### ISSUE TITLE
faceapi.allFaces returns an empty array

### ISSUE THREAD

**Issue by venu9l** [justadudewhohacks/face-api.js#101]
All things went well when my code is on Linux and when I copied my code to windows machine faceapi.allFaces returns an empty array

**Comment by justadudewhohacks** [comment]
What kind of graphics card do you have in your Linux and windows machine?

**Comment by venu9l** [comment]
Its Nvidia GeForce GTX 1050

**Comment by justadudewhohacks** [comment]
Can you upload your image and the cose Snippet you are using, so I can reproduce it?
