### ISSUE TITLE
How to use my model in face-api to recognize face

### ISSUE THREAD

**Issue by GangDevp** [justadudewhohacks/face-api.js#103]
The face-api.js throw error when I load my model. I found my model different with face-api's model by checked my model json .How to use my model in face-api to recognize face?

**Comment by justadudewhohacks** [comment]
Which model are you using? What kind of error is thrown?

**Comment by justadudewhohacks** [comment]
You can not simply load your own models, this library only allows you to load the provided models. If you want to load own models, use tfjs.

**Comment by GangDevp** [comment]
Thanks,I tried other palne to finish it.
