### ISSUE TITLE
Error on release version

### ISSUE THREAD

**Issue by joesalloum** [justadudewhohacks/face-api.js#104]
Dear when using the local version (debug version) the plugin works fine
when building a release version we get an error

![error](https://user-images.githubusercontent.com/3799066/47089120-bb6fef00-d228-11e8-93fd-6f19918b5285.png)

tho we installed an local certificate for ssl to run https since i thought it was a problem from the https

regards

**Comment by ScottDellinger** [comment]
Looks like your loading of the JSON is failing. Are you sure the path to the json files for your release version is correct?

**Comment by justadudewhohacks** [comment]
Not sure what debug and release mode means for you, but this error message comes from the model loading function, meaning in your release setup the uri to your model fikes are different.

**Comment by joesalloum** [comment]
okay thank you so much tomorrow i will check it
i’m using react

when building a release version (the version to be publish on a server) it looks like it’s changing something in the path i will check it back tomorrow and get back to you

thank you once again

have a nice evening

On Oct 17, 2018, at 11:51 PM, justadudewhohacks <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what debug and release mode means for you, but this error message comes from the model loading function, meaning in your release setup the uri to your model files are different.

**Comment by justadudewhohacks** [comment]
Alright, if in doubt, simply open the network tab in the dev tools of your browser and you should find out the uri of the request when loading the model.

**Comment by joesalloum** [comment]
thank you guys, yes on release version it's loading the path directly from localhost (react) not from the folder where the published website is

i will check the file and edit it it's better to use "./path" so we won't have the error

thank you again
