### ISSUE TITLE
WebGL Warning when using this API

### ISSUE THREAD

**Issue by JeroenClijmans** [justadudewhohacks/face-api.js#105]
Hello there,
I'm quite new to using Javascript and this API, and having read the tutorials and examples multiple times I'm having trouble getting this API to work. When running certain methods such as faceapi.tinyYolov2, the code fails and gives the following error:
`
Error: WebGL warning: texImage2D: Element is write-only, thus cannot be uploaded. (source: face-api.js: line 23: col 132152)`

I also get this error (same location) when running the method faceapi.locateFaces (and possibly during some more methods).   

This is my code:

```<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Face Recognition Test</title>
    <script src="../../modulesExtern/face-api/dist/face-api.js"></script>
</head>

<body>
<div id="container">
<img id="image" src="https://cdn-images-1.medium.com/max/1000/1*5XojINtKrkHFT3nOx6oW1g.jpeg">
<canvas id="myCanvas" width="200" height="100"></canvas>
<script type=module>
    const MODEL_URL = '../../modulesExtern/face-api/weights';
    let scoreThreshold = 0.5;
    let sizeType = 'lg';

    async function main() {
        await faceapi.loadTinyYolov2Model(MODEL_URL);
        const inputImgEl = document.getElementById("image");
        const { width, height } = inputImgEl;
        const canvas = document.getElementById("myCanvas");
        canvas.width = width;
        canvas.height = height;
        const forwardParams = {
            inputSize: sizeType,
            scoreThreshold
        };
        const detections = await faceapi.tinyYolov2(inputImgEl, forwardParams)
        // faceapi.drawDetection('myCanvas', detections.map(det => det.forSize(width, height)))
    }
    main();
</script>
</div>
</body>

</html>
```

Does anyone know what I'm doing wrong and/or how to solve it?

**Comment by ScottDellinger** [comment]
You're trying to load an image from an external source, which is a security problem. The way I got around that was to convert the remote image to a data uri and use that as the src of the image tag.

**Comment by JeroenClijmans** [comment]
This indeed was the issue. Thank you very much for your help! :)
