### ISSUE TITLE
Missing Age and Gender detection

### ISSUE THREAD

**Issue by MakarandKate** [justadudewhohacks/face-api.js#106]
Please add age and gender detection in lib

**Comment by justadudewhohacks** [comment]
Sounds like a reasonable extension. Any links to repos with pretrained models would be helpful.

**Comment by Bajajar** [comment]
> Sounds like a reasonable extension. Any links to repos with pretrained models would be helpful.

You can take a look at this [https://github.com/bharathvaj1995/gender-detection-tensorflowjs](url)
and the pretrained here [https://s3.ap-south-1.amazonaws.com/arunponnusamy/pre-trained-weights/gender_detection.model](url) However, I'm using this works [https://github.com/oarriaga/face_classification](url) and the results so far is pretty good. I would have provided the codes for that.

**Comment by ssamarug** [comment]
How could I perform transfer learning and train, over which models files, to add gender / age recognition. If I had an already trained model, how could I "plug" it into the API?

**Comment by justadudewhohacks** [comment]
Not sure if I understood correctly.

If you want to train your own model with transfer learning, I would actually try to use the face landmark model and replace the fully connected layer with an own one that outputs male / female.

Regarding the second question: What kind of model do you have? A tensorflow.js web model? If it is a plain tensorflow model you can probably convert it to a web model using the tfjs-converter tool.

**Comment by ssamarug** [comment]
Sorry, I'm new to TensorFlow. I'd need the outputs of face classification
to include gender and approximate age. I currently don't know how to do it,
not even in a way that would result in a model compatible with this API.

**Comment by ssamarug** [comment]
Sorry again. If I had a couple of TensoFlow.js Web models for gender / age classification of faces, could I "pipeline" them with each detected face from this API, maybe using single image recognition (not object detection), augmenting the face output predictions with these attributes?

**Comment by justadudewhohacks** [comment]
Yes, I mean the input of such a model would probably be the image of a face right? So you basically use face-api.js to detect and extract faces from an image and pass these into your network. Does that answer your question?

**Comment by ssamarug** [comment]
Yes, and thanks! I've just saw it was an enhancement request and tought it
could be part of the API itself. Again, sorry for my lack of knowledge.

**Comment by justadudewhohacks** [comment]
Some datasets:
https://susanqq.github.io/UTKFace/
https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/

**Comment by ssamarug** [comment]
Thanks! It will be of great help.

**Comment by justadudewhohacks** [comment]
Yeah, age and gender recognition is not implemented yet, I am collecting some resources at the moment.

**Comment by buggles333** [comment]
+1 from me, gender detection would be a great addition

**Comment by ShadabFaiz** [comment]
any updates on age / gender detection?

**Comment by examityharikrishna** [comment]
That's great!

**Comment by PutziSan** [comment]
Hi,
Thank you so much for the library, great work! I also find the age and gender recognition quite interesting and had seen that you had already started the implementation in a branch. Can you already give an estimate when you will release it?

**Comment by justadudewhohacks** [comment]
I am working on it a little bit more actively currently. Can't give any estimations yet when to I will release it, sorry. I have some first working versions, but I am constantly improving the model accuracy, trying to get close to state of the art.

**Comment by dkzeb** [comment]
> I am working on it a little bit more actively currently. Can't give any estimations yet when to I will release it, sorry. I have some first working versions, but I am constantly improving the model accuracy, trying to get close to state of the art.

First off - amazing work on this ;) 
is it possible to play around with your current implementation? do you have it in a branch that we can access?

**Comment by justadudewhohacks** [comment]
Age estimation and gender prediction is now implemented.

**Comment by examityharikrishna** [comment]
That's great news!

**Comment by thirukumars** [comment]
script.js:26 Uncaught (in promise) TypeError: faceapi.detectAllFaces(...).withFaceLandmarks(...).withFaceExpressions(...).withAgeGender is not a function



I got this error message while running,please help me out

**Comment by justadudewhohacks** [comment]
it should be withAgeAndGender and not withAgeGender

**Comment by thirukumars** [comment]
thank you and for draw

faceapi.draw.drawAgeAndGender is not a function

**Comment by thirukumars** [comment]
hello where do i found the code for recognizing two image without node and using javascript

**Comment by ismaildkc** [comment]
@thirukumars hello, i'm getting same error, "faceapi.draw.drawAgeAndGender is not a function"
did you solve that?
