### ISSUE TITLE
RGB or Grayscale in order to improve accuracy?

### ISSUE THREAD

**Issue by Bajajar** [justadudewhohacks/face-api.js#108]
At first, many thanks for your support and dedication to the project.

I'm just wondering, in order to improve accuracy, do we need to convert the media into gray-scale or just leave it at RGB before computeFaceDescriptor ?

As I can see that you've saved media as gray-scale in the example folder.

**Comment by justadudewhohacks** [comment]
Hi,

The example images just happen to be gray scale, RGB images should in general give better results. If there was a need to convert them, I would have provided the necessary utility for that.

**Comment by Bajajar** [comment]
Thank you for your clarification. I've tested the grey-scale method and the results were not much different from RGB.
