### ISSUE TITLE
faceLandmarks.getPositions is not a function

### ISSUE THREAD

**Issue by vbh25** [justadudewhohacks/face-api.js#112]
I called this function in webcamFaceTracking, drawing.js file.

**Comment by vbh25** [comment]
Then how can we get the positions?

**Comment by justadudewhohacks** [comment]
Simply use the property instead of the old getter: faceLandmarks.positions

**Comment by vbh25** [comment]
console.log("faceLandmarks positions: "+faceLandmarks.positions); 

It is saying "faceLandmarks positions: undefined"

**Comment by justadudewhohacks** [comment]
Then "faceLandmarks" is not an instance of faceapi.FaceLandmarks.

**Comment by vbh25** [comment]
is there anyway to get faceLandmarks as array in drawing.js ?

**Comment by buggles333** [comment]
I am getting similar results, my code is

`async function run() {
			
	await faceapi.loadTinyFaceDetectorModel('/models');
	await faceapi.loadFaceLandmarkTinyModel('/models');
			
	const input = document.getElementById('myImg');
	
	const useTinyModel = true
	const detectionsWithLandmarks  = await faceapi.detectAllFaces(input, new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks(useTinyModel);

	console.log("faceLandmarks positions: " + detectionsWithLandmarks.positions); 
			 
}`

Any ideas where I am going wrong?
