### ISSUE TITLE
Image blinking too much

### ISSUE THREAD

**Issue by vbh25** [justadudewhohacks/face-api.js#115]
I am drawing an image on using ctx in drawLandmarks. The image is blinking too much. Any reason / solution to avoid this?

**Comment by justadudewhohacks** [comment]
Manipulate the output canvas after the detection call, not before, to avoid the delay (see how it's done in the examples).

**Comment by vbh25** [comment]
I am manipulating in drawLandmarks function face-api.js file. I think it is after the detection call.
And where is it clearing the canvas?
