### ISSUE TITLE
Reference Error on TinyFaceDetectorOptions (and other options)

### ISSUE THREAD

**Issue by ScottDellinger** [justadudewhohacks/face-api.js#116]
I'm attempting to implement your new changes, but when I try to use: 

`const img1Description = await faceapi.detectSingleFace("s1", new TinyFaceDetectorOptions()).withFaceLandmarks().withFaceDescriptor()`

I get the following error:
`ReferenceError: TinyFaceDetectorOptions is not defined`

I've confirmed I've got the latest JavaScript files and have tried it across all browsers with the same result. I also get the same error for MtcnnOptions and SsdMobilenetv1Options. 

When I don't provide the options, the call is successful. What am I missing?

**Comment by justadudewhohacks** [comment]
I think it should be clear, that everything is accessible via faceapi and not on the global scope:
`new faceapi.TinyFaceDetectorOptions()`.

Sorry if the readme was confusing, I will adjust the snippets.

**Comment by ScottDellinger** [comment]
I figured it was something simple. That should have occurred to me. Thanks!
