### ISSUE TITLE
Face not getting detected in android phone, chrome browser.

### ISSUE THREAD

**Issue by vbh25** [justadudewhohacks/face-api.js#117]
https://justadudewhohacks.github.io/face-api.js/webcam_face_tracking

**Comment by justadudewhohacks** [comment]
Without any further information I can't help you.

What's the device you are using, is there any error message? Try opening a debug session and check the console.

**Comment by vbh25** [comment]
I am using Xiaomi Redmi 4 device. There is no error message. It is opening the camera but not detecting face.

**Comment by justadudewhohacks** [comment]
By the way, which chrome version are you using? I noticed yesterday, that after updating chrome to 69 on my android device, the webcam example doesn't work anymore properly.

I can also reproduce this on desktop with chrome 69. Chrome 70 works fine again, unfortunately chrome 70 doesn't seem to have arrived in the app store yet.

**Comment by vbh25** [comment]
chrome 69

**Comment by vbh25** [comment]
Chrome 70 is available on play store. And your demo works fine now !!

**Comment by justadudewhohacks** [comment]
Nice
