### ISSUE TITLE
0.15.0 Export issue - detectAllFaces missing

### ISSUE THREAD

**Issue by GantMan** [justadudewhohacks/face-api.js#119]
![image](https://user-images.githubusercontent.com/997157/47686535-b2c4d480-dba9-11e8-9942-f982c189bb10.png)

Looks like export failed.  Happy to test new version as needed.

**Comment by GantMan** [comment]
Also, missing is `detectSingleFace`

**Comment by justadudewhohacks** [comment]
Apparently an issue with export * notation picking up the entire directory instead of the index file. Not sure why some exports get lost this way though. Fix incoming...

**Comment by justadudewhohacks** [comment]
Should be resolved in 0.15.1.
