### ISSUE TITLE
Use SSD_MobileNet_V1 model, cause box width and height must be positive numbers

### ISSUE THREAD

**Issue by theangels** [justadudewhohacks/face-api.js#125]
Hello, I try to use face-api.js by follow this article
[https://itnext.io/face-api-js-javascript-api-for-face-recognition-in-the-browser-with-tensorflow-js-bcc2a6c4cf07](https://itnext.io/face-api-js-javascript-api-for-face-recognition-in-the-browser-with-tensorflow-js-bcc2a6c4cf07)

But when I run the code, the console output the error:

## Error

> face-api.js:1118 Uncaught (in promise) Error: Box.constructor - width (0.08514529466629028) and height (-0.15933257341384888) must be positive numbers
>     at Function.Box.assertIsValidBox (face-api.js:1118)
>     at Rect.Box (face-api.js:1103)
>     at new Rect (face-api.js:1387)
>     at face-api.js:4774
>     at Array.map (<anonymous>)
>     at SsdMobilenetv1.<anonymous> (face-api.js:4765)
>     at step (face-api.js:317)
>     at Object.next (face-api.js:298)
>     at fulfilled (face-api.js:288)

## Environment

Chrome: 70.0.3538.77
System: Windows10
Node.js: v11.0.0
express: v4.16.3

## Code

```
var MODEL_URL = '/models'
var canvas = $('#canvas')[0];

var imgObj = new Image();
imgObj.src = "/images/face-sample.jpg";
imgObj.onload = function(){
        var ctx = canvas.getContext('2d');
        ctx.drawImage(this, 0, 0);
    }

async function start() {
    var MODEL_URL = '/models'

    await faceapi.loadSsdMobilenetv1Model(MODEL_URL)
    await faceapi.loadFaceLandmarkModel(MODEL_URL)
    await faceapi.loadFaceRecognitionModel(MODEL_URL)

    console.log('Model loaded successed!')

    var input = canvas
    var fullFaceDescriptions = await faceapi.detectAllFaces(input).withFaceLandmarks().withFaceDescriptors()

    var detectionsArray = fullFaceDescriptions.map(fd => fd.detection)
    faceapi.drawDetection(canvas, detectionsArray, { withScore: true })

    const landmarksArray = fullFaceDescriptions.map(fd => fd.landmarks)
    faceapi.drawLandmarks(canvas, landmarksArray, { drawLines: true })

    console.log(detectionsArray)
}
start()
```

## Sample Image

![face-sample](https://user-images.githubusercontent.com/11308780/47908134-95547b00-dec7-11e8-9067-c4f46b22386e.jpg)

## Message

When this code run in my friends' computer, it works. I'm confused about it.
And When I try to play demo in this url [https://justadudewhohacks.github.io/face-api.js/face_and_landmark_detection](https://justadudewhohacks.github.io/face-api.js/face_and_landmark_detection), and I try to use SSD_MobileNet_V1 model, I got the same problem.

**Comment by justadudewhohacks** [comment]
Ahh yeah, that might be because you run the thing on an Intel GPU probably (please correct me if I am wrong with that assumption)? Intel GPUs seems to not be supported yet (https://github.com/tensorflow/tfjs/issues/510), thus the predicted bounding boxes are totally wrong resulting in this error.

Nevertheless, it might be better to handle bounding boxes, that are out of image borders, although it doesn't help in your case, since the prediction is simply wrong.

You could use the TinyFaceDetector, which should work with an Intel GPU.

**Comment by theangels** [comment]
> Ahh yeah, that might be because you run the thing on an Intel GPU probably (please correct me if I am wrong with that assumption)? Intel GPUs seems to not be supported yet ([tensorflow/tfjs#510](https://github.com/tensorflow/tfjs/issues/510)), thus the predicted bounding boxes are totally wrong resulting in this error.
> 
> Nevertheless, it might be better to handle bounding boxes, that are out of image borders, although it doesn't help in your case, since the prediction is simply wrong.
> 
> You could use the TinyFaceDetector, which should work with an Intel GPU.

Okay, I found that TinyFaceDetector is work for me, thank you.(But it is not accurate as SSD_MobileNet model XD)

**Comment by aserechenko** [comment]
Will Intel GPUs be supported at some point?

**Comment by skabbit** [comment]
Will Intel GPUs be supported at some point?
