### ISSUE TITLE
Error about Float32Array 

### ISSUE THREAD

**Issue by aarahvar** [justadudewhohacks/face-api.js#126]
Hi

When I open faceAndLandmarkDetection.html and some other files, I get the following error:

tf-core.esm.js:17 **Uncaught (in promise) RangeError: byte length of Float32Array should be a multiple of 4  at new Float32Array** (<anonymous>)
    at o (tf-core.esm.js:17)
    at decodeWeights (tf-core.esm.js:17)
    at tf-core.esm.js:17
    at Array.forEach (<anonymous>)
    at tf-core.esm.js:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (tf-core.esm.js:17)
    at tf-core.esm.js:17
    at Object.next (tf-core.esm.js:17)
o @ tf-core.esm.js:17
decodeWeights @ tf-core.esm.js:17
(anonymous) @ tf-core.esm.js:17
(anonymous) @ tf-core.esm.js:17
(anonymous) @ tf-core.esm.js:17
(anonymous) @ tf-core.esm.js:17
(anonymous) @ tf-core.esm.js:17
i @ tf-core.esm.js:17
async function (async)
run @ faceAndLandmarkDetection.html:186
(anonymous) @ faceAndLandmarkDetection.html:197
j @ jquery-2.1.1.min.js:2
fireWith @ jquery-2.1.1.min.js:2
ready @ jquery-2.1.1.min.js:2
I @ jquery-2.1.1.min.js:2

Any comment?

**Comment by freekoy** [comment]
Me too
`Uncaught (in promise) RangeError: byte length of Float32Array should be a multiple of 4
    at new Float32Array (<anonymous>)
    at o (io_utils.ts:116)
    at Object.decodeWeights (io_utils.ts:79)
    at e.<anonymous> (frozen_model.ts:109)
    at exports_regularizers.ts:47
    at Object.next (exports_regularizers.ts:47)
    at s (exports_regularizers.ts:47)`

**Comment by justadudewhohacks** [comment]
The error message is a bit confusing, but it might simply be, that the url to the model shards is simply wrong. Check out the network tab and verify, that the requests don't result in 404s.

**Comment by aarahvar** [comment]
> 
> 
> The error message is a bit confusing, but it might simply be, that the url to the model shards is simply wrong. Check out the network tab and verify, that the requests don't result in 404s.

Thanks, No message in the Network.
You can try yourself on my website: 
http://www.digibina.com/face-api/examples/views/faceAndLandmarkDetection.html

**Comment by aarahvar** [comment]
Everything is visible in my web now. You can see what I have in the web. I had to copy some folders to "views" folder to prevent some errors.

**Comment by justadudewhohacks** [comment]
The first shard doesn't load correctly: `ssd_mobilenetv1_model-shard1 | 206 | fetch | tf-core.esm.js:17 | 1.0 MB`. The size should be 4MB and not 1MB and the response code 206 is also suspicious to me. Maybe your file is corrupted or something?

**Comment by aarahvar** [comment]
> 
> 
> The first shard doesn't load correctly: `ssd_mobilenetv1_model-shard1 | 206 | fetch | tf-core.esm.js:17 | 1.0 MB`. The size should be 4MB and not 1MB and the response code 206 is also suspicious to me. Maybe your file is corrupted or something?

It seems that something was corrupted . I uploaded again and it is working now!

**Comment by justadudewhohacks** [comment]
Great!
