### ISSUE TITLE
Failed to Compile fragment Shader

### ISSUE THREAD

**Issue by rajeev-tbrew** [justadudewhohacks/face-api.js#128]
I am getting the following error suddenly since yesterday (was working fine till Nov 1) when I try to detect face using tiny-yolo. I had downloaded latest face-api.min.js on Oct 30th and it worked for a day and somehow started getting this error since yesterday.

![image](https://user-images.githubusercontent.com/38608333/48043981-726be480-e1af-11e8-8d34-bd15d0189af5.png)

Can you pls help on the same. I am including tfjs using  the following link.

<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script>

**Comment by justadudewhohacks** [comment]
Seems like an issue with tf latest maybe? Try to use the tfjs-core version, that face-api.js uses, which is 0.13.2 currently. I noticed some issues with 0.13.9 + WebGL backend.

**Comment by rajeev-tbrew** [comment]
Thank you.

You are right. It was an issue with tfjs as things work fine when I switch
to tfjs 0.13.2.
