### ISSUE TITLE
Webcam_face_tracking doesn't detect face when it is run locally in firefox browser on laptop.

### ISSUE THREAD

**Issue by veetechh** [justadudewhohacks/face-api.js#129]
I am using 63.0.1 firefox browser on windows 10. 

This works https://justadudewhohacks.github.io/face-api.js/webcam_face_tracking on both chrome & firefox.

but when it is run locally by npm start. It is opening the camera, but not detecting face in firefox. It works fine in chrome. And no logs too.

**Comment by vbh25** [comment]
any way to resolve this?

**Comment by ccccgn** [comment]
I have the same question and wonder how to resolve it.

**Comment by ccccgn** [comment]
It seems like the program stops at this line`
      const result = withFaceLandmarks
        ? await faceDetectionTask.withFaceLandmarks()
        : await faceDetectionTask`

**Comment by vbh25** [comment]
yes

**Comment by vbh25** [comment]
any workaround to solve this? like making delay.

**Comment by justadudewhohacks** [comment]
@vbh25, did you find a solution to that problem?

**Comment by vbh25** [comment]
calling videoEl.play() in videoEl.onloadedmetadata function .

**Comment by justadudewhohacks** [comment]
In fact, as @veetechh pointed out, moving onPlay to onloadedmetadata instead of onplay in the video element seems to solve it: `<video onloadedmetadata="onPlay(this)" id="inputVideo" autoplay muted></video>`.

Will fix this in the examples.

**Comment by zhongwei** [comment]
onloadedmetadata can't resolve my problem in firefox.

**Comment by justadudewhohacks** [comment]
Check in the fixed examples, closing here.
