### ISSUE TITLE
Error: Based on the provided shape, [1,1,16,32], and dtype float32, the tensor should have 512 values but has 93

### ISSUE THREAD

**Issue by psiservices-azubizarreta** [justadudewhohacks/face-api.js#131]
Hi! I'm having trouble making the library work on production. Everything works perfect locally.
Using angular 4. Here is the code:

`const detections: Array<any> = await faceapi.detectAllFaces(this.video, new faceapi.TinyFaceDetectorOptions({ inputSize: 128, scoreThreshold: 0.4 }));`

> ERROR Error: Uncaught (in promise): Error: Based on the provided shape, [1,1,16,32], and dtype float32, the tensor should have 512 values but has 93
Error: Based on the provided shape, [1,1,16,32], and dtype float32, the tensor should have 512 values but has 93
    at c (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at new t (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at Function.t.make (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at Ht (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at o (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at $a (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at scripts.208b17eda93ff84a86fa.bundle.js:1
    at Array.forEach (<anonymous>)
    at scripts.208b17eda93ff84a86fa.bundle.js:1
    at Array.forEach (<anonymous>)
    at c (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at new t (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at Function.t.make (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at Ht (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at o (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at $a (scripts.208b17eda93ff84a86fa.bundle.js:1)
    at scripts.208b17eda93ff84a86fa.bundle.js:1
    at Array.forEach (<anonymous>)
    at scripts.208b17eda93ff84a86fa.bundle.js:1
    at Array.forEach (<anonymous>)
    at S (polyfills.b05dc6a29a1cfeb080d6.bundle.js:1)
    at polyfills.b05dc6a29a1cfeb080d6.bundle.js:1
    at a (main.424b2f298a047510607b.bundle.js:1)
    at t.invoke (polyfills.b05dc6a29a1cfeb080d6.bundle.js:1)
    at Object.onInvoke (main.424b2f298a047510607b.bundle.js:1)
    at t.invoke (polyfills.b05dc6a29a1cfeb080d6.bundle.js:1)
    at e.run (polyfills.b05dc6a29a1cfeb080d6.bundle.js:1)
    at polyfills.b05dc6a29a1cfeb080d6.bundle.js:1
    at t.invokeTask (polyfills.b05dc6a29a1cfeb080d6.bundle.js:1)
    at Object.onInvokeTask (main.424b2f298a047510607b.bundle.js:1)
$ @ main.424b2f298a047510607b.bundle.js:1
t.handleError @ main.424b2f298a047510607b.bundle.js:1
next @ main.424b2f298a047510607b.bundle.js:1
e.object.i @ main.424b2f298a047510607b.bundle.js:1
e.__tryOrUnsub @ main.424b2f298a047510607b.bundle.js:1
e.next @ main.424b2f298a047510607b.bundle.js:1
e._next @ main.424b2f298a047510607b.bundle.js:1
e.next @ main.424b2f298a047510607b.bundle.js:1
e.next @ main.424b2f298a047510607b.bundle.js:1
e.emit @ main.424b2f298a047510607b.bundle.js:1
(anonymous) @ main.424b2f298a047510607b.bundle.js:1
t.invoke @ polyfills.b05dc6a29a1cfeb080d6.bundle.js:1
e.run @ polyfills.b05dc6a29a1cfeb080d6.bundle.js:1
t.runOutsideAngular @ main.424b2f298a047510607b.bundle.js:1
onHandleError @ main.424b2f298a047510607b.bundle.js:1
t.handleError @ polyfills.b05dc6a29a1cfeb080d6.bundle.js:1
e.runGuarded @ polyfills.b05dc6a29a1cfeb080d6.bundle.js:1
t @ polyfills.b05dc6a29a1cfeb080d6.bundle.js:1
n.microtaskDrainDone @ polyfills.b05dc6a29a1cfeb080d6.bundle.js:1
d @ polyfills.b05dc6a29a1cfeb080d6.bundle.js:1

Also the video is 351x360 pixels

**Comment by justadudewhohacks** [comment]
Not sure why the code snippet shown above should make any difference in production.

Looking at the error message your issue most likely resides in loading a model. Check that the model files are served correctly in your production environment.

**Comment by psiservices-azubizarreta** [comment]
Models are being served correctly. How can I verify if they are being loaded correctly?

**Comment by psiservices-azubizarreta** [comment]
Thanks! That solved it!

**Comment by huiyuye** [comment]
@psiservices-azubizarreta Can you tell me how to solve? I have a same error

**Comment by nannan9507** [comment]
@psiservices-azubizarreta Hello ! I hava a same problem as you met, and it's very peremptorily, so。。Can you tell us the way to solve this situation plz ? my very thanks!

**Comment by frank505** [comment]
a bit stuck here too how did you solve it on production?

**Comment by atmosuwiryo** [comment]
For me, this problem caused by uploading process to prod env using filezilla. It's solved by change the transfer type to binary.

Sorry for commenting on closed issue.

**Comment by neel448** [comment]
@atmosuwiryo this helped!

**Comment by avalanche1** [comment]
I managed to solve it serving model files from a [cdn](https://gitcdn.xyz/)
Use https://gitcdn.xyz/repo/justadudewhohacks/face-api.js/master/weights/ as `MODEL_URL`

**Comment by aryehrein** [comment]
That address seems invalid...

**Comment by avalanche1** [comment]
@aryehrein , well it tends to hibernate occasionally. You have to wake it up by pasting the link to `weights` folder manually on https://gitcdn.xyz/

**Comment by aryehrein** [comment]
It was actually a different problem - the json files managed to get loaded, but the non extension files (e.g.  "age_gender_model-shard1") weren't. So what I did - I used my downloaded "weights" folder (and not the cdn), and for each model I :
1. added a fictional ".shard" extension for the non extension file.
2. opened the corresponding "..._manifest.json" file and changed the "path" property to the new file name including the ".shard" extension.

For example:
1. /age_gender_model-shard1 renamed to /age_gender_model-shard1.shard
2. opened age_gender_model-weights_manifest.json, and changed 
`"paths":["age_gender_model-shard1"]`
to:
`"paths":["age_gender_model-shard1.shard"]`

Pay attention that some manifest.json files have 2 paths

**Comment by udit4** [comment]
@aryehrein It tried that (adding extension in non-extension files) but it is still not working !!

**Comment by aryehrein** [comment]
@udit4 What error do you get?

**Comment by udit4** [comment]
@aryehrein i am getting this => Error: Based on the provided shape, [1,1,128,256], the tensor should have 32768 values but has 12137

**Comment by jairforero** [comment]
Please help 
face-api.min.js:1 Uncaught (in promise) Error: Based on the provided shape, [25], the tensor should have 25 values but has 21

**Comment by aniskoubaa** [comment]
> 1. .shard

This solution worked for me. Thanks!
But this strange why it needs an extension for production on iOS.

**Comment by IncreikeSoul** [comment]
> > 1. .shard
> 
> This solution worked for me. Thanks!
> But this strange why it needs an extension for production on iOS.

I have the same problem with "Uncaught (in promise) Error: Based on the provided shape, [3,3,32,1], the tensor should have 288 values but has 109" in the context when i am deploying my example at the google cloud instance vm.
I changed the path in loadFromUri(models) to my domain https and nothing happens, then i tried to change extensions on non-extension files but idk.

My face-api.js and .json files are loaded.

![image](https://user-images.githubusercontent.com/22384296/86063098-b8825580-ba2f-11ea-85bc-e82a340f768d.png)

**Comment by maxim1006** [comment]
Maybe it will help somebody:

The error occurred when I started my local server with --spa, when removed it error gone

**Comment by nosuko** [comment]
@aryehrein Changing the file names worked for me! (adding an extension to -shard1 files). Thanks for the tip!! I hope it will help more people.

I would say that in my case I was developing an Ionic 5 (angular) app with face-api. It worked with ionic when testing with "ionic serve" in Chrome browser. It failed (and I need to apply this fix) when I created the app and tested in a real android device.

**Comment by LakshmanaBP** [comment]
Added .bin file extension to tiny_face_detector tfjs model. Else the file is not being served in production mode.

Changed the file `"face_detector_model-shard1"` to `"tiny_face_detector_model-shard1.bin" `and updating the path in  detector_model-weights_manifest.json file like below
`"paths":["tiny_face_detector_model-shard1.bin"] `

**Comment by rezanos** [comment]
> Added .bin file extension to tiny_face_detector tfjs model. Else the file is not being served in production mode.
> 
> Changed the file `"face_detector_model-shard1"` to `"tiny_face_detector_model-shard1.bin" `and updating the path in detector_model-weights_manifest.json file like below
> `"paths":["tiny_face_detector_model-shard1.bin"] `

Thanks! that's the solution
setting .bin extension makes Content-Type: application/octet-stream for response

**Comment by JMHeartley** [comment]
Hello all, 
Instead of changing anything about the files I set the MIME type mapping in IIS for "." (no extension) to "application/octet-stream" this make it so it's served as a binary file and my program works just fine now using Blazor. I haven't tested this on IIS express but it might be possible to do the same or similar.

**Comment by andrewviva** [comment]
My webserver does not allow paths to be accessed by the browser so I get 404 errors even though the models directory exists.  Is there another way that I can load these net jsons?

**Comment by JMHeartley** [comment]
My first thought is to host them on some site for free and lots them from there but you might be able to do something else with the updated version of this project => https://github.com/vladmandic/face-api

**Comment by Omar52344** [comment]
works for me change extension of the File wihtout extension change for .bin an manifest.json also change in paths 
work for me thanks IN ANGULAR

![image](https://github.com/justadudewhohacks/face-api.js/assets/89212762/2a5f2237-4d3b-4a35-8e7d-e44cc72d8d6a)

![image](https://github.com/justadudewhohacks/face-api.js/assets/89212762/a4577898-e9fb-4797-87cf-1bee972bd9a2)

**Comment by yanniscybevasion** [comment]
the problem can sometimes come from your browser cache

**Comment by Aditya621** [comment]
If you guys are still not able to solve check out this.

I tried one whole day to **solve** and here is the solution that works for me. 

**LMK** in the comment down if it works for you

1. I moved all my model files to public > models.
2. .bin added at last like change **face_landmark_68_model-shard1** to **face_landmark_68_model-shard1.bin** 
3. make sure you go to the JSON file and change the path to **face_landmark_68_model-shard1.bin** 

Thanks for reading :)

<img width="580" alt="Screenshot 2024-10-04 at 11 36 45 PM" src="https://github.com/user-attachments/assets/144a6cc2-968f-42d9-b0a1-92d829f4e919">
<img width="545" alt="Screenshot 2024-10-04 at 11 40 30 PM" src="https://github.com/user-attachments/assets/3fc858c5-7f4b-4b2e-b530-15bf70b02ae5">

**Comment by Jeonjareinji** [comment]
> If you guys are still not able to solve check out this.
> 
> I tried one whole day to **solve** and here is the solution that works for me.
> 
> **LMK** in the comment down if it works for you
> 
> 1. I moved all my model files to public > models.
> 2. .bin added at last like change **face_landmark_68_model-shard1** to **face_landmark_68_model-shard1.bin**
> 3. make sure you go to the JSON file and change the path to **face_landmark_68_model-shard1.bin**
> 
> Thanks for reading :)
> 
> <img alt="Screenshot 2024-10-04 at 11 36 45 PM" width="580" src="https://private-user-images.githubusercontent.com/56670647/373757794-144a6cc2-968f-42d9-b0a1-92d829f4e919.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDU5NzksIm5iZiI6MTcyOTA0NTY3OSwicGF0aCI6Ii81NjY3MDY0Ny8zNzM3NTc3OTQtMTQ0YTZjYzItOTY4Zi00MmQ5LWIwYTEtOTJkODI5ZjRlOTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAyMjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNGZjOWMxM2UzOGE5MWRiYjZhYjQ1OGVlYTYxZDQyODcyY2ZiNmQyNTBmNjJhNjQzNzg0MDlkMDBlZjUwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lOL_CIg3Dv5c7bWTEU9GB_WdMD9mbEe11NZc19JvsGE"> <img alt="Screenshot 2024-10-04 at 11 40 30 PM" width="545" src="https://private-user-images.githubusercontent.com/56670647/373758746-3fc858c5-7f4b-4b2e-b530-15bf70b02ae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDU5NzksIm5iZiI6MTcyOTA0NTY3OSwicGF0aCI6Ii81NjY3MDY0Ny8zNzM3NTg3NDYtM2ZjODU4YzUtN2Y0Yi00YjJlLWI1MzAtMTViZjcwYjAyYWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAyMjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1Yzc5NWJmMzE2YmQwZjA1MTNmMmUwMGJhZTExYTY0NzNkZjc1YWIwZDMxZmIwNDY5NzVjNzhmMzkyYzA1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9msKaPPuDTfWi5lTv2leb6FMb2aeN044sIxk0KxrxNo">

just change 3 files extension name to bin or all of file in model change to bin too ?

**Comment by JMHeartley** [comment]
@Jeonjareinji 
> just change 3 files extension name to bin or all of file in model change to bin too ?

Update the names of the shard files to include ".bin" and update the shared file name within the corresponding json files to include ".bin" as well

**Comment by sarwjeet1** [comment]
Thanks it really works .

**Comment by yellhtutpromax** [comment]
T

> It was actually a different problem - the json files managed to get loaded, but the non extension files (e.g. "age_gender_model-shard1") weren't. So what I did - I used my downloaded "weights" folder (and not the cdn), and for each model I :
> 
> 1. added a fictional ".shard" extension for the non extension file.
> 2. opened the corresponding "..._manifest.json" file and changed the "path" property to the new file name including the ".shard" extension.
> 
> For example:
> 
> 1. /age_gender_model-shard1 renamed to /age_gender_model-shard1.shard
> 2. opened age_gender_model-weights_manifest.json, and changed
>    `"paths":["age_gender_model-shard1"]`
>    to:
>    `"paths":["age_gender_model-shard1.shard"]`
> 
> Pay attention that some manifest.json files have 2 paths

```
This work for me , In case if you still facing this kind of issue , check inside the ( face_recognition_model-weights_manifest.json )
inside this file there is another file is linked put this file also ( face_recognition_model-shard2.shard )
```
