### ISSUE TITLE
Error on latest version of tensorflowjs

### ISSUE THREAD

**Issue by Bajajar** [justadudewhohacks/face-api.js#133]
I got an error when implement the latest version of tensorflowjs in html file `<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@latest"></script>`

> Uncaught (in promise) Error: Failed to compile fragment shader.
>     at createFragmentShader (tfjs@latest:2)
>     at e.createProgram (tfjs@latest:2)
>     at compileProgram (tfjs@latest:2)
>     at tfjs@latest:2
>     at e.getAndSaveBinary (tfjs@latest:2)
>     at e.compileAndRun (tfjs@latest:2)
>     at e.maxPool (tfjs@latest:2)
>     at ENV.engine.runKernel.x (face-api.js:23)
>     at tfjs@latest:2
>     at e.scopedRun (tfjs@latest:2)

It looks like FaceRecognitionModel can only compatible tensorflowjs under 0.13.0.

**Comment by justadudewhohacks** [comment]
Answered here: #128. Always use the same tfjs-core version as face-api.js, which is 0.13.8 now.
