### ISSUE TITLE
How to compare two faces on two pictures in the browser?

### ISSUE THREAD

**Issue by arpsyapathy** [justadudewhohacks/face-api.js#136]
Hi, everybody! 
I want to compare two faces in two photos with your beautiful face-api.js.
But I do not quite understand the algorithm how to do it... 

Can you show me a simple example of how to do this in a browser?

Thank you!

**Comment by justadudewhohacks** [comment]
You can simply compare their face descriptors by euclidean distance:

``` javascript
const distance = faceapi.euclideanDistance(descriptor1, descriptor2)
```

You can get the FullFaceDescription of all faces in an image as described in the README:

``` javascript
const fullFaceDescriptions = await faceapi.detectAllFaces(img).withFaceLandmarks().withFaceDescriptors()
```

A FullFaceDescription contains the detection, landmarks and descriptor as shown [here](https://github.com/justadudewhohacks/face-api.js#interface-full-face-description)

**Comment by psyapathy** [comment]
@justadudewhohacks Hello friend!
Thank you!
Like this?:

`
<html>
    <head>
        <script src="/face/face/face-api.js"></script>
    </head>
    <body>
        <img id="myImg1" src="http://site.com/oo/o1.jpg" />
        <img id="myImg2" src="http://site.com/oo/o2.jpg" />
    </body>
    <script>
    const input1 = document.getElementById('myImg1');
    const input2 = document.getElementById('myImg2');
    const detection1 = faceapi.detectAllFaces(input1).withFaceLandmarks().withFaceDescriptors();
    const detection2 = faceapi.detectAllFaces(input2).withFaceLandmarks().withFaceDescriptors();
    const distance = faceapi.euclideanDistance(detection1, detection2);
    console.log(distance);
    </script>
</html>
`

**Comment by land007** [comment]
[ { detection: 
     FaceDetection {
       _imageDims: [Dimensions],
       _score: 0.9839361906051636,
       _classScore: 0.9839361906051636,
       _className: '',
       _box: [Box] },
    landmarks: FaceLandmarks68 { _imgDims: [Dimensions], _shift: [Point], _positions: [Array] },
    unshiftedLandmarks: FaceLandmarks68 { _imgDims: [Dimensions], _shift: [Point], _positions: [Array] },
    alignedRect: 
     FaceDetection {
       _imageDims: [Dimensions],
       _score: 0.9839361906051636,
       _classScore: 0.9839361906051636,
       _className: '',
       _box: [Box] },
    descriptor: 
     Float32Array [
       -0.07600060850381851,
       0.09135700017213821,
       0.01828434318304062,
       -0.10295865684747696,
       -0.11790119111537933,
       -0.07359399646520615,
       -0.0860370621085167,
       -0.1646803319454193,
       0.17641472816467285,

**Comment by meedwire** [comment]
is there any way to compare two faces using the node ?

**Comment by shanurrahman-gcsns** [comment]
> is there any way to compare two faces using the node ?
I guess you can use this
`import { euclideanDistance } from 'face-api.js'`

**Comment by Nilesh-7296** [comment]
> @justadudewhohacks Hello friend!
> Thank you!
> Like this?:
> 
> ```
> <html>
>     <head>
>         <script src="/face/face/face-api.js"></script>
>     </head>
>     <body>
>         <img id="myImg1" src="/site.com/oo/o1.jpg" />
>         <img id="myImg2" src="/site.com/oo/o2.jpg" />
>     </body>
>     <script>
>     const input1 = document.getElementById('myImg1');
>     const input2 = document.getElementById('myImg2');
>     const detection1 = faceapi.detectAllFaces(input1).withFaceLandmarks().withFaceDescriptors();
>     const detection2 = faceapi.detectAllFaces(input2).withFaceLandmarks().withFaceDescriptors();
>     const distance = faceapi.euclideanDistance(detection1, detection2);
>     console.log(distance);
>     </script>
> </html>
> ```

this code showing this error,,,,

Uncaught (in promise) Error: SsdMobilenetv1 - load model before inference

**Comment by aakruti27** [comment]
You need to have a model folder (at the same location as your html and js files) with all the required models which can be found [here](https://github.com/justadudewhohacks/face-api.js/tree/master/weights)
