### ISSUE TITLE
Camera doesn't open in ios. 

### ISSUE THREAD

**Issue by vbh25** [justadudewhohacks/face-api.js#137]
I am trying in iphone 6s, IOS 12, safari & chrome 70. It is opening camera in safari but face not getting detected. But it doesn't open camera in chrome. Can you please help?

**Comment by prasadkawthekar** [comment]
@veetechh I am getting the same issue. Did you end up finding the problem? Thanks.

**Comment by lucasavila00** [comment]
```typescript
  const stream = await navigator.mediaDevices.getUserMedia(
    cameraConfig,
  );

  const video = document.createElement("video");
  video.setAttribute("autoplay", "true");
  video.setAttribute("playsinline", "true");
  video.setAttribute("muted", "true");
  video.setAttribute("loop", "true");
  video.setAttribute("controls", "true");
  video.srcObject = stream;
  await video.play();

```

**Comment by muhroots** [comment]
> ```ts
>   const stream = await navigator.mediaDevices.getUserMedia(
>     cameraConfig,
>   );
> 
>   const video = document.createElement("video");
>   video.setAttribute("autoplay", "true");
>   video.setAttribute("playsinline", "true");
>   video.setAttribute("muted", "true");
>   video.setAttribute("loop", "true");
>   video.setAttribute("controls", "true");
>   video.srcObject = stream;
>   await video.play();
> ```
