### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by rohanmahajan1993** [justadudewhohacks/face-api.js#139]
Hi, 
I was trying to learn deep learning and found your projects very cool. I wanted to train my own model and was wondering if you would mind sharing the dataset you used for the tiny_face_detector_model and the dataset you used for the 68k landmark detector.
Thanks,
Rohan

**Comment by justadudewhohacks** [comment]
Hello Rohan,

Send me a mail to the email address on my github profile then I will give you permission to download the dropbox folder for the datasets.

**Comment by chuan92** [comment]
@justadudewhohacks would you mind sharing your landmark dataset(~35k), thanks.
