### ISSUE TITLE
Is there any way to speed up the process of loading the page in the browser?

### ISSUE THREAD

**Issue by arpsyapathy** [justadudewhohacks/face-api.js#140]
Hello!

When loading the demo page (bbtFaceSimilarity) the browser hangs and waits for 10-15 seconds and then only gives the result. I take it this is a library download? Is there any way to speed up the process to avoid hanging?

**Comment by psyapathy** [comment]
@justadudewhohacks
I understood. thank you! 
Is there a minimum version?

**Comment by justadudewhohacks** [comment]
The 6MB version is already the compressed model, there is no smaller one.
