### ISSUE TITLE
I don't have acccess to all functionality of the API

### ISSUE THREAD

**Issue by WToon** [justadudewhohacks/face-api.js#141]
I can only load models through the loadModels() function, not the individual loading functions as described in the 'Usage' section of the repository. Any other function gives me errors such as "faceapi.nets.ssdMobilenetv1.loadFromUri is not a function".
I got the face-api.js file from the 'dist' folder and included that globally, is this an incorrect way of accessing the API?
(I am working with JS and React for the first time)

**Comment by justadudewhohacks** [comment]
You are probably not using the latest version. If you are using react, then you probably use a bundler such as webpack, parcel etc. and can just npm install it to get the latest version.

**Comment by WToon** [comment]
Turned out I was indeed not using the latest version. I apologise for the stupid question and appreciate the quick response very much. Very cool repository!
