### ISSUE TITLE
Loading labeledFaceDescriptors into React state from backend

### ISSUE THREAD

**Issue by ricksmith26** [justadudewhohacks/face-api.js#145]
Hi Vincent,

I am trying to make a React frontend with facial recognition and want to send the labeledFaceDescriptors from a backend into state when the page loads. 

When the labeledFaceDescriptor is made it console logs as follows and can be used by the faceMatcher:
[LabeledFaceDescriptors, LabeledFaceDescriptors, LabeledFaceDescriptors]
0: LabeledFaceDescriptors {_label: "milo", _descriptors: Array(1)}
1: LabeledFaceDescriptors {_label: "rick", _descriptors: Array(1)}
2: LabeledFaceDescriptors {_label: "teo", _descriptors: Array(1)}

However when I save this on the backend and send this through to the frontend is comes out as follows and faceMatcher will not use is despite the structure being the same:
(3) [{…}, {…}, {…}]
0: {_label: "milo", _descriptors: Array(1)}
1: {_label: "rick", _descriptors: Array(1)}
2: {_label: "teo", _descriptors: Array(1)}

I think the issue has something to do with it losing the LabeledFaceDescriptors and it being replaced with  {…}.

Is it possible to get around this anyway?

Thanks

Rick

**Comment by ricksmith26** [comment]
I have got past this issue now, thanks anyway

**Comment by justadudewhohacks** [comment]
Okay, just for future reference:. You can not simply use object rest spead (... operator) or object.assign to serialize a class instance.
