### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by joesalloum** [justadudewhohacks/face-api.js#146]
faceapi.allFacesMtcnn

is there any function to get single face mtcnn not all faces available ???
i working on face recognition login database and i need to get ONLY 1 face

**Comment by justadudewhohacks** [comment]
Did you read the readme? Check out detectSingleFace.

**Comment by ricksmith26** [comment]
this works, I have used it always returns the most prominent person in the shot 

await faceapi.detectSingleFace(image).withFaceLandmarks().withFaceDescriptor();
