### ISSUE TITLE
How to find similar faces in the database?

### ISSUE THREAD

**Issue by psyapathy** [justadudewhohacks/face-api.js#147]
Hello!
I have the photo№1 with need face. 
And i have a base of 100 photos. 
Among these 100 photos there is a photo with the original face from 1 photo.

How to implement the mechanism of search for similar persons in the database? It is possible?

I need to collect the descriptors of all these photos in database?
`const fullFaceDescription = await faceapi.detectSingleFace(input).withFaceLandmarks().withFaceDescriptor()`

And then compare the descriptors with the descriptor photo №1 (distance)?
 
Or i need use "Face Recognition by Matching Descriptors"?

Tell me how to do please. I want to understand the algorithm of the necessary actions.

Thank you advance!

**Comment by justadudewhohacks** [comment]
I dont fully understand the question, but you want to compute the descriptor for every face in the database and then compare them by computing the euclidean distance between the descriptor of your photo and the descriptors from your database. As a threshold value to detwrmine whether two faces are similar you can use 0.6.

**Comment by psyapathy** [comment]
Sorry for my bad English..

I'll try to explain better
I have a photo of my face. 
I want to find photos with similar faces among 100 other photos. 
But I want to keep these 100 photos in my database. 
I have database with links to 100 images and their descriptors. 
What is the fastest way (method) to find let's say 5 most similar photos from 100?
Like on schema
![Schema Face](http://t.torly.ru/schemface.png)

**Comment by justadudewhohacks** [comment]
This library provides you the means to decide, whether two faces show the same person or not, by computing the euclidean distance of their descriptors. From their on you will have to figure out an algorithm to solve your problem, given the means that face-api.js provides.

Regarding your second question: A descriptor is nothing more than a Float32Array with 128 values, so yes you can store them in a database.
