### ISSUE TITLE
How can I start just with tinyFaceDetector?

### ISSUE THREAD

**Issue by gooczy** [justadudewhohacks/face-api.js#149]
seems all code packing up into face-api, so how can I get this 190k tiny face detector package?

**Comment by gooczy** [comment]
after study,I still have no idea how to start with tiny face detector... I can not found manifest.json...

**Comment by justadudewhohacks** [comment]
You can get all the weights and manifest files are here: https://github.com/justadudewhohacks/face-api.js/tree/master/weights. The files with the prefix `tiny_face_detector` is what you want to get.

**Comment by gooczy** [comment]
well,I got it,thank you
