### ISSUE TITLE
Using face detection on archived videos with NodeJS

### ISSUE THREAD

**Issue by Zelxy** [justadudewhohacks/face-api.js#150]
Sorry if I'm missing something in the documentation but I'm not quite sure how would I extract and match faces on a video located somewhere in the server? Since it's expecting HTML elements and node canvas doesn't seem to be compatible with a function that loads a video.

**Comment by justadudewhohacks** [comment]
You will have to read and decode the frames of the video and create tensors out of the image data using a third party package. For example opencv4nodejs (which is probably overkill for simply reading video) or node-ffmpeg.

**Comment by Zelxy** [comment]
Thank you very much, ffmpeg was the package I was thinking about since I later need to do some video manipulation anyway :) in a similar question, would it be preferred to convert the image directly into a tensor or loading each one to the canvas with the loadImage function? I can't seem to find any decent comparison in performance and I'm not in power to do a full test right now.

**Comment by justadudewhohacks** [comment]
Sorry for late reply, if you get the decoded image data using ffmpeg then there is no need to convert it to a canvas, you can straight create a tensor from the data, which should also be faster. The main reason I use the canvas package in nodejs is because of the decoding of images.

**Comment by justadudewhohacks** [comment]
Yes, you forgot the `await` keyword, so detections in your case is a Promise:
`const detections = await faceapi.detectAllFaces(videoElement, options)`

**Comment by sathyamoorthyrr** [comment]
Thank you very much. I figured that out and deleted the comment before refreshing the page(before seeing your reply). Never thought you would reply immediately!
@justadudewhohacks
