### ISSUE TITLE
SOLVED: Webpack warning about not found "fs" module

### ISSUE THREAD

**Issue by etienne-martin** [justadudewhohacks/face-api.js#154]
I get the following warning when building my webapp with webpack:

```
[1] WARNING in ../node_modules/tfjs-image-recognition-base/build/es6/env/initialize.js
[1] Module not found: Error: Can't resolve 'fs' in '/Users/username/project/node_modules/tfjs-image-recognition-base/build/es6/env'
[1]  @ ../node_modules/tfjs-image-recognition-base/build/es6/env/initialize.js
[1]  @ ../node_modules/tfjs-image-recognition-base/build/es6/env/index.js
[1]  @ ../node_modules/tfjs-image-recognition-base/build/es6/index.js
[1]  @ ../node_modules/face-api.js/build/es6/index.js
[1]  @ ./src/index.tsx
```

I had to add the following to my webpack config to suppress the warning:

```
node: {
   fs: "empty"
}
```

It's weird because the target in my webpack config is set to `web`.

Am I doing something wrong? If not, this issue may help other people with the same warning.

**Comment by justadudewhohacks** [comment]
Thanks for reporting your solution!

It's because webpack sees the require('fs') in the code, but although it won't be required in a browser environment. face-api.js is not only a library for the browser anymore, if you are running in a nodejs environment fs will be required and used for reading model files from disk.

**Comment by etienne-martin** [comment]
Got it, do you think there's a way to suppress the warning on the library side so that webpack doesn't complain?

**Comment by etienne-martin** [comment]
Thanks for your awesome work btw, it's really impressive how easy it is to implement facial detection using your library. Love it 🙏

**Comment by justadudewhohacks** [comment]
Hmm not sure if it's possible from the side of the library. The issue is the conditional require, since webpack cannot evaluate the condition. So I think your solution is the correct one, telling webpack, that it is safe to ignore the fs module.

**Comment by etienne-martin** [comment]
Alright, I don't have time to investigate that monkeyPatch thing so I'll just close the issue for now. 

Thanks again.

**Comment by francisacosta** [comment]
to ignore the error. add this code on your webpack.mix.js

`mix.webpackConfig({
    node: {
        fs: 'empty',
    }
})`

**Comment by maccuaa** [comment]
For webpack 5 you need:

```js
resolve: {
    fallback: {
      fs: false
    }
  }
```

This really should be fixed in this lib though. Having to do this in my webpack config is clunky.

**Comment by peterchaula** [comment]
@maccuaa your solution worked for me. The warning went away. For anyone curious as to how the resolve option fixes the issue, please read the webpack docs https://webpack.js.org/configuration/resolve/#resolvefallback

**Comment by akosiyawin** [comment]
For anyone using Laravel 8 with webpack ^5 and has encounter this issue you need to configure your `webpack.mix.js` and add:

```
mix.webpackConfig({
    resolve: {
        fallback: { fs: false }
    }
});
```

This one is for webpack < 5 : 
`mix.webpackConfig({ node: { fs: 'empty', } })`

**Comment by sahajkedia** [comment]
Hi, for  next application, where do you think I need to add the code 

`mix.webpackConfig({
    resolve: {
        fallback: { fs: false }
    }
});
`

**Comment by etienne-martin** [comment]
@sahajkedia for next.js I think you can achieve similar results by adding the following to your project's package.json:

```
"browser": {
   "fs": false
}
```
