### ISSUE TITLE
Can´t get nodejs examples working

### ISSUE THREAD

**Issue by ollfa** [justadudewhohacks/face-api.js#164]
Hello, can't figure out how to run examples for nodejs. Browser examples works fine.  
Followed instructions in readme:
>git clone https://github.com/justadudewhohacks/face-api.js.git
>
>cd face-api.js/examples/examples-nodejs
>npm i
>
> tsc faceDetections
>Output: https://pastebin.com/huEH2RVQ
>and
>ts-node faceDetection.ts
>Output: https://pastebin.com/7AFfM6ki

Machine is Ubuntu 16,04 on AWS.

**Comment by persone16** [comment]
Right, i have that npm not installed. How can i fix this?

**Comment by justadudewhohacks** [comment]
You shouldn't need python to run the nodejs examples.

You only need python (or pip for that matter) to install @tensorflow/tfjs-node, but I am also using python 3.6 and it works fine.

**Comment by persone16** [comment]
It installed, then i deleted from variable path python 3.7., and then i installed python 2.7.

**Comment by ollfa** [comment]
Solved, thanks! Was using wrong version of tfjs-core.
