### ISSUE TITLE
Detecting open mouth from webcam feed

### ISSUE THREAD

**Issue by lewisdonovan** [justadudewhohacks/face-api.js#165]
Hey, thanks so much for sharing this project, it's awesome!
Just wondering what's the easiest way to detect when a user opens and closes their mouth? I've used `landmarks.getMouth()` and logged the result into the console, but I can't find any documentation for which points relate to which parts of the mouth, so I'm not sure where to start calculating.

Cheers

**Comment by justadudewhohacks** [comment]
Have a look at this [figure](https://www.pyimagesearch.com/wp-content/uploads/2017/04/facial_landmarks_68markup.jpg). Using `landmarks.getMouth()` you simply get an array of Points 49 to 68.

**Comment by lewisdonovan** [comment]
Perfect, thanks

**Comment by lewisdonovan** [comment]
The co-ordinates in the `getMouth()` array don't seem to bear much relation to the actual position of the mouth on the face being tracked. I've added the following:

```
setInterval(() => {
  mouth = landmarks.getMouth()
  if (mouth) {
    checker = document.getElementById('pointChecker')
    checker.innerHTML = ''
    mouth.map(function(point){
      span = document.createElement('span')
      checker.appendChild(span)
      span.style.left = point.x +'px'
      span.style.top = point.y +'px'
    })
  }
}, 100)
```

But the results don't match up to the mouth on the face being tracked by the draw function:
<img width="409" alt="screen shot 2018-12-12 at 16 07 25" src="https://user-images.githubusercontent.com/23400003/49882443-92cf3480-fe28-11e8-819c-d68acf6d6a2e.png">

**Comment by justadudewhohacks** [comment]
Are you sure your styles are not simply messed uo, is the parent absolutely positioned?

landmarks.getMouth() is used in the drawing function, that is used to draw the outline of the face (green) so the coordinates should be right.

**Comment by justadudewhohacks** [comment]
Closing, if this is still an issue feel free to update and reopen it.

**Comment by Waishnav** [comment]
> Have a look at this [figure](https://www.pyimagesearch.com/wp-content/uploads/2017/04/facial_landmarks_68markup.jpg). Using `landmarks.getMouth()` you simply get an array of Points 49 to 68.

is this a standard way to map mouth with these numbers as given in the image you shared.
