### ISSUE TITLE
Does JS (and face-api) benefit if you run the model loading in parallel?

### ISSUE THREAD

**Issue by salamanders** [justadudewhohacks/face-api.js#166]
Maybe more of a general understanding of JS, but if I loaded the models using what I *think* is parallel calls:

    await Promise.all([
        faceapi.loadSsdMobilenetv1Model(MODEL_URL),
        faceapi.loadFaceLandmarkModel(MODEL_URL),
        faceapi.loadFaceRecognitionModel(MODEL_URL)
    ]);

does that help any?

1. Yes, it is like loading multiple HTML tags, the browser is smart about doing it in parallel.
2. No, that isn't how JS rolls, and it would take too long to explain.
3. It is going to get cached anyhow, don't worry about it.
4. Other

:)

**Comment by justadudewhohacks** [comment]
It shouldn't hurt to do it that way and could be slightly faster, not sure to be honest. I guess the main limiting factor still is your bandwidth.

After the models have been cached, there should be no difference.

**Comment by salamanders** [comment]
Ok, then nbd (but good to know that they don't have to be loaded in any particular order!)
