### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

### ISSUE THREAD

**Issue by salamanders** [justadudewhohacks/face-api.js#168]
My loop was running happily, but consistently dies on this one image.
Should getContext2dOrThrow also be checking for 0 width canvas?

```Uncaught (in promise) DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at http://localhost:8080/face-api.js:2145:55
    at Array.map (<anonymous>)
    at http://localhost:8080/face-api.js:2141:53
    at step (http://localhost:8080/face-api.js:326:27)
    at Object.next (http://localhost:8080/face-api.js:307:57)
    at http://localhost:8080/face-api.js:300:75
    at new Promise (<anonymous>)
    at __awaiter$1 (http://localhost:8080/face-api.js:296:16)
    at extractFaces (http://localhost:8080/face-api.js:2110:16)
    at ComputeAllFaceDescriptorsTask.<anonymous> (http://localhost:8080/face-api.js:5318:54)```

**Comment by justadudewhohacks** [comment]
Check the rectangles that you are passing to extractFaces, seems they are not correct.

**Comment by salamanders** [comment]
I am passing them directly from 

    let fullFaceDescriptions = await faceapi.detectAllFaces(
                    smallCanvas,
                    new faceapi.SsdMobilenetv1Options({maxResults: 100})
                ).withFaceLandmarks().withFaceDescriptors();

Is it possible that `faceapi.detectAllFaces()` is returning a bad rectangle?

**Comment by justadudewhohacks** [comment]
Hmm that shouldnt be the case. Can you log the rectangle dimensions and your Image dimensions. Also could provide a repo for me to reproduce the issue?

**Comment by salamanders** [comment]
I can't share it publicly, sorry, don't know all the people in the picture.  But if I can get it to repro on a picture that I have full rights to, will do so.

**Comment by justadudewhohacks** [comment]
Closing, if this is still an issue feel free to reopen and share some information about how to reproduce this.

**Comment by zhangalex** [comment]
It's a Cross-domain issue with WebGL textures.
