### ISSUE TITLE
Improve accuracy and stabilization?

### ISSUE THREAD

**Issue by veetechh** [justadudewhohacks/face-api.js#169]
is there any easy way to improve to the accuracy and stabilize landmarks? trying with TINY_FACE_DETECTOR on mobile, sometimes landmarks go out of the face.

**Comment by justadudewhohacks** [comment]
There are no parameters to tune the landmark prediction process, if that was your question.

**Comment by veetechh** [comment]
Okay .. are you planning for any release to address this? thanks

**Comment by justadudewhohacks** [comment]
Can you show some screenshots please of what you mean by "sometimes landmarks go out of the face."?

**Comment by justadudewhohacks** [comment]
Hmm strange, they really look a bit off, are you using the default or the tiny model?

**Comment by veetechh** [comment]
tiny_face_detector_model-shard1 and face_landmark_68_model-shard1

**Comment by veetechh** [comment]
I observed this usually happens when the face is near to camera.

**Comment by justadudewhohacks** [comment]
Closing because the actual question of this issue seems to be answered.
