### ISSUE TITLE
Facial expressions / sentiment recognition

### ISSUE THREAD

**Issue by oreHGA** [justadudewhohacks/face-api.js#17]
Beautiful work with the Face API 🙌😍

I was thinking... would it be possible to extend the API to extract sentiment from the detected faces or it'll be beyond the scope of the project?

**Comment by justadudewhohacks** [comment]
Hi,

I think that is a beautiful idea and certainly a possible extension in the future. Would you build that upon face landmark extraction? Atleast that's what I could imagine, to train a model, which performs sentiment analysis based on the 68 face landmark positions.

Do you have anything in mind? If you know any project that implements sentiment analysis from facial expressions or some data sets, that could be useful for training a model, feel free to share ;)

**Comment by startupgurukul** [comment]
That would be a great approach and can create efficient emotion detection models vs current approaches, 
 

Here are couple of datasets,

https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge

https://www.kaggle.com/c/emotion-detection-from-facial-expressions

**Comment by justadudewhohacks** [comment]
Thanks for sharing the links  :)

**Comment by Bajajar** [comment]
You can take a look at this project https://github.com/bharathvaj1995/gender-detection-tensorflowjs

**Comment by justadudewhohacks** [comment]
@startupgurukul do you by any chance have access to the dataset of your first link? Looks like I can't download it.

**Comment by Bajajar** [comment]
> @startupgurukul do you by any chance have access to the dataset of your first link? Looks like I can't download it.

You can download it from here https://drive.google.com/file/d/1HJladquPEkD0a7i2FJxhyZPv1I1TCj_p/view?usp=sharing
