### ISSUE TITLE
Face Blur (QUESTION)

### ISSUE THREAD

**Issue by jasan-s** [justadudewhohacks/face-api.js#170]
NOT AN ISSUE!

I can see from the example that the bounding box is drawn. is it possible to use the bounding box + contour of face to blur faces?  If so can anyone share a code to do so. OR if not can I use the data from this lib + something like [Sharp.js ](https://github.com/lovell/sharp). ANy wexample code would be greatly appreciated.

**Comment by justadudewhohacks** [comment]
face-api.js gives you the bounding box and face landmark points. From there on you will have to apply other image processing to achieve your goal. Easiest thing I could think of is filtering for skin color and blurring using some other library.

**Comment by TonyBrobston** [comment]
@jasan-s I too am needing to do this. 

I may end up creating a thin wrapper that sits overtop of `face-api.js` and some other repo that easily blurs sections of images. I only found `face-api.js` late last night, so I haven't had a ton of time to investigate. Seems doable.
