### ISSUE TITLE
Custom labels when using FullFaceDescription

### ISSUE THREAD

**Issue by serge1peshcoff** [justadudewhohacks/face-api.js#171]
For now I can either use LabeledFaceDescription (without getting the box info) or FullFaceDescription (without getting a label). I need to display the recognized user (from a detection box) and a label above (the username basically). Is there a way to do it?

**Comment by serge1peshcoff** [comment]
@justadudewhohacks okay, how can I get the label from the faceMatcher.findBestMatch() call? When you create the faceapi.FaceMatcher, it accepts either the Array<LabeledFaceDescription> (which doesn't have a box I can use, only descriptors) or Array<FullFaceDescription> (which has the detection and a box inside, but labels are auto-generated). Or am I missing something?

Thanks in advance for the answer anyway!

**Comment by justadudewhohacks** [comment]
`faceMatcher.findBestMatch()` returns a [FaceMatch](https://github.com/justadudewhohacks/face-api.js/blob/master/src/classes/FaceMatch.ts), which has a label and distance property.

The labels are assigned automatically if you don't label your detection results manually, e.g. by passing an array of [faceapi.LabeledFaceDescriptors](https://github.com/justadudewhohacks/face-api.js/blob/master/src/classes/LabeledFaceDescriptors.ts).
