### ISSUE TITLE
webcam face detection bounding box

### ISSUE THREAD

**Issue by rachitgupta98** [justadudewhohacks/face-api.js#177]
Hi,
You made a awesome API.
i have question how you update the bounding box,
in my case i have this problem

![screenshot 52](https://user-images.githubusercontent.com/43313965/50565487-5327a880-0d55-11e9-90b2-00da009fef51.png)
for this i clear the canvas by 
ctx.clearRect(x,y,w,h)
but it is very slow.
Suggest any...

**Comment by justadudewhohacks** [comment]
`ctx.clearRect(0,0,width,height)` should work to clear your canvas, is it not? The way I am doing it in the examples is by simply resetting the canvas dimensions, see [drawing.js](https://github.com/justadudewhohacks/face-api.js/blob/master/examples/examples-browser/public/js/drawing.js):

```
canvas.width = width
canvas.height = height
```
