### ISSUE TITLE
Registration of backend webgl failed

### ISSUE THREAD

**Issue by zhangtingwz** [justadudewhohacks/face-api.js#178]
Nice to meet you Author,
I use it in my html,it`s my code ：
`<html>

<head>
<title>我的第一个 HTML 页面</title>
</head>

<body>
<img id="myImg" src="~/Content/scripts/jquery/445e2c1c0e833b46ff9e12e89e9ddebb.jpg" />
<script src="~/Content/scripts/jquery/face-api.js"></script>
<script>
   async function init () {
        const detections1 = await faceapi.detectFaceLandmarksTiny(faceImage);
        console.log(detections);
    })
init()
</body>

</html>
`
Nothing can be change , in my Google Chrome `s f12 show me 

![1546418554 1](https://user-images.githubusercontent.com/26179617/50584953-85e4b480-0ead-11e9-98aa-525caab7dfa4.png)

i didn`t know what`s happen.
but i use npm i,npm start ,it`s great.
please help me,thank you very much.
                                                                                                                                    Yours              zt

**Comment by justadudewhohacks** [comment]
Hmm, did you check, whether your device is able to run the WebGL backend? The error message comes from tfjs when initializing your environment once you first load the script.

**Comment by boulabiar** [comment]
I have this issue on a old device with intel graphics but which still can run webgl examples (three.js).

**Comment by pytholabsbot1** [comment]
I am also having this issue while using it on Moto G3 mobile

**Comment by overbyte** [comment]
i have this on linux with nvidia 1070 maxq (mobile) gpu (currently used for webgl)

error:
* firefox 80 (linux)
* brave Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)

working correctly:
* chromium Version 85.0.4183.121 (Official Build) snap (64-bit)
