### ISSUE TITLE
faceapi.extractFaces(input, results) does not accept results withFaceExpressions() or withFaceLandmarks()

### ISSUE THREAD

**Issue by sathyamoorthyrr** [justadudewhohacks/face-api.js#180]
**Case 1:** extractFaces() works fine when detectXFaces() is used alone.
**Case 2:** when detectXFaces() is used along withFaceExpressions() or withFaceLandmarks(), extractFaces() fails

e.g.,
```
const faceDetectionTask = faceapi.detectAllFaces(input, options)
const results =  await faceDetectionTask.withFaceLandmarks()
const faceImages = await faceapi.extractFaces(input, results)
```

This snippet stops with the following error:

>  Uncaught (in promise) TypeError: box.clipAtImageBorders is not a function
>     at extractFaces.ts:48
>     at Array.map (<anonymous>)
>     at Object.<anonymous> (extractFaces.ts:48)
>     at step (tf-core.esm.js:17)
>     at Object.next (tf-core.esm.js:17)
>     at fulfilled (tf-core.esm.js:17)
>     at \<anonymous>

Also,
as per **Case 1** above, results = [FaceDetection]
as per **Case 2** above, results = [{detection:FaceDetection, expressions:FaceExpression}]

_For the extractFaces() to work,_
1. call detectXFaces() second time without withFaceExpressions() or withFaceLandmarks() and use that result
2. someway manipulate the results to the expected format

is that the possible solution or alternate solution?

**Comment by justadudewhohacks** [comment]
`extractFaces` expects an array of FaceDetection or Rect, so instead of `results` simply `results.map(res => res.detection)` to `extractFaces`, as I did in the examples:

``` javascript
export async function extractFaces(input: TNetInput, detections: Array<FaceDetection | Rect>): Promise<HTMLCanvasElement[]>
```
