### ISSUE TITLE
Absolute import path

### ISSUE THREAD

**Issue by angas** [justadudewhohacks/face-api.js#181]
https://github.com/justadudewhohacks/face-api.js/blob/d67c16e5b330d1e78f7fb8281a16aa0e517b5230/src/faceLandmarkNet/FaceLandmark68TinyNet.ts#L1

Replacing `src/` with `../` would be a good idea because this is causing build problems.

**Comment by justadudewhohacks** [comment]
Fixed with v0.17.1.
