### ISSUE TITLE
fetch implementation is missing

### ISSUE THREAD

**Issue by ShadabFaiz** [justadudewhohacks/face-api.js#186]
Like the title says, fetch implemtation is missing.

face-api version: 0.17.1

``` typescript
import * as faceapi from 'face-api.js';
class App {

    private MODEL_URL: string;
    constructor() {
        console.log('starting app...');
        console.log(process.env.MODELS);
        this.MODEL_URL = process.env.MODELS;
    }
    start() {
        try {
            this.loadModels();
            console.log(`Models loadedd successfully....`);
        } catch (error) {
            console.error(error);
        }
    }

    private async loadModels() {
        await faceapi.loadSsdMobilenetv1Model(this.MODEL_URL)
    }

}

```
(node:25181) UnhandledPromiseRejectionWarning: Error: fetch - missing fetch implementation for nodejs environment
    at fetch (/home/Faiz/Organization/Repos/Image_Analysis/using_FaceAPI/node_modules/tfjs-image-recognition-base/src/env/createNodejsEnv.ts:24:11)
    at Object.<anonymous> (/home/Faiz/Organization/Repos/Image_Analysis/using_FaceAPI/node_modules/tfjs-image-recognition-base/src/dom/fetchOrThrow.ts:9:21)
    at step (/home/Faiz/Organization/Repos/Image_Analysis/using_FaceAPI/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/Faiz/Organization/Repos/Image_Analysis/using_FaceAPI/node_modules/tslib/tslib.js:114:57)
    at /home/Faiz/Organization/Repos/Image_Analysis/using_FaceAPI/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/Faiz/Organization/Repos/Image_Analysis/using_FaceAPI/node_modules/tslib/tslib.js:103:16)
    at Object.fetchOrThrow (/home/Faiz/Organization/Repos/Image_Analysis/using_FaceAPI/node_modules/tfjs-image-recognition-base/build/commonjs/dom/fetchOrThrow.js:6:20)
    at Object.<anonymous> (/home/Faiz/Organization/Repos/Image_Analysis/using_FaceAPI/node_modules/tfjs-image-recognition-base/src/dom/fetchJson.ts:4:17)
    at step (/home/Faiz/Organization/Repos/Image_Analysis/using_FaceAPI/node_modules/tslib/tslib.js:133:27)
(node:25181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of anasync function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:25181) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by justadudewhohacks** [comment]
The error message pretty much says it, you either need to use a fetch polyfill for nodejs or you can monkeyPatch it: `faceapi.env.monkeyPatch({ fetch: /*your implementation here*/ })`.

**Comment by ShadabFaiz** [comment]
Shouldn't it be implemented by the face-api itself? If not, then is there any specific reason for it?

**Comment by justadudewhohacks** [comment]
In tfjs-core fetch is being used for fetching and decoding model shards, thus you won't get around this. You can polyfill fetch installing the `node-fetch` package if you really need to load models from remote uris in nodejs or you could simply load the models from local filesystem instead.

**Comment by gadp22** [comment]
I have the same error @justadudewhohacks, I have installed node-fetch-polyfill but still not working. Am I misinterpreting it?

```
import express from 'express';
import path from 'path';
import * as faceapi from 'face-api.js';
import fetch from 'node-fetch-polyfill';

var app = express();
app.use(express.static('public'))

app.get('/', function (req, res) {
   res.sendFile(path.join(__dirname + '/index.html'));
})

var server = app.listen(8081, function () {
   var host = server.address().address
   var port = server.address().port

   console.log("Example app listening at http://%s:%s", host, port);
})

app.get('/test', async function(req, res, next){
    const MODEL_URL = '/models';

    try {
        await faceapi.loadSsdMobilenetv1Model(MODEL_URL);
    } catch (e) {
        console.log(e);
    }

   console.log(dataToSendToClient);
   //var dataToSendToClient = {'labeledFaceDescriptors': 'hello'};
   var JSONdata = JSON.stringify(dataToSendToClient);

   res.send(JSONdata);
})

```

**Comment by cefjoeii** [comment]
### Browser
Loading the models on the browser was working fine.
```javascript
// Load the face detection models
await faceapi.loadSsdMobilenetv1Model('path/to/models');

// Load the face landmark models
await faceapi.loadFaceLandmarkModel('path/to/models');

// Load the face recognition models
await faceapi.loadFaceRecognitionModel('path/to/models');       
```
<br>
However, I faced the same issue on Node.js.
<br>

### Node.js
I found the solution by looking through the example code in the repository.
```javascript
import path from 'path';

// Import a fetch implementation for Node.js
import fetch from 'node-fetch';

// Make face-api.js use that fetch implementation
faceapi.env.monkeyPatch({ fetch: fetch });

async function doSomething() {
  // Load the models
  // Try experimenting on wherever your models are located. Mine are from up one folder
  // You will get 'Error: Only absolute urls are supported' if you don't specify the absolute path
  await faceapi.nets.ssdMobilenetv1.loadFromDisk(path.join(__dirname, '/../models/face-api'));
  await faceapi.nets.faceLandmark68Net.loadFromDisk(path.join(__dirname, '/../models/face-api'));
  await faceapi.nets.faceRecognitionNet.loadFromDisk(path.join(__dirname, '/../models/face-api'));
}


```

**Comment by scsmla** [comment]
i have the same issue @cefjoeii but your solution is not work for me.This give another error 

> face-recognition.ts(15,27): error TS2322: Type 'typeof fetch' is not assignable to type '(url: string, init?: RequestInit) => Promise<Response>'.
  Types of parameters 'init' and 'init' are incompatible.
    Type 'RequestInit' is not assignable to type 'import("/home/duy/find_user_nodejs/node_modules/@types/node-fetch/index").RequestInit'.
      Types of property 'body' are incompatible.
        Type 'BodyInit' is not assignable to type 'import("/home/duy/find_user_nodejs/node_modules/@types/node-fetch/index").BodyInit'.
          Type 'Blob' is not assignable to type 'BodyInit'.
            Type 'Blob' is missing the following properties from type 'ArrayBuffer': byteLength, [Symbol.toStringTag]

**Comment by zavalyshyn** [comment]
You don't need fetch nor monkeypatch. Just use the special API calls to load the model files from local storage (the tutorials don't mention those, but README at npm does), like this:

```
const faceapi = require('face-api.js');
const tf = require('@tensorflow/tfjs-node');
const Canvas = require('canvas');
const Image = require('canvas');
const ImageData = require('canvas');

const MODEL_URL = `${__dirname}/face-models/`;

faceapi.nets.ssdMobilenetv1.loadFromDisk(MODEL_URL)
    .then(faceapi.nets.faceLandmark68Net.loadFromDisk(MODEL_URL))
    .then(faceapi.nets.faceRecognitionNet.loadFromDisk(MODEL_URL))
    .catch(error => {
        error.log(error);
    });

```

**Comment by vvmspace** [comment]
(node:12474) UnhandledPromiseRejectionWarning: Error: only absolute urls are supported
    at /home/vvm/tube/node_modules/node-fetch-polyfill/index.js:47:19

**Comment by RezaRahmati** [comment]
> ```js
> path.joi
> ```

I did the same and now I get `Only absolute URLs are supported`

Update
----------
I found what was my mistake

I was calling `faceapi.nets.faceRecognitionNet.loadFromUrl` instead of `faceapi.nets.faceRecognitionNet.loadFromDisk`
