### ISSUE TITLE
Can't load JSON as custom node package

### ISSUE THREAD

**Issue by GlenHughes** [justadudewhohacks/face-api.js#191]
I'm trying to load the models in a standard application and as an importable node package. Everything in the app is working brilliantly except where I am trying to load the models into face-api. The path being referenced is wrong for the node package version and it's trying to load from the root of the app rather than the root of the node package.

All models are stored in a folder relative to this script `weights/`

Code:
```
/**
     * injects the models json to FaceAPI.js
     * @returns {Promise<void> | *}
     * @todo find make better by not changing path...
     */
    loadModels() {
        const manifest = path.join(__dirname, 'weights');
        return faceapi.loadTinyFaceDetectorModel(manifest)
            .then(() => {
                this.options = new faceapi.TinyFaceDetectorOptions({
                    minFaceSize: this.minFaceSize,
                    minConfidence: this.minConfidence,
                    inputSize: this.inputSize,
                });
            })
            .catch(error => {
                console.error(`Unable to load models for Face API: ${error}`);
            });
    }
```

**Comment by justadudewhohacks** [comment]
I am not sure how your issue is related to this package. Did you try `path.resolve` instead of `path.join`?

**Comment by GlenHughes** [comment]
Yes, tried that. It seems the path is always relative to the site rather than the node module. I've managed to find a workaround by referencing an external URL which isn't great but will do for now. Is it possible to just pass in an object rather than JSON?

**Comment by GlenHughes** [comment]
So how would one pass in the JSON as a relative path then? If my script is in say a folder called `faceapi` and my models are in` faceapi/models` how would I link that? When I run pron it is trying to reference the root i.e. google.com/weights when I want it to reference the relative folder to the script that's calling it

**Comment by justadudewhohacks** [comment]
You would simply do `faceapi.loadTinyFaceDetectorModel('faceapi/model')`.

Is faceapi/models located in your assets (web app) or are you actually trying to load the model from disk in a nodejs process. If you attempt to load from disk you have to use faceapi.nets.tinyFaceDetector.loadFromDisk('faceapi/model'). (also see the README section about loading models)

**Comment by GlenHughes** [comment]
Okay, thank you. Let me give that a go. Appreciate the help at the weekend!
