### ISSUE TITLE
Individual Descriptions

### ISSUE THREAD

**Issue by AkshayAdiga1997** [justadudewhohacks/face-api.js#192]
Is it possible to get individual part's description? such as eyes, nose, mouth?

**Comment by justadudewhohacks** [comment]
Yes, check [this](https://github.com/justadudewhohacks/face-api.js#retrieve-the-face-landmark-points-and-contours) out.

**Comment by AkshayAdiga1997** [comment]
That returns the locations right? But I want to use them to identify a person. Just like we use facedescriptor.

**Comment by AkshayAdiga1997** [comment]
Okay. Thank you
