### ISSUE TITLE
Base64 Image

### ISSUE THREAD

**Issue by buggles333** [justadudewhohacks/face-api.js#196]
Love the library, having fun implementing it into various different things.

Is there a way to pass a base64 encoded image to it instead of a canvas?

**Comment by justadudewhohacks** [comment]
You can simply create an image element and set it's src to the base64 string, then pass this one to the api.

**Comment by pillihx** [comment]
Get error 'The object is in an invalid state. drawImage' using base64 in src img tag.

**Comment by anchitanc** [comment]
i am also using base64 image but not getting right way to use it. fetchImage() method only accept string argument. 
Can someone place point right solution for this?

**Comment by siddmegadeth** [comment]
how it can be done on nodejs 
Due to lack of documentation for nodejs its quite hard to get things working

**Comment by thingswizard** [comment]
Hallo, I've the same problem with base64 images.

I've simply modified the faceReconigtion.ts example in example-node directory in this way:

```
const referenceImage = await canvas.loadImage(REFERENCE_IMAGE)
//const queryImage = await canvas.loadImage(QUERY_IMAGE)

const queryImage = new Image()
queryImage.src = 'data:image/png;base64,' + base64img 

  const resultsRef = await faceapi.detectAllFaces(referenceImage, faceDetectionOptions)
    .withFaceLandmarks()
    .withFaceDescriptors()

```
base64img contains the base64 encoded image.

Running the code I get this error:

(node:6628) UnhandledPromiseRejectionWarning: TypeError: media.addEventListener is not a function
    at C:\Users\ ...... \node_modules\face-api.js\src\dom\awaitMediaLoaded.ts:25:11
    at new Promise (<anonymous>)
    at Object.awaitMediaLoaded (C:\Users\.... \node_modules\face-api.js\src\dom\awaitMediaLoaded.ts:6:10)
    at C:\Users\...... \node_modules\face-api.js\src\dom\toNetInput.ts:53:54
    at Array.map (<anonymous>)
    at Object.<anonymous> (C:\Users\........\node_modules\face-api.js\src\dom\toNetInput.ts:53:16)
    at step (C:\Users\..........\node_modules\tslib\tslib.js:139:27)
    at Object.next (C:\Users\..............\node_modules\tslib\tslib.js:120:57)
    at C:\Users\............\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
(node:6628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by arkumish** [comment]
Try this
for  using base64 image in face api js

1. convert base64 to blob
2. convert blob to acceptable face api image format

```javascript
    const base64Response = await fetch(bas64ImageData);
    const blob = await base64Response.blob();
    const img = await faceapi.bufferToImage(blob);

    const detections = await faceapi.detectSingleFace(img, new faceapi.TinyFaceDetectorOptions());`
```

**Comment by creativewebdev21** [comment]
> Try this for using base64 image in face api js
> 
> 1. convert base64 to blob
> 2. convert blob to acceptable face api image format
> 
> ```js
>     const base64Response = await fetch(bas64ImageData);
>     const blob = await base64Response.blob();
>     const img = await faceapi.bufferToImage(blob);
> 
>     const detections = await faceapi.detectSingleFace(img, new faceapi.TinyFaceDetectorOptions());`
> ```

Does it works in node.js?
