### ISSUE TITLE
Loading Images

### ISSUE THREAD

**Issue by siddhant1** [justadudewhohacks/face-api.js#198]
When Loading images we need to put the images in the public folder so that server can host that public folder, it doesn't work if I provide a relative path to my images that is not present inside the public folder.

**Comment by justadudewhohacks** [comment]
That's because a browser can not simply access your filesystem. You have to make any kind of assets publicly available via a webserver.

**Comment by LuuLinhSon** [comment]
When public url for my react js app is root(www.abcd.com), everything work well. But if I change public url to relative path (www.abcd.com/face), I face error "....load model before inference". 

export const loadModels = async () => {
  const MODEL_URL = `${process.env.PUBLIC_URL}/models`;
  await faceapi.loadTinyFaceDetectorModel(MODEL_URL);
  await faceapi.loadFaceLandmarkTinyModel(MODEL_URL);
  await faceapi.loadFaceRecognitionModel(MODEL_URL);
};

what happen. And how do I fix it? Should I change the model url to a relative path???
