### ISSUE TITLE
Web examples don't work on firefox

### ISSUE THREAD

**Issue by erenaud3** [justadudewhohacks/face-api.js#201]
Hi !

I noticed that web example doesn't work on firefox.
More precisely, the asynchronous functions detectSingleFace and detectAllFaces never end.

I can't explain why and honestly, I don't even know why I tried this package on Firefox since every single complex project I run into doesn't seem to work on that browser.

But maybe you could specify it on README's package ?

Regards

**Comment by justadudewhohacks** [comment]
Are you referring to the same issue as #129? Otherwise should work fine on firefox.

**Comment by erenaud3** [comment]
Yep, that's exactly the same issue ! Sorry, I should have check better. I am closing this one.
