### ISSUE TITLE
Error: LabeledFaceDescriptors - constructor expected descriptors to be an array of Float32Array

### ISSUE THREAD

**Issue by xperiafan13-rom** [justadudewhohacks/face-api.js#202]
Hi, I use your api with nodejs, this is my code:

onst referenceImage = await canvas.loadImage(REFERENCE_IMAGE)
    const queryImage = await canvas.loadImage(QUERY_IMAGE)

    const results = await faceapi
        .detectAllFaces(referenceImage)
        .withFaceLandmarks()
        .withFaceDescriptors()
    const labeledDescriptors = [new faceapi.LabeledFaceDescriptors('obama', Float32Array.from(results[0].descriptor))]
    const faceMatcher = new faceapi.FaceMatcher(labeledDescriptors)

But i get Error: LabeledFaceDescriptors - constructor expected descriptors to be an array of Float32Array

I already try:
    const labeledDescriptors = [new faceapi.LabeledFaceDescriptors('obama', results[0].descriptor)]

and

const labeledDescriptors = [new faceapi.LabeledFaceDescriptors('obama', results[0].descriptor.map(desc => new Float32Array(desc)))]

I execute this like a npm script: node script.js

**Comment by justadudewhohacks** [comment]
It should be as follows:

``` javascript

// using only one reference descriptor for class 'obama'
const descriptorsObama = [
  new Float32Array(results[0].descriptor)
]

const labeledDescriptors = [
  new faceapi.LabeledFaceDescriptors('obama', descriptorsObama )
]
```

**Comment by xperiafan13-rom** [comment]
Thanks!

**Comment by xperiafan13-rom** [comment]
To proccess al descriptors i do :
await forEach(this.files, async (img) => {
            try {
                const desc = await faceapi
                    .detectSingleFace(img)
                    .withFaceLandmarks()
                    .withFaceDescriptor();
                results.push(Array.prototype.slice.call(desc.descriptor));
            } catch (e) {
                console.log(e);
            }
        });


and:

const descriptors = [];
                    obj.biometric.descriptors.forEach(element => {
                        descriptors.push(new Float32Array(element));
                    });
                    const faceMatcher = new faceapi.FaceMatcher([
                        new faceapi.LabeledFaceDescriptors(prefix, descriptors)
                    ]);
                    const singleResult = await faceapi.detectSingleFace(img).withFaceLandmarks().withFaceDescriptor();

where element is image to campare with array of descriptors
