### ISSUE TITLE
Webcam feed on NodeJs environment

### ISSUE THREAD

**Issue by erenaud3** [justadudewhohacks/face-api.js#203]
Hi,

I would like to perform live face detection in a nodejs environment but I don't quiet see how to do that.

Initially, I was capturing frames from my webcam using opencv4nodejs:
```
cap = new cv.VideoCapture(videoDeviceId);
(...)
_frame = cap.read();
```
But then I would have to find a way to convert _frame to a Canvas, right ? At least if I'm using a monkey path like this:
```
const { Canvas, Image, ImageData } = canvas
faceapi.env.monkeyPatch({ Canvas, Image, ImageData })
```

Do I have other options ? Would it be possible to use a monkey patch with some opencv4nodejs' elements ?

I saw this line in README.md:
```
Alternatively you can simply construct your own tensors from image data and pass tensors as inputs to the API.
```
Okay, but how can I achieve that ? If I look at detectAllFaces' signature, I can see the following:
```
detectAllFaces(input: TNetInput, options?: FaceDetectionOptions): DetectAllFacesTask
```
And if I look further, I can see that TNetInput can be a TNetInputArg, which can be a TResolvedNetInput, which can be a tf.Tensor3D or tf.Tensor4D.

So I would have to retrieve data from _frame and use them to instantiate a tf.Tensor3D ?

Thanks !

**Comment by erenaud3** [comment]
Okay, so I managed to get a small working snippet:
```
this.currentFrameTime = Date.now();

// get frame using opencv4nodejs
_frame = Service.videoCapture.getFrame();

try {
    // create tensor
  _tensorFrame = tfjs.tensor3d(_frame.getDataAsArray());
} catch (_error) {
  _err = _error;
  this.log.error("Error instantiating tensor !!!");
  this.log.error(_err.message);
}

faceapi.detectAllFaces(_tensorFrame, this.faceDetectionOptions).then((function(_this) {
  return function(_detectedFaces) {

    var _delayNextFrame, _paintedCurrentFrame;

    // draw face boxes on frame
    _paintedCurrentFrame = Service.videoCapture.drawFaceBoxes(_frame, _detectedFaces);

    // compute latency
    Service.frameDuration = Date.now() - _this.currentFrameTime;

    // display image
    Service.faceRecoUtils.showImage(_paintedCurrentFrame);

   // compute delay needed to have a constant fps
    _delayNextFrame = Math.max(0, 1000 / _this.options.fps - Service.frameDuration);

    return _this.log.debug("Latency: ", Service.frameDuration);
  };
})(this));

// try to have a constant fps
setTimeout((function(_this) {
  return function() {
    return _this.analyseFrame();
  };
})(this), _delayNextFrame);
```

So my problem is, this is really really slow ! Like way slower that your web-example (from 1000ms to 3500ms for one frame). 
In issue #44, you said that "If the code is running on the cpu in node, it would probably be very slow.". As a matter of fact, I am running code on cpu. I tried to run it on GPU but I still couldn't make it (issue with cuDNN, cuda and tensorflow versions). Anyway, that doesn't change anything because the production computers won't have GPUs.

Could you explain the speed gap between node and browser ? Because if I understand correctly, you are running your code on CPU in browser examples, right ? 

Second question: face-api.js isn't designed to run on NodeJS and I better stick to face-recognition.js, right ?

**Comment by erenaud3** [comment]
Sorry, I think I wasn't clear: I got 1000ms in nodejs, not in brower.

But anyway _frame.getDataAsArray() was the real problem here. Your code is way more efficient.

With TinyFaceDetector, the detection takes from 80 to 200 ms. My tensor creation was taking from 1100 to 1500ms  while your's only takes from 10 to 30 ms !! Thanks a lot for your help.

**Comment by mamacker** [comment]
In case someone comes along after me looking for **exactly** the code needed.
As a repo: https://github.com/mamacker/faceme
```
import * as tfjs from '@tensorflow/tfjs-node';
import * as faceapi from 'face-api.js';
import * as fs from 'fs';
import * as cv from 'opencv';

const minConfidence = 0.5;
/*
const faceDetectionNet = faceapi.nets.ssdMobilenetv1;
const faceDetectionOptions = new faceapi.SsdMobilenetv1Options({minConfidence});
*/
const faceDetectionNet = faceapi.nets.tinyFaceDetector;
const faceDetectionOptions = new faceapi.TinyFaceDetectorOptions({minConfidence});

let globalFrame = null;
let lastFrame = null;
function processFrame() {
  if (globalFrame == null) return;
  if (lastFrame == globalFrame) return;

  lastFrame = globalFrame;
  let tFrame = faceapi.tf.tensor3d(globalFrame, [480, 640, 3])
  faceapi.detectAllFaces(tFrame, faceDetectionOptions).then((faces) => {
    console.log(faces);
  });
}
setInterval(processFrame, 100);

async function run() {
  await faceDetectionNet.loadFromDisk('./weights');
  let video = '/dev/video0';
  let cap = new cv.VideoCapture(video);
  let capture = () => {
    cap.read(function(err, frame) {
      if (frame.width() > 0) {
        let data = new Uint8Array(frame.getData().buffer);
        globalFrame = data;
      }

      setTimeout(capture, 0);
    });
  }
  capture();
}

run()
```

**Comment by whyboris** [comment]
Thank you @mamacker for the code 🙇‍♂️ Thanks to you I was able to remove `canvas` from my project 🙇‍♂️

Full code: https://github.com/whyboris/extract-faces-node

I'm using [sharp](https://github.com/lovell/sharp) for image loading (as I need other image manipulations later)

Relevant piece:
```ts
const sharp = require('sharp');
const imgBuffer: Buffer = await sharp('./some/img/path.jpg').toBuffer();
const imgTensor = tf.node.decodeJpeg(imgBuffer);
const detections = await faceapi.detectAllFaces(imgTensor);
```

**Comment by punisher97** [comment]
> Thank you @mamacker for the code 🙇‍♂️ Thanks to you I was able to remove `canvas` from my project 🙇‍♂️
> 
> Full code: https://github.com/whyboris/extract-faces-node
> 
> I'm using [sharp](https://github.com/lovell/sharp) for image loading (as I need other image manipulations later)
> 
> Relevant piece:
> 
> ```ts
> const sharp = require('sharp');
> const imgBuffer: Buffer = await sharp('./some/img/path.jpg').toBuffer();
> const imgTensor = tf.node.decodeJpeg(imgBuffer);
> const detections = await faceapi.detectAllFaces(imgTensor);
> ```

This the correct mode, using decodeJpeg and most faster
