### ISSUE TITLE
Safari iOS Exceeded WebGL Texture Size 

### ISSUE THREAD

**Issue by prasadkawthekar** [justadudewhohacks/face-api.js#204]
Thanks for open-sourcing this library. It works perfectly for me on desktop Safari and Chrome. But it doesn't work for me on either browsers for iPhone. On Safari, I get the following error when I try loading the face detector and landmark detectors:

`Unhandled Promise Rejection: Error: Requested texture size [6321x16] greater than WebGL maximum on this browser / GPU [4096x4096] in 161.50cc6bac.chunk.js:13429`

Would you know how to handle this issue? Thanks.

**Comment by justadudewhohacks** [comment]
Unfortunately I don't have access to mobile safari. Which example are you referring to and which function call is throwing this error, can you post a stacktrace?

**Comment by larui529** [comment]
Actually, I can run the demo api on Ipad Safari, but it's very sluggish. I am wondering why is that so. I am wondering if a surface pro could do better since I want to use it on a tablet.

**Comment by sriesow** [comment]
We were facing this problem also in our project. We were able to resolve this by manually loading the face-api.js rather than loading from npm.
