### ISSUE TITLE
Face-api js Error in faceFeatureExtractor while building in angular

### ISSUE THREAD

**Issue by examityharikrishna** [justadudewhohacks/face-api.js#206]
Added face-api.js via npm module in my angular application.

Added  **import * as faceapi from 'face-api.js'** line to component and did ng build. Below is the error which I am getting

`ERROR in node_modules/face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.d.ts(11,24): error TS1110: Type expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.d.ts(11,31): error TS1003: Identifier expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.d.ts(11,83): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.d.ts(11,84): error TS1131: Property or signature expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.d.ts(11,96): error TS1005: '=' expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.d.ts(13,5): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.d.ts(13,36): error TS1005: ',' expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.d.ts(13,51): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/FaceFeatureExtractor.d.ts(17,1): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.d.ts(11,24): error TS1110: Type expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.d.ts(11,31): error TS1003: Identifier expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.d.ts(11,83): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.d.ts(11,84): error TS1131: Property or signature expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.d.ts(11,96): error TS1005: '=' expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.d.ts(13,5): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.d.ts(13,36): error TS1005: ',' expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.d.ts(13,51): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/faceFeatureExtractor/TinyFaceFeatureExtractor.d.ts(17,1): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(17,24): error TS1110: Type expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(17,31): error TS1003: Identifier expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(17,83): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(17,84): error TS1131: Property or signature expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(17,96): error TS1005: '=' expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(19,5): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(19,51): error TS1005: ',' expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(19,71): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(23,5): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(23,36): error TS1005: ',' expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(23,51): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/faceProcessor/FaceProcessor.d.ts(27,1): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.d.ts(12,24): error TS1110: Type expected.
node_modules/face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.d.ts(12,31): error TS1003: Identifier expected.
node_modules/face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.d.ts(12,83): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.d.ts(12,84): error TS1131: Property or signature expected.
node_modules/face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.d.ts(12,96): error TS1005: '=' expected.
node_modules/face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.d.ts(14,5): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.d.ts(14,36): error TS1005: ',' expected.
node_modules/face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.d.ts(14,51): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/faceRecognitionNet/FaceRecognitionNet.d.ts(18,1): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/mtcnn/Mtcnn.d.ts(19,24): error TS1110: Type expected.
node_modules/face-api.js/build/commonjs/mtcnn/Mtcnn.d.ts(19,31): error TS1003: Identifier expected.
node_modules/face-api.js/build/commonjs/mtcnn/Mtcnn.d.ts(19,83): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/mtcnn/Mtcnn.d.ts(19,84): error TS1131: Property or signature expected.
node_modules/face-api.js/build/commonjs/mtcnn/Mtcnn.d.ts(19,96): error TS1005: '=' expected.
node_modules/face-api.js/build/commonjs/mtcnn/Mtcnn.d.ts(21,5): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/mtcnn/Mtcnn.d.ts(21,36): error TS1005: ',' expected.
node_modules/face-api.js/build/commonjs/mtcnn/Mtcnn.d.ts(21,51): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/mtcnn/Mtcnn.d.ts(25,1): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.d.ts(20,24): error TS1110: Type expected.
node_modules/face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.d.ts(20,31): error TS1003: Identifier expected.
node_modules/face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.d.ts(20,83): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.d.ts(20,84): error TS1131: Property or signature expected.
node_modules/face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.d.ts(20,96): error TS1005: '=' expected.
node_modules/face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.d.ts(22,5): error TS1128: Declaration or statement expected.
node_modules/face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.d.ts(22,36): error TS1005: ',' expected.
node_modules/face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.d.ts(22,51): error TS1005: ';' expected.
node_modules/face-api.js/build/commonjs/ssdMobilenetv1/SsdMobilenetv1.d.ts(26,1): error TS1128: Declaration or statement expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(26,24): error TS1110: Type expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(26,31): error TS1003: Identifier expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(26,43): error TS1005: ';' expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(26,44): error TS1131: Property or signature expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(26,56): error TS1005: '=' expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(28,5): error TS1128: Declaration or statement expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(28,36): error TS1005: ',' expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(28,51): error TS1005: ';' expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(32,5): error TS1128: Declaration or statement expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(32,40): error TS1005: ',' expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(32,74): error TS1005: ',' expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(32,103): error TS1109: Expression expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(32,112): error TS1005: ';' expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(41,5): error TS1128: Declaration or statement expected.
node_modules/tfjs-image-recognition-base/build/commonjs/tinyYolov2/TinyYolov2.d.ts(42,1): error TS1128: Declaration or statement expected.
`

**Below are my Package.Json dependencies** 

"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.5",
    "@types/chrome": "0.0.77",
    "angular-styled-components": "0.0.17",
    "angular2-datetimepicker": "^1.1.1",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^3.3.7",
    "browser-detect": "^0.2.28",
    "bulma": "^0.7.2",
    "core-js": "^2.4.1",
    "face-api.js": "^0.18.0",
    "json-server": "^0.14.0",
    "logrocket": "^0.6.17",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.23",
    "ng-pick-datetime": "^5.2.6",
    "ng-pick-datetime-moment": "^1.0.5",
    "ngx-moment": "^3.3.0",
    "ngx-spinner": "^2.0.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  }

**Comment by examityharikrishna** [comment]
Thanks for quick reply. The issue is fixed when I update ts-lint, typescript, ts-node packages.

**Comment by Mathyn** [comment]
Could you share which versions you used? I am also running into the exact same problem.

Typescript: 3.4.3
Angular: 5.2.11
Ionic: 4.18.0
Node: 8.11.2

My tsconfig.json looks like this:
````
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "src/**/*.spec.ts",
    "src/**/__tests__/*.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by Mathyn** [comment]
I fixed this. Upgrading the globally installed version of Typescript was not enough because Ionic defaults back to a locally installed one. Updating this one (e.g. `npm install typescript@3.4.3 --save-dev` solved the issue for me.
