### ISSUE TITLE
Slow at the first Check

### ISSUE THREAD

**Issue by AkshayAdiga1997** [justadudewhohacks/face-api.js#209]
fullFaceDescriptions = await faceapi
                                                    .detectSingleFace(videoEl, new faceapi.SsdMobilenetv1Options({ inputSize:256 }))
                                                    .withFaceLandmarks()
                                                    .withFaceDescriptor()
desc=fullFaceDescriptions.descriptor

1st time when the above code is executed, it takes around 3-4 seconds. Successive execution takes around half a second. Why is that so?

**Comment by rachitgupta98** [comment]
yeah because it loads the models first & then it works fine.

**Comment by AkshayAdiga1997** [comment]
> yeah because it loads the models first & then it works fine.
I have include these lines before that code
await faceapi.loadSsdMobilenetv1Model('/src/store/models/')
await faceapi.loadFaceLandmarkTinyModel('/src/store/models/')
await faceapi.loadFaceLandmarkModel('/src/store/models/')
await faceapi.loadFaceRecognitionModel('/src/store/models/')
