### ISSUE TITLE
Use more than one file to train face recognition

### ISSUE THREAD

**Issue by gsommavilla** [justadudewhohacks/face-api.js#216]
I am working to create a node js server to perform face
recognition, using face-api.js.

I have two questions regarding the architecture of such system.

#### 1. Use more than one file to train

Firstly, I would like to train the face recognition server with
reference faces stored on several input files (let's call them train
images). There is a single face on each train image.  F.ex.:

    train_images/Hannah.jpg
    train_images/John.jpg
    train_images/Tom.jpg
    train_images/Jessie.jpg
    ..

Is there already a way in face-api.js to load a batch of train images
and store the resulting features in a single object?

#### 2. Use more than one train image for each person

Secondly, I think that the system would be more robust if several
images of the same persons are used to train the face features. F.ex.:

    train_images/Hannah_0001.jpg
    train_images/Hannah_0002.jpg
    train_images/Hannah_0003.jpg
    train_images/Tom_0001.jpg
    train_images/Tom_0002.jpg
    ..

So I'd like to use more than one picture for each person for
training. Maybe this can be achieved by merging data from more than
one picture of the same person. Is this possible with face-api.js?

**Comment by justadudewhohacks** [comment]
Yes you can use multiple descriptors per label for face recognition by using the average distance of all descriptors for example. What you are probably looking for is the faceapi.FaceMatcher helper class.

**Comment by gsommavilla** [comment]
I finally tried this out and definitely FaceMatcher was what I needed.
The following example (taken from README, I somewhat missed it) describes exactly how to solve my problem:

    const labeledDescriptors = [
      new faceapi.LabeledFaceDescriptors(
        'obama',
        [descriptorObama1, descriptorObama2]
      ),
      new faceapi.LabeledFaceDescriptors(
        'trump',
        [descriptorTrump]
      )
    ]
    const faceMatcher = new faceapi.FaceMatcher(labeledDescriptors)
	
Thank you.
