### ISSUE TITLE
Installation of @tensorflowtfjs-node is not possible

### ISSUE THREAD

**Issue by Hohuade** [justadudewhohacks/face-api.js#217]
This is when I installed it.
I can't solve it.
What shouldI do?

E:\jslife_WX\wxjslife_rebuild_face>npm install

> @tensorflow/tfjs-node@0.2.3 install E:\jslife_WX\wxjslife_rebuild_face\node_modules\@tensorflow\tfjs-node
> node scripts/install.js

* Downloading libtensorflow
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 172.217.160.80:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
npm WARN less-loader@4.1.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @tensorflow/tfjs-data@0.1.7 requires a peer of @tensorflow/tfjs-core@0.14.5 but none is installed. You must install peer dependencies yourself.
npm WARN @tensorflow/tfjs-layers@0.9.2 requires a peer of @tensorflow/tfjs-core@0.14.5 but none is installed.
You must install peer dependencies yourself.
npm WARN @tensorflow/tfjs-converter@0.7.2 requires a peer of @tensorflow/tfjs-core@0.14.5 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@0.2.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@0.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by TheKiteRunners** [comment]
network error, Try using vpn

**Comment by justadudewhohacks** [comment]
Closing because it's not related to face-api.js.
