### ISSUE TITLE
Browser support / compatibility

### ISSUE THREAD

**Issue by garygreen** [justadudewhohacks/face-api.js#22]
Would it be possible to list the browsers which support this package? For example can this work server-side on node or is it primarily client side focused?

**Comment by justadudewhohacks** [comment]
Sure. Actually it should run anywhere, where tensorflow.js runs. It's primarily focused for clientside applications. Haven't tried to run this in node. Although it should be possible, I think tfjs-core stuff cannot be run on the native gpu and running this on the CPU would be pretty damn slow.
