### ISSUE TITLE
Face rotation

### ISSUE THREAD

**Issue by hugohil** [justadudewhohacks/face-api.js#220]
Hey, first of all, thanks a lot for this awesome library. Really easy to use yet very efficient and versatile. 👍 

I was wondering how could I get the face rotation ?
i.e some y-axis and x-axis rotation value that could indicate how much the user is facing the camera, and if not, how much is he/she facing in which direction.

thanks!

**Comment by justadudewhohacks** [comment]
This is a potential enhancement, which is not implemented yet. Tracking [issue](https://github.com/justadudewhohacks/face-api.js/issues/107) is here.
