### ISSUE TITLE
Build without tfjs

### ISSUE THREAD

**Issue by ldenoue** [justadudewhohacks/face-api.js#224]
I use faceapi on a web page that already imports tfjs using their CDN.
Is there a build of faceapi that doesn’t include tfjs so that it’ll be smaller and no warning about tfjs having been included twice?

**Comment by justadudewhohacks** [comment]
You mean a bundled face-api.js script? No there is no such build. There would also probably be conflicts regarding the tfjs-core version, if there is a mismatch.

**Comment by ldenoue** [comment]
Right, something like Google does when you use their CDN bundles.
For example, when I want to use body-pix, I simply have to do:
```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>
<script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/body-pix"></script>
```

It'd be nice to be able to add face-api.js below in order to use body-pix and face-api on the same webapp.

Laurent

**Comment by justadudewhohacks** [comment]
Why are you pulling all the scripts from CDNs and don't bundle tfjs, body-pix and face-api.js together?

**Comment by ldenoue** [comment]
Because it’s easy to try things in pure JavaScript without having to setup a dev environment that needs TypeScript.
But I should try.
