### ISSUE TITLE
Trying to get this to work in Angular

### ISSUE THREAD

**Issue by coreboarder** [justadudewhohacks/face-api.js#228]
I have been trying to get this to work in an Angular component, without success, and would love a bit of help/direction. Await dies on the vine and I'm stumped as to what to do next beyond throwing more darts at the wall. Is there a debug flag somewhere?

**[package.json]**
"face-api.js": "^0.18.0",

**[component.html]**
< div style="position: relative" class="margin">
  < video id="videoEl" autoplay muted>< /video>
  < canvas id="overlay">< /canvas>
< /div>

**[component.ts]**
import { Component, OnInit } from '@angular/core';

import * as $ from 'jquery';

// implements nodejs wrappers for HTMLCanvasElement, HTMLImageElement, ImageData
import * as canvas from 'canvas';
import * as faceapi from 'face-api.js';
import { CPU_ENVS } from '@tensorflow/tfjs-core/dist/test_util';

// patch nodejs environment, we need to provide an implementation of
// HTMLCanvasElement and HTMLImageElement, additionally an implementation
// of ImageData is required, in case you want to use the MTCNN
const { Canvas, Image, ImageData } = canvas;
faceapi.env.monkeyPatch({ Canvas, Image, ImageData });

const TINY_FACE_DETECTOR = 'tiny_face_detector';

@Component({
  selector: 'app-facetrack',
  templateUrl: './facetrack.component.html',
  styleUrls: ['./facetrack.component.css']
})
export class FacetrackComponent implements OnInit {

  // tiny_face_detector options
  inputSize = 512;
  scoreThreshold = 0.5;
  withFaceLandmarks = false;
  withBoxes = true;
  videoEl;
  stream;

  constructor(
  ) {
  }

  ngOnInit() {
    this.loadModels();
  }

  // ======================================================================
  // BEGIN: startTracking
  // ======================================================================
  async startTracking() {
    let cnvs;
    const vEl = <HTMLCanvasElement>document.getElementById('videoEl');
    const vElwidth = vEl.width;
    const vElheight = vEl.height;
    console.log('start tracking...');
    const options = new faceapi.TinyFaceDetectorOptions({ inputSize: 320, scoreThreshold: 0.5 });

    const ts = Date.now();

    setTimeout(function () {

      console.log('this.videoEl = ' + vEl);
      // const detections = faceapi.detectSingleFace(vEl).withFaceLandmarks();
      const detections = faceapi.detectSingleFace(vEl, options);
      console.log('detections');
      console.log(detections);

      // resize the detected boxes in case your displayed image has a different size then the original
      const detectionsForSize = faceapi.resizeResults(detections, { width: vElwidth, height: vElheight });
      console.log('detectionsForSize');
      console.log(detectionsForSize);
      // draw them into a canvas
      cnvs = document.getElementById('overlay');
      // this.canvas.getContext('2d');
      canvas.width = vEl.width;
      canvas.height = vEl.height;
      faceapi.drawDetection(cnvs, detectionsForSize, { withScore: true });

    }, 5000);

  }
  // ======================================================================
  // END: startTracking
  // ======================================================================

  // ======================================================================
  // BEGIN: cameraConnect
  // ======================================================================
  async cameraConnect() {
    // try to access users webcam and stream the images
    // to the video element
    this.stream = await navigator.mediaDevices.getUserMedia({ video: {} });
    this.videoEl = $('#videoEl').get(0);
    this.videoEl.srcObject = this.stream;

    if (this.videoEl.srcObject.active === true) {
      this.startTracking();
    } else {
      console.log('Camera not connected...');
    }

  }
  // ======================================================================
  // END: cameraConnect
  // ======================================================================

  // ======================================================================
  // BEGIN: loadModels
  // ======================================================================
  async loadModels() {
    // load the models
    await faceapi.loadTinyFaceDetectorModel('./assets/weights/');
    await faceapi.loadFaceRecognitionModel('./assets/weights/');
    this.cameraConnect();
  }
  // ======================================================================
  // END: loadModels
  // ======================================================================

}

**Comment by coreboarder** [comment]
The output for "console.log(detections);" is: 
DetectSingleFaceTask {input: video#videoEl, options: TinyFaceDetectorOptions}
input: video#videoEl
options: TinyFaceDetectorOptions {_name: "TinyFaceDetectorOptions", _inputSize: 320, _scoreThreshold: 0.5}
__proto__: DetectFacesTaskBase

**Comment by coreboarder** [comment]
The output for "console.log(detectionsForSize);" is:
DetectSingleFaceTask {input: video#videoEl, options: TinyFaceDetectorOptions}
input: video#videoEl
options: TinyFaceDetectorOptions {_name: "TinyFaceDetectorOptions", _inputSize: 320, _scoreThreshold: 0.5}
__proto__: DetectFacesTaskBase

**Comment by justadudewhohacks** [comment]
You forgot the await keyword: `const detections = await faceapi.detectSingleFace(vEl, options)`, detectSingleFace returns a Promise. Therefore your function also has to be async.

**Comment by coreboarder** [comment]
When I use "await faceapi.detectSingleFace(vEl, options)" nothing happens. Is there a debug flag or a way to get some console output?

**Comment by Getsuren** [comment]
I had the same problem but instead of giving to detectSingleFace the video to eat I gave it a canvas I in wich I draw the video's frames. Seems to be working. I would yet be interested to know why feeding the video to the function doesn't work in this context.

**Comment by styick** [comment]
@Getsuren l have the same problem, but l open a new tab: Live Demos page, my app  seems to be working.

**Comment by achirsh** [comment]
hello，I want to load the local model, but 404 (Not Found) is prompted. Do you have this problem in the process of using？

**Comment by justadudewhohacks** [comment]
I think you are facing the same issue as #129. I added a comment how to fix this. I still have to fix the example code.

**Comment by justadudewhohacks** [comment]
Closing here. If the issue still persists after following the advice in my comment above, feel free to reopen.
