### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by rohanmuplara** [justadudewhohacks/face-api.js#229]
I am trying to test out my new face detector which doesn't use yolo but automatically regresses the bounding boxes for single face detector. We have been using a youtube dataset but the aspect ratio doesn't match the youtube dataset so when resize our images, the face gets distorted. I was wondering if you could point to some good datasets to use which have resolutions that match the webcam.

**Comment by justadudewhohacks** [comment]
Your face detector should be independent from the aspect ratio. I would preprocess your images such that they are squared before training your network. You can scale down your images and pad the minor dimension with zeros. Optionally you can also center the image.
