### ISSUE TITLE
implementation on Raspberry pi

### ISSUE THREAD

**Issue by rachitgupta98** [justadudewhohacks/face-api.js#230]
can we use Faceapi.js on raspberry pi 3

**Comment by justadudewhohacks** [comment]
If tfjs / tfjs-node is running on raspberry pi than face-api.js is too.  You would have to try it out, I can't say for sure.

**Comment by faridhajnal** [comment]
Hi! Did you manage to do it? Or any more info on this? Having a super hard time making my program work on Chromium for my RPI :(

**Comment by TechnoDezi** [comment]
Hi

I know this is an old issue, but I want to share my findings. I have recently after a long battle managed to get face-api running on a Raspberry PI, it comes down to getting tfjs-node running. You can have a look at my blog post: **[https://technodezi.co.za/Post/running-face-apijs-or-tfjs-node-on-a-raspberry-pi-and-nodejs](https://technodezi.co.za/Post/running-face-apijs-or-tfjs-node-on-a-raspberry-pi-and-nodejs)**

I opted to rather run it from a node application as directly inside chromium was way too slow. Tensorflow on raspberry pi is still slow, but better.

If you still struggle I will be more than willing to assist.

**Comment by alexjose70** [comment]
> Hi
> 
> I know this is an old issue, but I want to share my findings. I have recently after a long battle managed to get face-api running on a Raspberry PI, it comes down to getting tfjs-node running. You can have a look at my blog post: **https://technodezi.co.za/Post/running-face-apijs-or-tfjs-node-on-a-raspberry-pi-and-nodejs**
> 
> I opted to rather run it from a node application as directly inside chromium was way too slow. Tensorflow on raspberry pi is still slow, but better.
> 
> If you still struggle I will be more than willing to assist.

Hello @TechnoDezi, I think your post is down, do you have it somewhere else? I am trying to run face-api with chromium on ubuntu for rpi4 but its not working because of WebGL
