### ISSUE TITLE
Is there anyway to extract all faces from Webcam?

### ISSUE THREAD

**Issue by suijunqiang** [justadudewhohacks/face-api.js#238]
I am trying to extract all faces from webcam, but there is no API to do so, although "face extraction" API able to extract faces from a picture but not on a video?

I'm not sure that is a good idea if extracting faces from Webcam each frame by "face extraction" API.

So, any comments

Thanks & Best Regards
Sui

**Comment by erenaud3** [comment]
Hi,

> I'm not sure that is a good idea if extracting faces from Webcam each frame by "face extraction" API.

This is exactly the approach I would choose. Of course, you are not going to analyze every frame. One per second could be way enough depending on what you are planning to do.

You could take a look at the code on [this issue](https://github.com/justadudewhohacks/face-api.js/issues/203).
Then again, it really depends on what you want to do. Above code was designed for a back-end only environment. If you want to perform face extraction on a browser, you can just take a look at the corresponding example in this repo.

Regards

**Comment by suijunqiang** [comment]
Hi, @erenaud3 
It's really helpful, I will try your advise.
BYW,  the demo fps of Webcam face detection on my laptop able to in the range of 20-40, so I believe it can be get a well performance on the web browser.
Again, thanks for your help and keep in touch.

Thanks & Best Regards

**Comment by suijunqiang** [comment]
@erenaud3 
Hello again, I have met some issue for the project of face-api.js.
So would you please add my whatsapp/wechat/qq to your friend list for easing commutations.
I am looking forward to get your feedback.

Thanks & Best Regards
Sui
