### ISSUE TITLE
the  "BBT Face Matching" functions accuracy is very low & slow in "example-browser" when using my own photos.

### ISSUE THREAD

**Issue by suijunqiang** [justadudewhohacks/face-api.js#241]
I have no idea why the accuracy is very low(10%), what I did as below.
I have created 2 new folders under example/images and edited 5 png photos for each folder(one is mine), also change "classes" in the file of example-browser/public/js/bbt.js to be "const classes = ['asuix','asui']", when I refresh the running code, the accuracy is very low.

Would you please give some advises?

Thanks & Best Regards
Sui

**Comment by justadudewhohacks** [comment]
You probably forgot to perform face alignment. If you are referring to the bbt face matching example: this example expects the face images to be aligned already.

**Comment by suijunqiang** [comment]
@justadudewhohacks

Thanks for your response.
It's my fault, now the matching accuracy has been risen to be 95% and more.
Thanks again.

Sui
