### ISSUE TITLE
How to train and have my own model

### ISSUE THREAD

**Issue by vcasadei** [justadudewhohacks/face-api.js#243]
Hi, your lib seen really good, however I feel the need for a tutorial on how to use it for custom face recognition.

I still cannot figure it out how to train a model with my own images

**Comment by justadudewhohacks** [comment]
You don't train a new model. Check out the introduction [article](https://itnext.io/face-api-js-javascript-api-for-face-recognition-in-the-browser-with-tensorflow-js-bcc2a6c4cf07).

**Comment by alex77t** [comment]
Hi, can you please advise how did you convert dlib face landmarks model into tensorflow format?

**Comment by justadudewhohacks** [comment]
@alex77t I did not do so. I trained a face landmark detector from scratch, as stated in the README.

**Comment by linhbkhn95** [comment]
how to train model to detection my face?
