### ISSUE TITLE
weights missing for FaceLandmark68Net

### ISSUE THREAD

**Issue by mvolkmann** [justadudewhohacks/face-api.js#244]
Should there be a manifest.json file and a weight file for FaceLandmark68Net in the weights directory?
When I try to use Mtcnn, it seems to want that model to have been loaded.

**Comment by TheKiteRunners** [comment]
> To load a model, you have provide the corresponding manifest.json file as well as the model weight files (shards) as assets.

**Comment by justadudewhohacks** [comment]
If you only use the mtcnn then you don't need that model.

**Comment by mvolkmann** [comment]
I am only using the mtcnn model. I have this in my code and I verified that it is getting executed:

```js
faceApi.loadMtcnnModel('/weights');
```

My weights directory contains the files mtcnn_model-shard1, mtcnn_model-weights_manifest.json, and many other shard and manifest files. But I get this error:

```
FaceProcessor.js:35 Uncaught (in promise) Error: FaceLandmark68Net - load model before inference
    at FaceLandmark68Net.FaceProcessor.runNet (FaceProcessor.js:35)
```

It's as if the mtcnn model depends on another model. Is that possible?

**Comment by justadudewhohacks** [comment]
Nope that's not possible. You are apparently calling the landmark prediction API, as the error suggests. What does the rest of your code look like?

**Comment by mvolkmann** [comment]
I see what is causing the error now.

```js
    const faces = await faceApi.detectAllFaces(video, options)
      .withFaceLandmarks()
      .withFaceDescriptors();
```

If I remove the calls to `withFaceLandmarks` and `withFaceDescriptors`, the error goes away.
Where can I get the model files that are required to use those methods? I have files that begin with `face_landmark_68_model-` and `face_landmark_68_tiny_model_`, but it seems those are not the ones I need.

**Comment by justadudewhohacks** [comment]
face_landmark_68_model for face landmark prediction and face_recognition_model for computing face descriptors. The reason why you still get the error is, because you are not loading them:
``` javascript
await faceapi.loadFaceLandmarkModel('/models')
await faceapi.loadFaceRecognitionModel('/models')
```

**Comment by mvolkmann** [comment]
Thanks!
