### ISSUE TITLE
Is it possible to get the detected faces and display them?

### ISSUE THREAD

**Issue by mbsyaswanth** [justadudewhohacks/face-api.js#245]
I want to get the detected faces from image/video input and display them seperately below the video/image or somewhere else? Please tell me how to do that?

**Comment by justadudewhohacks** [comment]
[Here](https://github.com/justadudewhohacks/face-api.js/blob/master/examples/examples-browser/views/faceExtraction.html) is the corresponding example to achieve face extraction.
