### ISSUE TITLE
node + express = hang

### ISSUE THREAD

**Issue by PratiquesAlgorithmiques** [justadudewhohacks/face-api.js#247]
hello i'm trying to make a simple node + express application that given an image url it detects whether there are faces in the image and then shows a simple list of the image urls that have faces (not the images just the urls) in a web page. everything works but when it is calculating i have no access to the very simple and light web page. is there a workaround for this? thanks !

**Comment by justadudewhohacks** [comment]
> everything works but when it is calculating i have no access to the very simple and light web page. is there a workaround for this? thanks !

Could you reframe that question? I don't understand what you are trying to say.

**Comment by PratiquesAlgorithmiques** [comment]
i would like to be able to see the urls on my web page that is served by the same node program that is also using face-api to detect faces in images. while node is using the face detection algorithms the site hangs and becomes unavailable.

**Comment by justadudewhohacks** [comment]
The fact that your website does not respond anymore does not have anything to do with faceapi, if you are running it on a nodejs server.
