### ISSUE TITLE
Error uploading an image

### ISSUE THREAD

**Issue by fortil** [justadudewhohacks/face-api.js#249]
When I try to upload a custom image with 4.8 MB the demo [face recognition](https://justadudewhohacks.github.io/face-api.js/face_recognition/) crash

http://g.recordit.co/QFQt9qeqzF.gif

**Comment by justadudewhohacks** [comment]
The reason it's throwing that error is, because it doesn't detect any faces in the image you are uploading. Probably the demo should display a proper error in this case.

**Comment by justadudewhohacks** [comment]
Should be fixed by now.
