### ISSUE TITLE
FaceRecognizer.constructor - expected atleast one input

### ISSUE THREAD

**Issue by reviloera** [justadudewhohacks/face-api.js#250]
Thank you for this amazing library. When I run this code on coloured photos it works on, however when I input back and white am getting the error above. am doing this with African faces ... 

If you have a workaround I will appreciate

Thank you

**Comment by justadudewhohacks** [comment]
Please provide some code, the error message is thrown, because you are passing an empty array to the FaceMatcher constructor.

**Comment by reviloera** [comment]
If I supply black and white image to the model its throwing that error .... when all my images are colored it works perfectly

**Comment by justadudewhohacks** [comment]
As described in the abovementioned issue, you have to handle the case when no face is detected.
