### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by lemidiriba** [justadudewhohacks/face-api.js#251]
i need help with how to run the code localy in my computer like if it is possible step by step

**Comment by john-yick** [comment]
Think you are looking for this: [https://github.com/justadudewhohacks/face-api.js/tree/master/examples](https://github.com/justadudewhohacks/face-api.js/tree/master/examples)
There should be enough information in there to get it all up and running. It is all in typescript so you need to make sure that you have that installed first.

**Comment by chtsngn** [comment]
@lemidiriba you can follow the steps [here](https://github.com/justadudewhohacks/face-api.js/blob/master/README.md).

**Comment by lemidiriba** [comment]
tanks for you support.
