### ISSUE TITLE
Does detectSingleFace returns a Promise or a Class???

### ISSUE THREAD

**Issue by Omi0** [justadudewhohacks/face-api.js#253]
Here it returns a promise:

`const detection = await faceapi.detectSingleFace(input)
`

But in typing it returns DetectSingleFaceTask class, and only its run() method returns a Promise.
https://github.com/justadudewhohacks/face-api.js/blob/c66dbbde9bcfa4fe67e65d818c698597ed2825a0/build/es6/globalApi/detectFaces.d.ts#L4

**Comment by justadudewhohacks** [comment]
It's not directly a Promise, but it's a custom [class](https://github.com/justadudewhohacks/face-api.js/blob/c66dbbde9bcfa4fe67e65d818c698597ed2825a0/src/globalApi/ComposableTask.ts), which is awaitable.

**Comment by Omi0** [comment]
Clear. Cheers.
