### ISSUE TITLE
Update to work with latest @tensorflow/tfjs-node

### ISSUE THREAD

**Issue by john-yick** [justadudewhohacks/face-api.js#254]
When testing using the latest @tensorflow/tfjs-node it does not load correctly and you end up with this error:
`============================
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node, or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
============================`

Processing images then takes a good 10 seconds

I think face-api.js is only compatible with older versions of @tensorflow/tfjs-node as it references ^0.2.3. After downgrading to this version my image processing time drops down to 0.4 seconds per image. 

Let me know if there is a way to run the latest @tensorflow/tfjs-node with face-api.js

Thanks

**Comment by justadudewhohacks** [comment]
> I think face-api.js is only compatible with older versions of @tensorflow/tfjs-node as it references ^0.2.3. 

That's correct, face-api.js currently uses tfjs-core version 0.14.2, thus you need to install a compatible tfjs-node version.

PR for upgrading to latest tfjs-core version is already up #246. Will upgrade as soon as possible.

**Comment by john-yick** [comment]
Thanks for the prompt reply, just wanted to raise as when trying to run the code initially in NodeJS I hit this issue and it was unclear how to resolve it.

Look forward to the update for the tfjs-core.

Thanks

**Comment by juamanuel** [comment]
What are the best versions of face-api, tfjs-core and tfjs-node to run together?
