### ISSUE TITLE
errors【Based on the provided shape the tensor should have 512 values but has 482】after built

### ISSUE THREAD

**Issue by nannan9507** [justadudewhohacks/face-api.js#257]
hey，I hava a problem.

the code is running successfully in my development environment, but when I built, it's show a error as 【Based on the provided shape the tensor should have 512 values but has 482】

the number is changed value when I turn to the other model

I'm sure the resources is loaded 200.but the error is also exist. And I don't use Vue , just the es6

**Comment by neel448** [comment]
@nannan9507  Did you find the solution for this ?

**Comment by createcandle** [comment]
Make sure you clear your browser cache.
