### ISSUE TITLE
use electron packaging，const result = await faceapi.detectSingleFace(videoEl, options);    result === undefined

### ISSUE THREAD

**Issue by achirsh** [justadudewhohacks/face-api.js#262]

**Comment by justadudewhohacks** [comment]
???

**Comment by achirsh** [comment]
html
`
<video id="inputVideo" onPlay={this.onPlay.bind(this} autoPlay muted/>
<canvas />
`

**Comment by achirsh** [comment]
![1](https://user-images.githubusercontent.com/13446367/55370581-7c5efd00-552d-11e9-938a-c2f56e7f4eb4.jpeg)
![2](https://user-images.githubusercontent.com/13446367/55370617-98fb3500-552d-11e9-9464-54c5832808a1.jpeg)
encapsulates the executable file using electronic.js

await faceapi.detectSingleFace(videoEl, options) === undefined

**WEB**
![3](https://user-images.githubusercontent.com/13446367/55370727-0d35d880-552e-11e9-80e8-975b8c32a34f.jpg)
**encapsulates the executable file using electronic.js**
![4](https://user-images.githubusercontent.com/13446367/55370776-440bee80-552e-11e9-8b99-3e65cff92ade.jpg)

**Comment by achirsh** [comment]
@justadudewhohacks

**Comment by achirsh** [comment]
![1554275534952](https://user-images.githubusercontent.com/13446367/55459816-0046e100-5623-11e9-9789-bd6106c3c3de.jpg)

**Comment by achirsh** [comment]
![1554278009373](https://user-images.githubusercontent.com/13446367/55462260-e6a89800-5628-11e9-90d8-bb6621a8bf89.jpg)

**Comment by justadudewhohacks** [comment]
Which backends are you using on the web and electron example, webgl or cpu?

**Comment by achirsh** [comment]
@justadudewhohacks Thanks for you，i replaced electron with nw.js, nw.js is ok.
