### ISSUE TITLE
What is best way to compare 2 faces? [Question]

### ISSUE THREAD

**Issue by je3f0o** [justadudewhohacks/face-api.js#265]
Hello.
I'm very noob in topic about face recognition and only second day playing with it.
I read acticles from author of these libraries 'Vincent Mühler' face-recognition.js and face-api.js tutorials on https://medium.com.
So I tried to compare 2 faces using opencv4nodejs and face-api.js in nodejs back-end.
But using `face_api.computeFaceDescriptor(reference_image);` is very slow.
All I need is compare only 2 faces. There is no need for training identity in my use case.
Please advice me what is best way to compare 2 faces only in nodejs back-end?
Thank you.

**Comment by justadudewhohacks** [comment]
You are probably not using tfjs-node, which speeds things up a lot.

**Comment by je3f0o** [comment]
You were right, I wasn't using tfjs-node. Because it wasn't working in my current machine MacOs 10.11 El Capitan. There is some issue with __clock_time in tfjs-node compiled binary. But I tried to install on linux machine and CPU backend it is so much improved. Thank you.
`Compute face descriptor performance: 188ms`
