### ISSUE TITLE
TypeError: detectSingleFace

### ISSUE THREAD

**Issue by Panepo** [justadudewhohacks/face-api.js#266]
Hi there,

I am building my project with face-api.js(0.19.0) and create react app(2.1.5), the browser throws an error on the following code:
```
const results = await faceapi
        .detectSingleFace(image)
        .withFaceLandmarks()
        .withFaceDescriptors()
```

The error message is as follows:

![2019-04-09_105523](https://user-images.githubusercontent.com/4687188/55770155-e63f4f80-5ab5-11e9-8fea-04eb829c9f4d.png)

I have tried different detection and landmark models and got the same message. 
Is there something wrong on my code?
Thanks

**Comment by justadudewhohacks** [comment]
Using detectSingleFace it has to be withFaceDescriptor instead of withFaceDescriptors. There is only 1 descriptor computed for that single face.

**Comment by Panepo** [comment]
Thanks.

Didn't notice there is a different.
