### ISSUE TITLE
examples for authentication with face id?

### ISSUE THREAD

**Issue by chovy** [justadudewhohacks/face-api.js#279]
Is it possible with this library to authenticate a user via facial recognition? If so how would I do that?

**Comment by ScottDellinger** [comment]
Sure is.

You'd need to get the descriptors of the people you want to authenticate (via a photo or something) and store that. Then you compare it to the descriptors of the person on the camera video feed and if you're u nder the threshold (0.6 or so is good, from my experience), that's a match.

**Comment by chovy** [comment]
Ok cool. Thanks

**Comment by wdebusschere** [comment]
Anyone willing to set this up for a fee?
