### ISSUE TITLE
A image with dimDiff = 1 will cause error in computeFaceDescriptor and padToSquare

### ISSUE THREAD

**Issue by hermanho** [justadudewhohacks/face-api.js#28]
When I call the function computeFaceDescriptor with an image which the different between width and height is 1 pixel, it will cause an error "Shapes can not be <= 0. Found 0 at dim 1" at this line:

https://github.com/justadudewhohacks/face-api.js/blob/cc63d787761123d6fbc6c0ced03016fca2e711e9/src/padToSquare.ts#L35

The value of paddingAmount is 0 so it cannot be concat.

**Comment by justadudewhohacks** [comment]
Thanks for reporting, I will look into this.
