### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by BalaKrishnaJ27Myntra** [justadudewhohacks/face-api.js#286]
Please let me know if there is support for react native and if not what changes can be done to support react native

**Comment by justadudewhohacks** [comment]
According to @nkreeger in https://github.com/tensorflow/tfjs/issues/1346:

> We don't fully support React Native - it is something we have on our roadmap but we haven't had a chance to figure out how to do this correctly.

face-api.js is built on top of tfjs-core, so the environment this library can be used in is mainly determined by where tfjs-core runs as well.
