### ISSUE TITLE
How to improve performance using node.js with openblas

### ISSUE THREAD

**Issue by masterulisses** [justadudewhohacks/face-api.js#295]
I'm also experiencing slowness problem when using faceRecognition on api-faces. I use windows and my tests are taking around three seconds to identify the face.
I already installed openblas on windows, but it looks like faces-api.js does not recognize it.

Sorry, you are requested to use face-recognition.js and this repository is saying This package is pretty much obsolete. I recommend you to switch to face-api.js.

Note: I'm already using dependencies:"@tensorflow/tfjs-node": "^1.0.2"

Please help me, I'm loving this api.

**Comment by justadudewhohacks** [comment]
Does it print any warning when importing tfjs-node? If there is a version mismatch, it might not be able to speed up things via tfjs-node, but using "@tensorflow/tfjs-node": "^1.0.2" should actually work.

Also keep in mind that face-api.js does not use openblas.

**Comment by masterulisses** [comment]
Thank you for the answer, please.

See package.json:
{
  "name": "ussrecognizeface",
  "version": "1.0.0",
  "description": "face identifier",
  "main": "server.js",
  "scripts": {
    "test": "echo \" Error: no test specified \ "&& exit 1",
    "start": "nodemon server.js --ignore * .marko.js"
  },
  "author": "Ulisses Silva de Souza",
  "license": "ISC",
  "dependencies": {
    "@ tensorflow / tfjs-node": "1.0.2",
    "canvas": "2.0.1",
    "express": "^ 4.16.4",
    "face-api.js": "^ 0.20.0",
    "marko": "^ 4.16.13"
  },
  "devDependencies": {
    "nodemon": "^ 1.19.0"
  }
}

See the log after npm install:

////////////// HOME LOG //////////////////////////////////

> @ tensorflow / tfjs-node @ 1.0.2 install C: \ development \ salesusWeb \ DropboxSvnRepository \ ussRecognizeFace \ node_modules \ @tensorflow \ tfjs-node
> node scripts / install.js

* Downloading libtensorflow
[=============================== 1150733 / bps 100% 0.0s
* Building TensorFlow Node.js bindings

> canvas@2.0.1 install C: \ development \ salesusWeb \ DropboxSvnRepository \ ussRecognizeFace \ node_modules \ canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[canvas] Success: "C: \ development \ salesusWeb \ DropboxSvnRepository \ ussRecognizeFace \ node_modules \ canvas \ build \ Release \ canvas-prebuilt.node" is installed via remote

> nodemon@1.19.0 postinstall C: \ development \ salesusWeb \ DropboxSvnRepository \ ussRecognizeFace \ node_modules \ nodemon
> node bin / postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN ussrecognizeface@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules \ fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os": "darwin", "arch": "any"} (current: {"os": "win32", "arch": "x64"})

added 392 packages from 253 contributors and audited 2600 packages in 70.31s
found 0 vulnerabilities
////////////// FIM LOG //////////////////////////////////

See the log after faceRecognition.js:
done, saved results to out/queryImage.jpg

**Comment by masterulisses** [comment]
Can the pc processor be the cause of being slow?

My machine:
Intel (R) Core (TM) i7-3537U CPU @ 2.00GHz 2.50 GHz
Memory: 8GB
system type: 64-bit

**Comment by justadudewhohacks** [comment]
Hmm it could be, just curious, are you actually importing `import '@tensorflow/tfjs-node';` in your code?

Also, do you mean the entire faceRecognition example is running for ~3s? Keep in mind that this example is processing 2 images, detecting all faces on them and for each detected face computing the landmarks and face descriptors, so 3s seems to be reasonable on the CPU.

Usually in the browser execution is much faster since ops are run on the GPU via WebGL. If you have an nvidia gpu you could also use the gpu version of tfjs-node.

**Comment by masterulisses** [comment]
1 - Yes I am using require ("@ tensorflow / tfjs-node");
see your env.js:
"use strict";
exports .__ esModule = true;
// import nodejs bindings to native tensorflow,
// not required, but will speed things up drastically (python required)
require ("@ tensorflow / tfjs-node");
// implements nodejs wrappers for HTMLCanvasElement, HTMLImageElement, ImageData
var canvas = require ('canvas');
exports.canvas = canvas;
var faceapi = require ("../../../ face-api.js");
// patch nodejs environment, we need to provide an implementation of
// HTMLCanvasElement and HTMLImageElement, additionally an implementation
// of ImageData is required, in case you want to use the MTCNN
var Canvas = canvas.Canvas, Image = canvas.Image, ImageData = canvas.ImageData;
faceapi.env.monkeyPatch ({Canvas: Canvas, Image: Image, ImageData: ImageData});

2 - Yes it is taking 3 seconds to compare images.
3 - As I'm developing an application that will compare a base image with several others in the repository, then 3 seconds is a lot.

But thanks for the help.

**Comment by justadudewhohacks** [comment]
Alright, yes 3s is a lot, thus it is better to get some GPU acceleration for example by using `@tensorflow/tfjs-node` in your nodejs app. But you will need an nvidida GPU.

**Comment by masterulisses** [comment]
I have NVIDIA GeForce GT 740m.
However, I spent several hours trying to configure @ tensorflow / tfjs-node-gpu without success.
Would you take a step by step?
Using gpu I would increase the speed in how much?
