### ISSUE TITLE
MobilenetV2 to tensorlfowjs webmodel

### ISSUE THREAD

**Issue by Sunwc0** [justadudewhohacks/face-api.js#296]
Hey!
Can you share me your scripts on how you converted the weights provided in https://github.com/yeephycho/tensorflow-face-detection to tfjs. 

I tried this but hit unsupported ops issue.
tensorflowjs_converter --input_format=tf_frozen_model --output_node_names='embeddings' saved_model/ output/

ValueError: Unsupported Ops in the model before optimization
QueueDequeueUpToV2, FIFOQueueV2

I saw https://github.com/justadudewhohacks/face-api.js/issues/50, but don't konw how to transform it

**Comment by justadudewhohacks** [comment]
Hey,

Sorry but there is no script. I did it mostly manually. If the tensorflowjs_converter says, that there are unsupported ops, then these ops remain to be implemented by the tfjs team. I am not familar with what these ops are doing "QueueDequeueUpToV2, FIFOQueueV2" but in some cases it is possible to skip postprocessing operations at the end of the graph and implement them manually.

Maybe you want to try to visualize the graph using tensorboard first, to figure out, where these ops occur in the graph.

**Comment by Sunwc0** [comment]
Thank for your answer, I tried restore a new graph and drop these unsupported ops node,It worked
