### ISSUE TITLE
To make changes in src which will reflect in face-api js call from nodejs like in running example-nodejs .

### ISSUE THREAD

**Issue by singhania1408** [justadudewhohacks/face-api.js#298]
I would like to make some changes in the src(like simple console.log() statements) and it doesn't reflect in running example-nodejs faceExpressionRecognition.ts file. 
Please suggest changes I need to done to show my logs in running examples.

**Comment by justadudewhohacks** [comment]
If you are making changes in the source code of face-api.js, then you also have to compile the typescript via tsc.

**Comment by singhania1408** [comment]
Thanks. But I have compiled through npm run-script build in the main directory then only compiled facialExpressionRecognition through tsc.
Can you please also share any research involved behind the project to make architectures and on what data it is trained and accuracy on test data etc.

**Comment by justadudewhohacks** [comment]
If you compile the example via tsc, then you have to execute the javascript files using nodejs, but I guess you are already doing so?

> Can you please also share any research involved behind the project to make architectures and on what data it is trained and accuracy on test data etc.

I am already including this kind of information in the README, for any further models that I am training I will also include benchmark results and test accuracy, as I did for the ageGenderNet in the last release.

Other than that, I am closing this issue, as your question is not really related to this project, but rather a basic javascript/typescript question.
