### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by vando97** [justadudewhohacks/face-api.js#301]
Hi you. 
First of all,  thanks with lib of you. I have some questions : 
- is pretreatment image in lib?  If have, you can help me find it in your code?
Thanks again.
I hope you answer my question.

**Comment by justadudewhohacks** [comment]
Hi,

What do you mean with pretreatment image? Image preprocessing? There is logic in this lib to create a batch tensor from all inputs including resizing and padding of input images, which is implemented [here](https://github.com/justadudewhohacks/tfjs-image-recognition-base/blob/master/src/dom/NetInput.ts#L121-L153) followed by [normalization](https://github.com/justadudewhohacks/face-api.js/blob/master/src/faceFeatureExtractor/FaceFeatureExtractor.ts#L25-L26).

**Comment by vando97** [comment]
Thanks very much.
That is the answer I need.
thank you again.

Vào 14:10, T.5, 23 Th5, 2019 Vincent Mühler <notifications@github.com> đã
viết:
