### ISSUE TITLE
Undefined when face-api is busy

### ISSUE THREAD

**Issue by idelburgo** [justadudewhohacks/face-api.js#305]
Hi, I don't know if it is really an issue or is my problem.
I am trying to use the library, and as it is async, I am sending frames to detect continuously.

My question is: What does the library return if you ask it to process another frame before it has finished processing the previous one? Does it return `undefined`?

**Comment by justadudewhohacks** [comment]
No the api is able to handle that, as far as I know the execution of the shader programs will simply be queued and scheduled to be executed on your GPU. However, I do not recommend to do that extensively and rather schedule prediction calls one after another, but you can experiment with that of course. You will see when performance starts to drop.
