### ISSUE TITLE
loading models in angular 

### ISSUE THREAD

**Issue by yaffaharari** [justadudewhohacks/face-api.js#307]
hi, 
I try to load models from my app component who located in: myproject/src/app/openCam/opencamComponent.ts
I run: 
Promise.all([ faceapi.nets.faceLandmark68Net.loadFromUri('./models')  ]);
I put the models folder in:  myproject/src/models. 
I got the error: 

ERROR Error: Uncaught (in promise): Error: failed to fetch: (404) Not Found, from url: http://localhost:4200/models/face_landmark_68_model-weights_manifest.json
Error: failed to fetch: (404) Not Found, from url: http://localhost:4200/models/face_landmark_68_model-weights_manifest.json

my models folder contains all files from: face-api.js/weights/ in this github repository. 
I know little about AI and I want to landmark only eyes.

**Comment by yaffaharari** [comment]
according the taturial.. I pat models folder into assets and changed the code line to: 
    await faceapi.nets.faceLandmark68Net.loadFromUri('assets/models');

**Comment by guilhermeaugustog** [comment]
The complete path to your model is project/src/assets/models ?
