### ISSUE TITLE
pre-processing

### ISSUE THREAD

**Issue by ngovando** [justadudewhohacks/face-api.js#308]
Hello. I want to annoy you again.
How does your photo pre-processing process take place? I see you use:
 const meanRgb = [122.782, 117.001, 104.298]
      const normalized = normalize (batchTensor, meanRgb) .div (tf.scalar (255)) as tf.Tensor4D

and resize images. But I found that while reading the docs, it showed that relying on 68 points of face you will get face image and resize the image to the face. So when will the image processing process take place? Before or after getting a face?

thank you very much.

**Comment by justadudewhohacks** [comment]
The pre processing of the network input will be applied at the beginning of each networks forward function.
