### ISSUE TITLE
Why not compatible with IE browsers? Is there a solution?

### ISSUE THREAD

**Issue by shdjllajksd** [justadudewhohacks/face-api.js#311]
Why not compatible with IE browsers? Is there a solution?

**Comment by rabbit1013** [comment]
I have same problem.

**Comment by ScottDellinger** [comment]
I would guess that support for IE is lacking because the last version of IE (11) is due for end-of-life in just a few months in January 2020.

**Comment by jeffreytgilbert** [comment]
It's around 10% and falling last I checked. Given the niche nature of projects developed with face recognition, you should prompt users to upgrade to a newer browser. There are options. Browsers older than IE 11 are basically nonexistent today thanks to the Windows 10 free edition baselining systems to at least IE 11 and/or Edge.

**Comment by dr1llc4t** [comment]
Because IE does not support WebGL 2.0. Same with Edge.

**Comment by spencerwaynesmith** [comment]
To make it work with Edge you need to set this config option:

faceapi.tf.ENV.set('WEBGL_PACK', false);

Works great for me on Edge now!
