### ISSUE TITLE
LabeledFaceDescriptor Issue

### ISSUE THREAD

**Issue by NasrAlmansoob** [justadudewhohacks/face-api.js#313]
Hello Vincent,

I know this question has been asked a few times, and I've looked at the solutions but couldn't resolve my issue using the available solutions. Just not sure what to change to a Float32Array.
I will attach my code below!

Thank you

![Screen Shot 2019-06-05 at 12 40 07 PM](https://user-images.githubusercontent.com/50146137/58977340-1aba4980-878f-11e9-9e15-afef385d3968.png)
![Screen Shot 2019-06-05 at 12 40 19 PM](https://user-images.githubusercontent.com/50146137/58977341-1aba4980-878f-11e9-80bc-6a3177e4cf56.png)

**Comment by NasrAlmansoob** [comment]
![Screen Shot 2019-06-05 at 12 42 36 PM](https://user-images.githubusercontent.com/50146137/58977469-6d940100-878f-11e9-8366-9684442836a9.png)

**Comment by justadudewhohacks** [comment]
Hi, `detectAllFaces` returns all faces (a javascript array), so fullFaceDescriptions.descriptor will be undefined in your code. Use detectSingleFace` if that's what you intended to do, or extract the descriptors from the array.
