### ISSUE TITLE
Model Licenses

### ISSUE THREAD

**Issue by gravypod** [justadudewhohacks/face-api.js#315]
Are the models included in this repo licensed under MIT? I'm doing an art project for a senior hum class at my college and wanted to make sure I didn't violate any of the license agreements of software I was using. 

Thanks!

**Comment by justadudewhohacks** [comment]
All of the model files available in this repo are licensed under MIT yes.

If you are really concerned about licenses of some of the original model weights, that I haven't trained by myself, then check out the license agreements for the [SSD Mobilenet V1](https://github.com/yeephycho/tensorflow-face-detection) face detector, the [MTCNN](https://github.com/kpzhang93/MTCNN_face_detection_alignment) and the [face recognition model](https://github.com/davisking/dlib-models).

All other models are created by myself and you can use them for whatever purpose you want.
