### ISSUE TITLE
Working with Videos in NodeJS

### ISSUE THREAD

**Issue by dijs** [justadudewhohacks/face-api.js#316]
I did not see any video examples in your nodejs folder.

I was wondering if this is supported yet, or is it just images currently?

I tried looking into it, and it seems I need to find a way to convert a video file to a `TNetInput`? Does that sound right?

I also looked for `HTMLVideoElement` polyfills for Node, but did not find any.

**Comment by justadudewhohacks** [comment]
face-api.js is not concerned with decoding video in nodejs, thus you might want to use any kind of polyfill (if exists) or video decoding package to generate tensors for video frames. For example I use opencv4nodejs in conjunction with face-api.js a lot.

**Comment by VKairon** [comment]
How do you integrate opencv4nodejs with face-api.js? Can you please be a little more specific. Thanks!

**Comment by justadudewhohacks** [comment]
@VKairon you can simply convert from an opencv Mat to a tensor using the following code:
``` javascript
// assuming img is a BGR Mat
const data = new Uint8Array(img.cvtColor(cv.COLOR_BGR2RGB).getData().buffer)
const imgTensor = faceapi.tf.tensor3d(data, [img.rows, img.cols, 3])
```
