### ISSUE TITLE
How to do facial recognition in videos?

### ISSUE THREAD

**Issue by VKairon** [justadudewhohacks/face-api.js#320]
I have been trying to implement facial recognition in videos and I just came upon face-api.js and I was wondering how to implement face recognition in videos using this?

**Comment by idelburgo** [comment]
There are two tutorials in the Readme file. You can maybe follow them to help you. Hope it helps

**Comment by VKairon** [comment]
Thanks!
Will try them.

**Comment by VKairon** [comment]
All the tutorials talk about images or webcams. Is there any resource for prerecorded videos?

**Comment by idelburgo** [comment]
The examples provided by the author. It has one prerecorded video of big bang theory. I would say download de example and take a look. Until someone answer

**Comment by justadudewhohacks** [comment]
As @idelburgo said, there are examples for that available.
