### ISSUE TITLE
npm install not working on Windows

### ISSUE THREAD

**Issue by hornta** [justadudewhohacks/face-api.js#321]
Hi. I really want to try this API but I have spent two full days trying to figure out why my `npm install` fails on me in Windows 10.
I am running node v10.5.0 and npm v6.9.0
I've posted the log of npm install right here.

https://hastebin.com/ebezikojaw.coffeescript

**Comment by sorxrob** [comment]
Do `npm -g install --production windows-build-tools` first and install it again.

**Comment by hornta** [comment]
I've tried that both locally and globally but I still get the same result.

**Comment by hornta** [comment]
Do no one else have this problem but me? I so want to use this API and I'm going crazy because of that :-)
