### ISSUE TITLE
Does face-api not support face similarity between video and image matching? Now I'm converting my face into canvas and comparing it with the image. That's a low recognition rate.   

### ISSUE THREAD

**Issue by zhangpeng1012** [justadudewhohacks/face-api.js#326]
Does face-api not support face similarity between video and image matching? Now I'm converting my face into canvas and comparing it with the image. That's a low recognition rate.

**Comment by justadudewhohacks** [comment]
The type of input (video, image) does not matter. There is probably some issue with your code or the reference image you are using. 

If this is still an issue, feel free to reopen and post the relevant code + reference Image you are using + an example query image, that was not recognized correctly.
