### ISSUE TITLE
Distance away picture cannot be detected in tiny face detector model.

### ISSUE THREAD

**Issue by esmeromichael** [justadudewhohacks/face-api.js#331]
Working fine in Ssd MobileNet, however when I using tiny face detector it will not working to detect a distance away picture.

**Comment by Archote** [comment]
Same issue too

**Comment by justadudewhohacks** [comment]
The SSD model is able to handle much smaller faces than the tiny face detection model I trained.

**Comment by esmeromichael** [comment]
@justadudewhohacks I used SSD model before and it's very nice, however it's very lag, that's why I tried tiny detection. Is the possible reason why it's lag because of my machine? or need higher GPU or else?

**Comment by justadudewhohacks** [comment]
> Is the possible reason why it's lag because of my machine? or need higher GPU or else?

Yes, the SSD model requires much more resources and will run slower than the tiny model.
