### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by powermikee** [justadudewhohacks/face-api.js#333]
What sort of servers would you need to run this to handle say 100s of requests a second. Would you recommend higher GPU or memory?

Thanks.

**Comment by justadudewhohacks** [comment]
Hard to say, I have never done such experiments. 

> Would you recommend higher GPU or memory?
Not sure what this means, but I would definetily recommend machines with a GPU for that scale.

**Comment by amitbend** [comment]
@powermikee I would suggest performing a load test on the library to find out.
You can use a load test library like [autocannon](https://github.com/mcollina/autocannon) on an isolated env (clean EC2 or docker image).

Post your results here if you end up doing it
