### ISSUE TITLE
extendStatics$1

### ISSUE THREAD

**Issue by informathis7** [justadudewhohacks/face-api.js#334]
Hi,
first of all, I would like thank you for all your works.
I encounter a problem when I use images on faceDetection and others api but not with the webcam, here is the error 
![image](https://user-images.githubusercontent.com/52248745/60188417-87c17c00-982f-11e9-9fed-3d8e4632eeb5.png)
here is the problem p.byteLength = 81881 and not 81888 !
![image](https://user-images.githubusercontent.com/52248745/60188459-99a31f00-982f-11e9-880d-919f03b4a165.png)
I have been surching for a long time, can you help me please ?

**Comment by justadudewhohacks** [comment]
`decodeWeights` comes from tfjs-core. Looks like the weight or shard files you are trying to load are malformed somehow.

**Comment by justadudewhohacks** [comment]
If this is still an issue feel free to reopen.
