### ISSUE TITLE
Issue With Euclidian distance of Facematcher

### ISSUE THREAD

**Issue by rakesh553** [justadudewhohacks/face-api.js#336]
const video = document.getElementById('input')

Promise.all([
  faceapi.nets.tinyFaceDetector.loadFromUri('/models'),
  faceapi.nets.faceLandmark68Net.loadFromUri('/models'),
  faceapi.nets.faceRecognitionNet.loadFromUri('/models'),
  faceapi.nets.faceExpressionNet.loadFromUri('face-api.js-master/weights'),
  faceapi.nets.ssdMobilenetv1.loadFromUri('face-api.js-master/weights'),
]).then(startVideo)

function startVideo() {
  navigator.getUserMedia(
    { video: {} },
    stream => video.srcObject = stream,
    err => console.error(err)
  )
}

video.addEventListener('play', () => {

  const canvas = faceapi.createCanvasFromMedia(video)
  canvas.style.position="absolute"
  document.body.append(canvas)
  const displaySize = { width: video.width, height: video.height }
    faceapi.matchDimensions(canvas, displaySize)

  setInterval(async () => {

    const detections = await faceapi.detectAllFaces(video, new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceDescriptor()
  //  detections = faceapi.resizeResults(detections,displaySize)
  const displaySize1 = {width:canvas.height, height:canvas.height}  
  const resizedDetections = faceapi.resizeResults(detections, displaySize1)
  canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height)  
  faceapi.draw.drawDetections(canvas,detections)
    const labels =['Rakesh']

    const labeledFaceDescriptors = await Promise.all(
     labels.map(async label => {
       const descriptions = []
       for (let i = 1; i <= 2; i++) {
         const img = await faceapi.fetchImage(`https://raw.githubusercontent.com/rakesh553/labels/master/${label}/${i}.jpg`)
         const detections1 = await faceapi.detectSingleFace(img).withFaceLandmarks().withFaceDescriptor()
         descriptions.push(detections1.descriptor)
         if (!detections1) {
            console.log("no faces detected for ${label}")
          }
       }
   
       return new faceapi.LabeledFaceDescriptors(label, descriptions)
     })
   )    
   const maxDescriptorDistance = 0.6
    const faceMatcher = new faceapi.FaceMatcher(labeledFaceDescriptors, maxDescriptorDistance)
const results = resizedDetections.map(d => faceMatcher.findBestMatch(d.descriptor))
 results.forEach((bestMatch ,i)=>{
     const box = resizedDetections[i].detection.box
     const text = bestMatch.toString()
     const drawBox = new faceapi.draw.Drawbox(box,{label:text})
     drawBox.draw(canvas)
 })

}, 100)})

This code when I run in chrome tells me that
it has some property height which is not defined

**Comment by justadudewhohacks** [comment]
Can you show me the error message / stack trace and on which line this error occurs please.

**Comment by justadudewhohacks** [comment]
If this is still an issue, feel free to reopen and post the error message / stack trace.

**Comment by rakesh553** [comment]
Hi Sir,
I apologise for the late reply. I had other project in process so I could
not answer to the issue.I got my application done. Thank you the support
and replying


Thanks & Regards
Rakesh
