### ISSUE TITLE
Error in detect face process

### ISSUE THREAD

**Issue by felipegonzalez1994** [justadudewhohacks/face-api.js#346]
hi, i have a error in 
```
const resultsRef =  await faceapi.detectSingleFace(referenceImage, faceDetectionOptions.faceDetectionOptions)
      .withFaceLandmarks()
      .withFaceDescriptors();
```
is a node backend, when starting it works correctly, but after a few attempts, it dies in that specific line where the faces of the image are detected.
when puts a try catch to the await, throws the next error
"TypeError: faceapi.detectSingleFace(...).withFaceLandmarks(...).withFaceDescriptors is not a function"
Node: 9.0
SO: Centos7
sorry for my bad english.

**Comment by justadudewhohacks** [comment]
Hi,

Using `detectSingleFace` it has to be `withFaceDescriptor` and not the plural form `withFaceDescriptors`-

**Comment by felipegonzalez1994** [comment]
> Hi,
> 
> Using `detectSingleFace` it has to be `withFaceDescriptor` and not the plural form `withFaceDescriptors`-

sorry, my bad but I still have the same problem, I run the server, made about 5 successful consultations and then it does not work anymore.
`await faceapi.detectSingleFace(referenceImage, faceDetectionOptions.faceDetectionOptions)
      .withFaceLandmarks()
      .withFaceDescriptors();` 
 begins to return "resultsRef=[]", and it does not work anymore even if i restart the server

**Comment by justadudewhohacks** [comment]
You probably mean resultsRef = undefined. `detectSingleFace` returns undefined if no face has been detected.

**Comment by dixit-rk** [comment]
> Hi,
> 
> Using `detectSingleFace` it has to be `withFaceDescriptor` and not the plural form `withFaceDescriptors`-


Thank You so Much Sir
