### ISSUE TITLE
models/face_landmark_68_model-shard1  not fount 404

### ISSUE THREAD

**Issue by MatheusDomingos** [justadudewhohacks/face-api.js#349]
I when placing the files in a subpath of my server, the project can not find the file:
 models / face_landmark_68_model-shard1 

Files with .json are localized but not others.

How to solve?

**Comment by justadudewhohacks** [comment]
Check the network tab, e.g. the URI your client attempts to fetch the shards from. Most likely the URI is invalid, or the files are not accessible under that URI.
