### ISSUE TITLE
SOLVED: Distance is high

### ISSUE THREAD

**Issue by LeonardoDB** [justadudewhohacks/face-api.js#352]
Hello Vincent, thanks for this fantastic API,

I'm getting some recognition tests, and my distance is low as you can see in the photo, is it possible this better? Thank you very much, I am using a photo in the base for the recognition, I already shot like photos, but I did not have significant changes.

![image](https://user-images.githubusercontent.com/33195732/61299257-1b92c200-a7b6-11e9-8c55-2e80bd830088.png)

**Comment by justadudewhohacks** [comment]
Can you show me the relevant code and the reference image/s you are using?

**Comment by LeonardoDB** [comment]
Hello Vincent, thank you for answering me quickly.

In this snippet of code is where I capture an image and do the detection of the broken using the tiny and check in the JSON if it has some similar

           shot = await blobImage();

           image = await faceapi.bufferToImage(shot.blob);
           image_shot = await shot.b64;

            const displaySize = { width: image.width, height: image.height };
            const detections = await faceapi.detectAllFaces(image, new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceDescriptors().withFaceExpressions();
            const resizedDetections = faceapi.resizeResults(detections, displaySize);
            const results = resizedDetections.map(d => faceMatcher.findBestMatch(d.descriptor));

            results.forEach((result, i) => {
                console.log(result);`

This image i use for traning

![image](https://user-images.githubusercontent.com/33195732/61318720-12b4e700-a7dc-11e9-8590-04c4bb52c543.png)

**Comment by justadudewhohacks** [comment]
Hmm looks good to me, what's the issue? The low distance tells you that the faces you are comparing are very similar.

**Comment by LeonardoDB** [comment]
Can you reduce even more from a distance? 0.4 for my application is very high yet, would have improve for + - 0.2

**Comment by justadudewhohacks** [comment]
Not really, 0.4 is already an indicator for very strong similarity. The threshold value should be 0.6 anyways.

**Comment by LeonardoDB** [comment]
Humm ok, thank very much Vincent, your API is fantastic!!! 

Hugs my friend.
