### ISSUE TITLE
Tiny Face Detector inputSize has strange effect on detect result?

### ISSUE THREAD

**Issue by zjlovezj** [justadudewhohacks/face-api.js#355]
I run some test on demo site: https://justadudewhohacks.github.io/face-api.js/face_and_landmark_detection

And found that when I choose different inputSize, some detected a face, some(224) didn't.
Is it a bug?
<img width="472" alt="faceapi-160" src="https://user-images.githubusercontent.com/388222/61441841-0619c580-a979-11e9-8634-5eaf3f49109a.png">

<img width="462" alt="faceapi-224" src="https://user-images.githubusercontent.com/388222/61441912-29dd0b80-a979-11e9-8e46-141242fcba56.png">

<img width="451" alt="faceapi-320" src="https://user-images.githubusercontent.com/388222/61441942-33667380-a979-11e9-80bd-fef6a256568d.png">

<img width="462" alt="faceapi-416" src="https://user-images.githubusercontent.com/388222/61441971-3eb99f00-a979-11e9-8eb4-3e0645e76d14.png">

Tested on MacBook Pro 2017 13'. Macos 10.14.5. Chrome 75.0.3770.142(64bit).

**Comment by justadudewhohacks** [comment]
Not really a bug, it just happens for some scales with the current model. If in doubt and you can afford it, run the prediction on different input sizes for better scalability.
