### ISSUE TITLE
withFaceDescriptors is not a function

### ISSUE THREAD

**Issue by tslater** [justadudewhohacks/face-api.js#356]
I am able to call `withFaceDescriptors()` successfully, but only when chaining it after `withFaceLandmarks()`. Is it possible to just call `withFaceDescriptors()` after `detectAllFaces()`? I just want the description and don't want to waste the the time loading and running the model for landmarks.

**Comment by summerscar** [comment]
i have this problem too

**Comment by wolhandlerdeb** [comment]
> I am able to call `withFaceDescriptors()` successfully, but only when chaining it after `withFaceLandmarks()`. Is it possible to just call `withFaceDescriptors()` after `detectAllFaces()`? I just want the description and don't want to waste the the time loading and running the model for landmarks.

I've  the same problem. Do you manage to fix this?
Thanks

**Comment by justadudewhohacks** [comment]
> Is it possible to just call withFaceDescriptors() after detectAllFaces()?

No it's not. `withFaceLandmarks` is required since it does apply alignment to the face image, without alignment the descriptor will be pretty much useless produced by the net currently available for face recognition.
