### ISSUE TITLE
Determine Face Shape

### ISSUE THREAD

**Issue by PolGuixe** [justadudewhohacks/face-api.js#359]
Would it be possible to detect the face shape? 
e.g. round, square, oval, etc. 
Not sure if training data exists with this information.

**Comment by linhbkhn95** [comment]
you can add feature_vector for my face ,
in docs has example.
const labeledDescriptors = [
  new faceapi.LabeledFaceDescriptors(
    'obama',
    [descriptorObama1, descriptorObama2]
  ),
  new faceapi.LabeledFaceDescriptors(
    'trump',
    [descriptorTrump]
  )
]

const faceMatcher = new faceapi.FaceMatcher(labeledDescriptors)

**Comment by justadudewhohacks** [comment]
Maybe it is possible to find a rule, based on the 68 face landmark points?
