### ISSUE TITLE
Error: Tensor is disposed

### ISSUE THREAD

**Issue by baskin** [justadudewhohacks/face-api.js#36]
Hi @justadudewhohacks ,

I'm getting the following after performing the below steps:
1. load models using `faceapi.loadModels('assets/models/') `(this is successful)
2. invoke `faceapi.allFaces(input, this.minConfidence).then(..` (where `input` is the id to a image element.  This fails with below error).

> core.js:1449 ERROR Error: Uncaught (in promise): Error: Tensor is disposed.
Error: Tensor is disposed.
    at t.throwIfDisposed (face-api.min.js:1)
    at t.asType (face-api.min.js:1)
    at t.toFloat (face-api.min.js:1)
    at face-api.min.js:1
    at Array.map (<anonymous>)
    at face-api.min.js:1
    at t.tidy (face-api.min.js:1)
    at rc (face-api.min.js:1)
    at face-api.min.js:1
    at t.tidy (face-api.min.js:1)
    at t.throwIfDisposed (face-api.min.js:1)
    at t.asType (face-api.min.js:1)
    at t.toFloat (face-api.min.js:1)
    at face-api.min.js:1
    at Array.map (<anonymous>)
    at face-api.min.js:1
    at t.tidy (face-api.min.js:1)
    at rc (face-api.min.js:1)
    at face-api.min.js:1
    at t.tidy (face-api.min.js:1)
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at e.invokeTask (polyfills.js:3)
    at i.isUsingGlobalCallback.invoke (polyfills.js:3)

Did I forget to do sth? Sorry, not familiar with how tensors work so maybe its a stupid question.

Thanks

**Comment by baskin** [comment]
Just realized this.
I was using `tfjs` for another library in my app. After removing it, `faceapi.allFaces` works!
What could be wrong?

> <script src="https://unpkg.com/@tensorflow/tfjs" defer></script>

**Comment by justadudewhohacks** [comment]
So the error occurs when you are additionally including the tfjs script to face-api.js? Does it work with tfjs-core?

Not sure if there are issues, when you are using tfjs additionally, because someone seemed to have issues with this in #9. In case tfjs-core is enough for your application, you can also access the bundled version via `faceapi.tf.`

**Comment by baskin** [comment]
> So the error occurs when you are additionally including the tfjs script to face-api.js? Does it work with tfjs-core?

yes and yes

> you can also access the bundled version via faceapi.tf

Can you please point me to how to use it? Sorry tf noob speaking :)

**Comment by justadudewhohacks** [comment]
> yes and yes

So it works with tfjs-core but not with tfjs?

> Can you please point me to how to use it? Sorry tf noob speaking :)

Well not quite sure what you mean. You can simply use tf via `faceapi.tf`. You could simply bind tf to the window object for convenience: `window.tf = faceapi.tf` and then use tf as you would normally.

**Comment by baskin** [comment]
> So it works with tfjs-core but not with tfjs?

Correct

> You could simply bind tf to the window object for convenience: window.tf = faceapi.tf and then use tf as you would normally.

I see. I'll try that. Closing. Thanks for the prompt responses.

**Comment by bharathvaj1995** [comment]
> So it works with tfjs-core but not with tfjs?
@justadudewhohacks  No. It doesnot work with both (tfjs & tfjs-core). It throws "Tensor disposed Error" for tfjs-core.
![image](https://user-images.githubusercontent.com/16360498/43047855-82badb32-8dfb-11e8-811a-58da23b956ff.png)
