### ISSUE TITLE
How to develop server side recognition model using faceapi, nodejs and express?

### ISSUE THREAD

**Issue by Dannybrown2710** [justadudewhohacks/face-api.js#362]
Hi ,

I am trying to develop a real time face recognition model using faceapi js using node and express. I have tried to recognize the face using the below code.

[https://gist.github.com/Dannybrown2710/5e30c063da936ee947d8fff474f9f57b](url)

But it seems that it takes a minute to train and recognize a model. Is there any way to improve recognizing speed to get real time results as in browser?

**Comment by linhbkhn95** [comment]
t has idea for you, you only load model once when start server. I am bulding project use sails server, detected and tracking realtime with camera ip.

**Comment by JJJvaa** [comment]
I did this demo website: https://facelogin.vaa.red

It's a basic user authentication with facial recognition using faceapi-js. Runs with node.js, express, and socket.io. GitLab repo where you can find the code: https://gitlab.com/vaared/facelogin

**Comment by justadudewhohacks** [comment]
> Is there any way to improve recognizing speed to get real time results as in browser?

Probably if you have an Nvidia GPU, otherwise you won't get GPU acceleration in node.
