### ISSUE TITLE
tracking 

### ISSUE THREAD

**Issue by linhbkhn95** [justadudewhohacks/face-api.js#364]
i am building project tracking realtime, 1s i getScreenshot from webcam, i must convert img to blod then sumbit to server,then detection. i must read file save local disk becase face-api only read from path file. can you read file from base 64 or blob ? i love face-api. i want finish project then write medium page for face-api :D

**Comment by justadudewhohacks** [comment]
> can you read file from base 64 or blob ?

Yes, either use the node canvas package as shown in the examples or use check out the decoding/encoding ops provided by tfjs-node.

**Comment by linhbkhn95** [comment]
you can help me a example code ?

**Comment by justadudewhohacks** [comment]
Take a look at the nodejs examples.
