### ISSUE TITLE
Use non Nvidia GPU in Node

### ISSUE THREAD

**Issue by neumartin** [justadudewhohacks/face-api.js#366]
I have an Intel GPU, if I use this in browser I get WebGL acceleration, but if I use Node I only get CPU backend, because the lack of CUDA cores.
Can I use WebGL in Node to use my Intel graphics card acceleration?

**Comment by justadudewhohacks** [comment]
> Can I use WebGL in Node to use my Intel graphics card acceleration?

As far as I know that's not possible, but your probably better off asking such kinds of questions to the tfjs community.
