### ISSUE TITLE
VideoJS as input source, RTMP

### ISSUE THREAD

**Issue by webdev778** [justadudewhohacks/face-api.js#371]
Hi,

I've been struggling to solve this issue for last few days.
but I couldn't find a way.
And I found #159 which literally exactly same to my case. 
But there doesn't provide final solution.

As the author of @#159 mentioned, video.js generate object for flash, I getting errors while using face-api.

I NEED Urgent help for this.
Thanks

**Comment by justadudewhohacks** [comment]
Please do not duplicate the issue then. We will keep track of this under #159.
