### ISSUE TITLE
Best approach to process large sets of images (100-500)

### ISSUE THREAD

**Issue by edoardolunardi** [justadudewhohacks/face-api.js#372]
Hi!
First of all, thank you for this great library.

I have to process an array of images, with 100-500 images: I need to find a particular face, given in input, among those 100-500 faces.

I did some tests with **ssdMobilenetv1** (I might need its accuracy): it took 48 seconds to process 100 images and a total of 500 faces (running in the browser and using detectAllFaces).

The problem is that, in the worst case, I might need to pass all the images.

What's the best approach for dealing with so many images?

Thank you in advance!

**Comment by justadudewhohacks** [comment]
I can't think of any other approach than what you are already doing.
