### ISSUE TITLE
face Expression

### ISSUE THREAD

**Issue by thirukumars** [justadudewhohacks/face-api.js#378]

**Comment by thirukumars** [comment]
i need the face Expression should come in console.please make an try(i need)

**Comment by thirukumars** [comment]
i mean if it happy means,it print happy in console like that

**Comment by uriel2707** [comment]
try to
`  const detections = await faceapi
        .detectSingleFace(this.video, this.cf.tyniOptions)
        .withFaceExpressions()`
` console.log(detections.expressions)`

**Comment by thirukumars** [comment]
i console.log in FaceExpressionDetection in  face-api.js file,it's working

and thank you for your response
