### ISSUE TITLE
Is there any method to use face-api for face detection in youtube video?

### ISSUE THREAD

**Issue by yhg8423** [justadudewhohacks/face-api.js#380]
I want to use face-api.js for face-detection in youtube video. However, I didn't find a method to use face-api with youtube video. Is there any method?

**Comment by justadudewhohacks** [comment]
If you are talking about a browser addon that let's you run face detection on their website I am not sure. Go write one! :)

Other than that the api accepts HTMLVideoElements, how you get the youtube video for example by downloading it, is up to you.
