### ISSUE TITLE
Some kind of isReady method

### ISSUE THREAD

**Issue by idelburgo** [justadudewhohacks/face-api.js#382]
Hi, 
is there some kind of `faceapi.isDetectorLoaded` or similar to avoid calling detection if it is not ready yet?

That would be great.

**Comment by justadudewhohacks** [comment]
Yes `net.isLoaded` will tell you if the network parameters have been loaded.

**Comment by idelburgo** [comment]
You are right! Sorry for the inconvenience. Im closing this issue.

**Comment by luckyboy07** [comment]
is this method gone? i'm using version 0.22.2 but this method is not available now. i'm kind a use it for not always load the models
