### ISSUE TITLE
Drawing landmarks with descriptors and size given

### ISSUE THREAD

**Issue by nevikw39** [justadudewhohacks/face-api.js#383]
Hello,

In the beginning, I would like to thanks for your exceptional effort toward this astonishing project. With this I make a Chrome extension and now I'm building a new web page. It took me, a high school student, a little hard time to comprehend the meaning of _"Euclidean Distance"_ between two descriptors which are 128-dimensional vectors actually.

Now, there is a page which can get the user's face descriptor via webcam. After computing his/her face descriptor, I want to save it, drawing the landmarks on the canvas at other time when user wants.
Therefore, is there any method to retrieve the landmarks from descriptors? The detection result is resizable, so I wonder the relation between landmarks and descriptors, and whether the descriptor whose value ranging from -1 to 1 is the result of normalization and could be inverted.
Otherwise, is there any approach to save the detection results?

With great appreciation

**Comment by justadudewhohacks** [comment]
I think you are confusing something here the face descriptor has nothing to with do with face landmark positions.
