### ISSUE TITLE
Frame drops when setting imageData tensor3D as input

### ISSUE THREAD

**Issue by imokya** [justadudewhohacks/face-api.js#384]
frame drops when I set a tensor3D object as input, is there any way to optimize? the code below is only for demostration, coz I can only access webcam fame data in a webview env.

const data = ctx.getImageData(0, 0, vw, vh)
const elem = faceapi.tf.browser.fromPixels(data)
const options = new faceapi.TinyFaceDetectorOptions({ inputSize, scoreThreshold })
const result = await faceapi.detectSingleFace(elem, options).withFaceLandmarks()

**Comment by justadudewhohacks** [comment]
What does "frame drops" mean? You also have to dispose the elem tensor after the API call (elem.dispose()), othewise you will end up with memory leaks.
