### ISSUE TITLE
run example failed on windows 10

### ISSUE THREAD

**Issue by wyl765** [justadudewhohacks/face-api.js#39]
[npm-debug.log](https://github.com/justadudewhohacks/face-api.js/files/2158626/npm-debug.log)
I cloned the repository, and run the example as the tutorial. but got error, I'm on Windows 10.

**Comment by justadudewhohacks** [comment]
The debug log doesn't help. Please tell me what you did and what kind of error was thrown.

**Comment by wyl765** [comment]
Below are all what I do and error message.

git clone https://github.com/justadudewhohacks/face-api.js.git
cd face-api.js
cd examples
npm i
npm start
app.post('/fetch_external_image', async (req, res) => {
                                        ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Learnings\face-api.js\examples\npm-debug.log

**Comment by justadudewhohacks** [comment]
`node v6.2.2` does not support async await out of the box. You can either upgrade your node version, or rewrite that function using Promises (or alternatively comment it out, but then you won't be able to fetch images from an external url).
