### ISSUE TITLE
Two or  more Reference Image for single person

### ISSUE THREAD

**Issue by thirukumars** [justadudewhohacks/face-api.js#390]
At present I can able compare Images for one person one reference Image.There is  way in face-api.js for detecting more than 1 image for same person....... with same image name(xxxx.jpg)

**Comment by Kryten0807** [comment]
I'm also looking for a way to do this. Here's the approach I'm thinking of...

1. generate a reference image with multiple images of the same person
1. match my new image against the reference image - if it matches **any** of the faces on the reference image, then we know it's that person

I'm not sure how well this will work... should I check the best score out of all the matches on the reference image or should I check the average?

**Comment by thirukumars** [comment]
i'm not sure about this,but in face-recognization api they used the technique.
here https://github.com/justadudewhohacks/face-recognition.js

**Comment by justadudewhohacks** [comment]
This API doesn't prescribe any way to deal with this, you can do whatever works best for you. If you have multiple reference images you could either want every reference image to match, atleast one image to match, compute the average of all distances... it's up to you.
