### ISSUE TITLE
illegal instruction (core dumped)

### ISSUE THREAD

**Issue by vadymkop** [justadudewhohacks/face-api.js#391]
To speed up face scanning in face-api.js, I used @tensorflow/tfjs-node as written in the readme. 
Everything is working okay on the local machine and in the docker (on local machine).
When i try to import @tensorflow/tfjs-node (via `require('@tensorflow/tfjs-node')`) on nodejs server, the application is crashing with error. The error message is the following: 

> illegal instruction (core dumped)

Without it line everything works okay, but very slowly.
How to resolve problem with “illegal instruction (core dumped)”?

**Comment by vadymkop** [comment]
The problem was resolved after configuring the server.

**Comment by davidmuggleton** [comment]
@vadymkop how did you fix the issue?

**Comment by Jefry-nolastname** [comment]
> The problem was resolved after configuring the server.

configuring what on the server??
