### ISSUE TITLE
Convert tfjs model to keras

### ISSUE THREAD

**Issue by GloveD** [justadudewhohacks/face-api.js#393]
hello，I'm glad to see your this excellent repo，but I met a demand and need to convert the tfjs model （age_gender_model-shard1，age_gender_model-weights_manifest.json）to the keras model. When using the [tfjs-converter](tfjs-converter) method, I found a problem, the field "modelTopology" isn't in the json file. How can I get the content of this part, I hope you can give some help.

**Comment by justadudewhohacks** [comment]
I have no clue sorry. Also keep in mind that although the weights_manifest.json files provided in this repo are in the manifest format of tfjs, the models are not / might not be valid tfjs web models.

If you can figure out what information is stored in "modelTopology" you could try to assemble them manually.
