### ISSUE TITLE
is we can object detection in face-API

### ISSUE THREAD

**Issue by thirukumars** [justadudewhohacks/face-api.js#399]
we want to do the object detection using yolo in this by using this api

**Comment by uriel2707** [comment]
face-API using tiny yolo model v2
[https://pjreddie.com/darknet/yolov2/](url)

Recommend
[https://itnext.io/face-api-js-javascript-api-for-face-recognition-in-the-browser-with-tensorflow-js-bcc2a6c4cf07](https://itnext.io/face-api-js-javascript-api-for-face-recognition-in-the-browser-with-tensorflow-js-bcc2a6c4cf07)
Loaded models 
```
await Promise.all([
      faceapi.nets.tinyFaceDetector.loadFromUri('/weights'),
      faceapi.nets.faceExpressionNet.loadFromUri('/weights')
    ])
```
set confing tiny yolo

```
tyniOptions = new faceapi.TinyFaceDetectorOptions({
      inputSize: 128,
      scoreThreshold: 0.5
    })
```
detect function
```
 const detections = await faceapi
        .detectSingleFace(input, tyniOptions)
        .withFaceExpressions()
```

**Comment by justadudewhohacks** [comment]
This API is not for arbitrary object detection. You can detect faces with it.
