### ISSUE TITLE
face landmark detection model Architecture?

### ISSUE THREAD

**Issue by Rakeshvcr** [justadudewhohacks/face-api.js#403]
What is the architecture of the face_landmark_68_model. I wanted to train my own landmark detection model with lesser points. please let me know the model architecture.

**Comment by thirukumars** [comment]
ssd model or tinyYolo or mtcnn we can use any of those three

**Comment by Rakeshvcr** [comment]
@thirukumars correct me if I'm wrong, I think all those model are only for detecting faces, If the faces are detected then, they are using face_landmark_68_model to detect landmark.

**Comment by justadudewhohacks** [comment]
> @thirukumars correct me if I'm wrong, I think all those model are only for detecting faces, If the faces are detected then, they are using face_landmark_68_model to detect landmark.

Correct.

From the README:

> 68 Point Face Landmark Detection Models
This package implements a very lightweight and fast, yet accurate 68 point face landmark detector. The default model has a size of only 350kb (face_landmark_68_model) and the tiny model is only 80kb (face_landmark_68_tiny_model). Both models employ the ideas of depthwise separable convolutions as well as densely connected blocks. The models have been trained on a dataset of ~35k face images labeled with 68 face landmark points.

The implementation is a bit hidden, but you can find the code of the forward method [here](https://github.com/justadudewhohacks/face-api.js/blob/master/src/faceFeatureExtractor/FaceFeatureExtractor.ts#L15-L36).

**Comment by IGhadalharbi** [comment]
hello
please i have question ,i need to know how the function will take the landmark of face?
and what is the landmark will take it?
thank u very much

**Comment by IGhadalharbi** [comment]
hello
why there is no answer?
thank u
