### ISSUE TITLE
Ionic Capacitor - loadFromUri

### ISSUE THREAD

**Issue by SimonScholl** [justadudewhohacks/face-api.js#404]
After i changed from a ionic cordova to capacitor build i experience issues loading the models.
On my PWA everything is working and the models are placed in the www/assests/models folder. But when i try to run the native android build i get this error message

```
Error: Uncaught (in promise): Error: Based on the provided shape, [1,1,512,512], the tensor should have 262144 values but has 216607
    Error: Based on the provided shape, [1,1,512,512], the tensor should have 262144 values but has 216607
        at d (http://localhost/vendor.js:100321:4453)
        at dn (http://localhost/vendor.js:100321:71403)
        at fn (http://localhost/vendor.js:100321:70965)
        at o (http://localhost/vendor.js:100321:444184)
        at _c (http://localhost/vendor.js:100321:444219)
        at http://localhost/vendor.js:100321:463380
        at Array.forEach (<anonymous>)
        at http://localhost/vendor.js:100321:463354
        at Array.forEach (<anonymous>)
        at http://localhost/vendor.js:100321:463142

```
In my previous build for the native android app with cordova the models where located at assets/www/assets/models now with capacitor the folder structure changed to assets/public/assets/models.

I load ssd with
`await faceapi.nets.ssdMobilenetv1.loadFromUri('assets/models');`

**Comment by esmircm** [comment]
> After i changed from a ionic cordova to capacitor build i experience issues loading the models.
> On my PWA everything is working and the models are placed in the www/assests/models folder. But when i try to run the native android build i get this error message
> 
> ```
> Error: Uncaught (in promise): Error: Based on the provided shape, [1,1,512,512], the tensor should have 262144 values but has 216607
>     Error: Based on the provided shape, [1,1,512,512], the tensor should have 262144 values but has 216607
>         at d (http://localhost/vendor.js:100321:4453)
>         at dn (http://localhost/vendor.js:100321:71403)
>         at fn (http://localhost/vendor.js:100321:70965)
>         at o (http://localhost/vendor.js:100321:444184)
>         at _c (http://localhost/vendor.js:100321:444219)
>         at http://localhost/vendor.js:100321:463380
>         at Array.forEach (<anonymous>)
>         at http://localhost/vendor.js:100321:463354
>         at Array.forEach (<anonymous>)
>         at http://localhost/vendor.js:100321:463142
> ```
> 
> In my previous build for the native android app with cordova the models where located at assets/www/assets/models now with capacitor the folder structure changed to assets/public/assets/models.
> 
> I load ssd with
> `await faceapi.nets.ssdMobilenetv1.loadFromUri('assets/models');`

I use ionic with capacitor and load the models in this way:

`await faceapi.loadSsdMobilenetv1Model('/assets/models');`
`await faceapi.loadFaceLandmarkModel('/assets/models');`

The extension of the models changed them to bin

![Captura de pantalla 2019-09-07 a las 1 13 13](https://user-images.githubusercontent.com/9834236/64465539-7937f080-d10d-11e9-9f80-0505827923e7.png)

Similarly in the .json files

![Captura de pantalla 2019-09-07 a las 1 15 36](https://user-images.githubusercontent.com/9834236/64465574-b56b5100-d10d-11e9-92d3-4ca960730b81.png)

Running on android and ios  🎉🎉

**Comment by SimonScholl** [comment]
@justadudewhohacks Thank you a lot this solved my issue. :)

**Comment by MMadume** [comment]
> > > After i changed from a ionic cordova to capacitor build i experience issues loading the models.
> > > On my PWA everything is working and the models are placed in the www/assests/models folder. But when i try to run the native android build i get this error message
> > > ```
> > > Error: Uncaught (in promise): Error: Based on the provided shape, [1,1,512,512], the tensor should have 262144 values but has 216607
> > >     Error: Based on the provided shape, [1,1,512,512], the tensor should have 262144 values but has 216607
> > >         at d (http://localhost/vendor.js:100321:4453)
> > >         at dn (http://localhost/vendor.js:100321:71403)
> > >         at fn (http://localhost/vendor.js:100321:70965)
> > >         at o (http://localhost/vendor.js:100321:444184)
> > >         at _c (http://localhost/vendor.js:100321:444219)
> > >         at http://localhost/vendor.js:100321:463380
> > >         at Array.forEach (<anonymous>)
> > >         at http://localhost/vendor.js:100321:463354
> > >         at Array.forEach (<anonymous>)
> > >         at http://localhost/vendor.js:100321:463142
> > > ```
> > > 
> > > 
> > > In my previous build for the native android app with cordova the models where located at assets/www/assets/models now with capacitor the folder structure changed to assets/public/assets/models.
> > > I load ssd with
> > > `await faceapi.nets.ssdMobilenetv1.loadFromUri('assets/models');`
> > 
> > 
> > I use ionic with capacitor and load the models in this way:
> > `await faceapi.loadSsdMobilenetv1Model('/assets/models');`
> > `await faceapi.loadFaceLandmarkModel('/assets/models');`
> > The extension of the models changed them to bin
> > ![Captura de pantalla 2019-09-07 a las 1 13 13](https://user-images.githubusercontent.com/9834236/64465539-7937f080-d10d-11e9-9f80-0505827923e7.png)
> > Similarly in the .json files
> > ![Captura de pantalla 2019-09-07 a las 1 15 36](https://user-images.githubusercontent.com/9834236/64465574-b56b5100-d10d-11e9-92d3-4ca960730b81.png)
> > Running on android and ios 🎉🎉
> 
> Thy this solved my issue :)

Thank you. Solved my issue as well

**Comment by Nil0801** [comment]
Hello @MMadume, @esmircm and @SimonScholl 
I am also working in Ionic capacitor and facing some issues with loading a model. Can you please help me with that? Can you share how did you load your model ? 
Thank you

**Comment by jairforero** [comment]
Hi I rename models to .bin and change this in json but say error in android

2020-11-16 15:35:27.015 24121-24121/systemsweb.net E/Capacitor/Console: File: http://localhost/vendor-es2015.js - Line 41309 - Msg: ERROR Error: Uncaught (in promise): Error: SsdMobilenetv1 - load model before inference
    Error: SsdMobilenetv1 - load model before inference
        at SsdMobilenetv1.push../node_modules/face-api.js/build/es6/ssdMobilenetv1/SsdMobilenetv1.js.SsdMobilenetv1.forwardInput (http://localhost/tab3-tab3-module-es2015.js:13925:19)
        at SsdMobilenetv1.<anonymous> (http://localhost/tab3-tab3-module-es2015.js:13959:35)
        at step (http://localhost/vendor-es2015.js:123912:23)
        at Object.next (http://localhost/vendor-es2015.js:123893:53)
        at fulfilled (http://localhost/vendor-es2015.js:123883:58)
        at ZoneDelegate.invoke (http://localhost/polyfills-es2015.js:3470:30)
        at Object.onInvoke (http://localhost/vendor-es2015.js:73011:33)
        at ZoneDelegate.invoke (http://localhost/polyfills-es2015.js:3469:36)
        at Zone.run (http://localhost/polyfills-es2015.js:3229:47)
        at http://localhost/polyfills-es2015.js:3963:40

**Comment by MRolefes** [comment]
> > After i changed from a ionic cordova to capacitor build i experience issues loading the models.
> > On my PWA everything is working and the models are placed in the www/assests/models folder. But when i try to run the native android build i get this error message
> > ```
> > Error: Uncaught (in promise): Error: Based on the provided shape, [1,1,512,512], the tensor should have 262144 values but has 216607
> >     Error: Based on the provided shape, [1,1,512,512], the tensor should have 262144 values but has 216607
> >         at d (http://localhost/vendor.js:100321:4453)
> >         at dn (http://localhost/vendor.js:100321:71403)
> >         at fn (http://localhost/vendor.js:100321:70965)
> >         at o (http://localhost/vendor.js:100321:444184)
> >         at _c (http://localhost/vendor.js:100321:444219)
> >         at http://localhost/vendor.js:100321:463380
> >         at Array.forEach (<anonymous>)
> >         at http://localhost/vendor.js:100321:463354
> >         at Array.forEach (<anonymous>)
> >         at http://localhost/vendor.js:100321:463142
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In my previous build for the native android app with cordova the models where located at assets/www/assets/models now with capacitor the folder structure changed to assets/public/assets/models.
> > I load ssd with
> > `await faceapi.nets.ssdMobilenetv1.loadFromUri('assets/models');`
> 
> I use ionic with capacitor and load the models in this way:
> 
> `await faceapi.loadSsdMobilenetv1Model('/assets/models');` `await faceapi.loadFaceLandmarkModel('/assets/models');`
> 
> The extension of the models changed them to bin
> 
> ![Captura de pantalla 2019-09-07 a las 1 13 13](https://user-images.githubusercontent.com/9834236/64465539-7937f080-d10d-11e9-9f80-0505827923e7.png)
> 
> Similarly in the .json files
> 
> ![Captura de pantalla 2019-09-07 a las 1 15 36](https://user-images.githubusercontent.com/9834236/64465574-b56b5100-d10d-11e9-92d3-4ca960730b81.png)
> 
> Running on android and ios 🎉🎉

Thanks allot! You just saved me from a 10 hour hassle debugging the face-api why it wasn't loading the weight maps...
