### ISSUE TITLE
Outputting face emotion values onto input textbox rather than canvas

### ISSUE THREAD

**Issue by jk939393** [justadudewhohacks/face-api.js#405]
Hello,
I would like to output face expressions into a textbox outside of the canvas rather than being drawn on canvas element I have successfully used  **faceapi.draw.drawFaceExpressions(canvas, resizedDetections)** to draw emotions on the user, but I would like the emotions to display live to a textbox outside of the canvas
like this but instead of user input, input from the detections. console.log(detections) shows the individual emotions in the console as objects, 

expressions: t
angry: 0.024997340515255928
disgusted: 0.183808371424675
fearful: 0.0007150841993279755
happy: 0.005134096834808588
neutral: 0.5548677444458008
sad: 0.22994768619537354
surprised: 0.000529530574567616

 but I do not know how to write these into a textbox after they are in the console

I ultimately want these in a textbox so i can create a funcion from the values in the textbox

`<script>
function showMsg2(){
  var userInput = document.getElementById('userInput2').value;
  document.getElementById('userMsg2').textContent = userInput;
}
</script>
<input type="input" maxlength="40" id="userInput2" onkeyup="showMsg2()" **placeholder="Enter text here...">**
<p id="userMsg2"></p>
`

**Comment by justadudewhohacks** [comment]
Your question is not related to face-api.js. Please do not ask basic javascript questions here. Stackoverflow / Google are the way to go for that and you will receive a solution / response much faster.
