### ISSUE TITLE
expected media to be of type HTMLImageElement

### ISSUE THREAD

**Issue by warhammercasey** [justadudewhohacks/face-api.js#408]
```
const faceapi = require('face-api.js');
require('@tensorflow/tfjs-node');
const fetch = require('node-fetch');
const path = require('path');

faceapi.env.monkeyPatch({ fetch: fetch });

const MODELS_URL = path.join(__dirname, '/models/');
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
global.window = new JSDOM(`<!DOCTYPE html><img id="myImg" src="image.png" />`, { resources: "usable", url: "file:///" + __dirname + "/" }).window;
global.document = window.document;
global.HTMLElement = window.HTMLElement;`

async function detectFaceCommand(message) {
    await faceapi.nets.ssdMobilenetv1.loadFromDisk(MODELS_URL);
    await faceapi.nets.faceLandmark68Net.loadFromDisk(MODELS_URL);
    await faceapi.nets.faceRecognitionNet.loadFromDisk(MODELS_URL);
    image = document.getElementById('myImg');
    let fullFaceDescriptions = await faceapi.detectSingleFace(image).withFaceLandmarks().withFaceDescriptor();
}
```

This just gives me `Error: toNetInput - expected media to be of type HTMLImageElement | HTMLVideoElement | HTMLCanvasElement | tf.Tensor3D, or to be an element id`

Outputting `image` to the console shows that it is an HTMLImageElement yet it still says its not.

**Comment by justadudewhohacks** [comment]
Might be that the image element returned by JSDOM is not a valid HTMLImageElement, e.g. `img instanceof HTMLImageElement` returns false. If that's the case you could try to monkey patch HTMLImageElement somehow.

**Comment by warhammercasey** [comment]
I messed around with it for a bit and `image instanceof HTMLImageElement` returns true. In the code snippet I provided I realized `global.HTMLElement = window.HTMLElement` was supposed to be `global.HTMLImageElement = window.HTMLImageElement` but I still get `expected media to be of the type HTMLImageElement`

**Comment by justadudewhohacks** [comment]
> I got around this issue by adding Image: window.HTMLImageElement to monkeypatch but now I get TypeError: canvas.getContext is not a function in getContext2dOrThrow.js so I'm assuming I need to do similar to env.Canvas with monkeyPatch but I cant figure out what I need to set it to.

Exactly, checlk out the nodejs examples that utilize the canvas node package to monkey patch Image, Canvas and ImageData.

I am actually not sure what kind of environment you are running your code, but you also wanna try monkey patching the constructors of Image and Canvas:

``` javascript
faceapi.env.monkeyPatch({ 
  createCanvasElement: () => document.createElement('canvas'), 
  createImageElement: () => document.createElement('img') 
})
```

**Comment by warhammercasey** [comment]
Thanks a ton this worked:
```
faceapi.env.monkeyPatch({
    fetch: fetch,
    Canvas: window.HTMLCanvasElement,
    Image: window.HTMLImageElement,
    ImageData: canvas.ImageData,
    createCanvasElement: () => document.createElement('canvas'),
    createImageElement: () => document.createElement('img')
});
```
