### ISSUE TITLE
Use a another face detection model instead of the existed models in the repo

### ISSUE THREAD

**Issue by huybg-1975** [justadudewhohacks/face-api.js#414]
Hi @justadudewhohacks,
I really love your work and find that it is useful for my work.
Today, I want to try some another models (face detection) that not exists in your repo and model that I want run is resnet-ssd such [here](https://github.com/LZQthePlane/Face-detection-base-on-ResnetSSD/blob/master/Res10_300x300_SSD_iter_140000.caffemodel), it use caffe model and I try it under python enviroment with opencv dnn module successfully.

Can you support me for this work ?
Thanks in advance.

**Comment by justadudewhohacks** [comment]
The easiest way that I could think of right now is to convert the caffe model to tensorflow and then use tfjs-converter, to convert it to a web model.
