### ISSUE TITLE
Is there any solution to tell the different between real face and face from a picture

### ISSUE THREAD

**Issue by Al-JeMay** [justadudewhohacks/face-api.js#419]
What is the best solution on how to differentiate the face detection result of a person in front of a camera from a person just holding an image of him. 

Thank you in advance and thanks again for your wonderful API :)

**Comment by ariffromeo** [comment]
there is model called liveness detection that can spot between fake and real person. it would be good if face-api.js can load the model too. i have the keras model and converted it into js model. i just dont know how to implement it into this api. u can read it here [https://www.pyimagesearch.com/2019/03/11/liveness-detection-with-opencv/](https://www.pyimagesearch.com/2019/03/11/liveness-detection-with-opencv/)

**Comment by justadudewhohacks** [comment]
face-api.js does not provide a model for that task, I am not even sure, how a neural network would be able to solve that task.

@ariffromeo if you have a Keras model, then you can convert it to a web model and run it using the tfjs-converter.

**Comment by Otherwa** [comment]
So any alt ? @justadudewhohacks
