### ISSUE TITLE
Implementing mtcnn for face detection and 5 point landmarks

### ISSUE THREAD

**Issue by justadudewhohacks** [justadudewhohacks/face-api.js#42]
The face detection and alignment approach of [mtcnn](https://github.com/kpzhang93/MTCNN_face_detection_alignment) from this [paper](https://kpzhang93.github.io/MTCNN_face_detection_alignment/paper/spl.pdf) seems to be a promising alternative for real time face detection + face alignment. Next thing on my TODO list.

**Comment by akofman** [comment]
Sounds exciting. Just to understand well, the aim here is to get a faster, "lighter" way for faces detection right ?

I'm not sure if it helps but I've found this tf implementation : https://github.com/AITTSMD/MTCNN-Tensorflow, I guess you have to adapt in order to keep the tfjs compatibility.

Thanks for your awesome work.

**Comment by justadudewhohacks** [comment]
Exactly that is the purpose. Plus mtcnn detects 5 point face landmarks along the way, which is enough for face alignment, so you could also skip the 68 point face landmark detection for face recognition.

Thanks for sharing the link, I already played around with this repo and a few others. The results look very promising and I am already into porting this architecture to tfjs. Hopefully I can show some results soon ;)

**Comment by thexiroy** [comment]
Sounds pretty promising any ETA? :) The current face detection is not suited for real-time detection (got 1 second on my laptop) so I am currently trying/using other alternatives. Looking forward to it!

**Comment by justadudewhohacks** [comment]
Turns out, that reimplementing the mtcnn architecture with tfjs is much trickier than I thought. However a few days ago I managed to get a first working solution. I still have to identify some performance bottlenecks and do some fine tuning. 

But first results show a significant speedup to the current SSD implementation. With mtcnn you also have some parameters allowing to get better overall performance. Atleast on my machine I can get realtime performance on the video face detection example with the current state of the implemenation.

Im currently working on the [mtcnn](https://github.com/justadudewhohacks/face-api.js/tree/mtcnn) branch. I will try to make it available as sonn as possible.

**Comment by akofman** [comment]
That sounds good ! Just curious about it, why did you choose to have a try with mtcnn. I also read some good results with YOLOv3 (https://pjreddie.com/darknet/yolo) but I'm not able to say which one is the fastest algorithm.

**Comment by justadudewhohacks** [comment]
Yolo v3 also seems to be a good option to investigate. I just read that yolov3 uses quite some layer, whose implementation is specific to darknet. 

Furthermore, I don't think there is any yolo v3 model trained specifically for face detection yet, meaning we would have to train it from scratch. Yolo v2 is certainly an option, but while it may be faster then the already implemented SSD face detector it will probably not be as accurate.

I chose mtcnn since it seemed to be very lightweight, e.g. it is fast, has a small model size (only 2mb without any quantization) seems to be highly configurable for your needs by tuning paramaters.

**Comment by thexiroy** [comment]
I have also tested the current face detection on my mobile (S8+), it seems to take around 3 seconds to detect a single face from a 384*216 photo.
I am currently looking into alternatives such as: pico.js (https://tkv.io/posts/picojs-intro/), it's fast but I am not sure if it works with face-recognition.js.

Anyway, looking forward to your results.

**Comment by justadudewhohacks** [comment]
Yea I think mobile is a specific case, we wont simply get realtime for a mobile device that easily. Maybe its better for face detection on mobile to use simpler solutions such as haar features or viola jones instead of a cnn.

**Comment by justadudewhohacks** [comment]
Finally it's done. The Mtcnn has some weird warmup time, but I  for live face detection by video / webcam I roughly see an average speedup somewhere between 2 - 4x on my main machine as well as a huge speedup on my laptop.

With that being said I am closing here. @akofman , I would like to keep up the YOLO discussion in another issue however, which might be worth some further investigations in future as well. Also @thexiroy I would be interested in your findings (performance wise) regarding pico.js or any other tool that would possibly be most suitable for face detection on mobile.

**Comment by akofman** [comment]
Congrats 👏 👏 ! I've just tested it with a video and it's really faster. On my MBP Core i7 I have no lag anymore, I didn't measure it precisely but the difference is impressive.
Unfortunately I didn't manage to test it on my old Nexus 5 phone because of a 'Failed to compile fragment shader' error ... I'm also curious to compare it with picojs.

**Comment by justadudewhohacks** [comment]
Great to hear! Let me know if this issue persists, I thought I fixed all those shader compilation errors, which most of the time occured to me, when the images have been scaled down too much.

**Comment by zhaoningning** [comment]
@justadudewhohacks  Did you train mtcnn from scratch or use the released models trained by others, I find the performance of your mtcnn model is not very stable

**Comment by justadudewhohacks** [comment]
The weights are taken from the official repo, as stated in the README, I didn't retrain the model.
