### ISSUE TITLE
load model before inference

### ISSUE THREAD

**Issue by demchenkodenis** [justadudewhohacks/face-api.js#420]
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>title</title>
		
		<link rel="stylesheet" href="css/main.css">
		
	</head>
	<body>
		https://sun9-58.userapi.com/c638524/v638524146/57f04/76YNYJz82jY.jpg
		
		<img id="myImg" src="">
		
		<button>get img</button>

		<script src="js/jquery.js"></script>
		<script src="js/face-api.js"></script>
		
		<script src="js/main.js"></script>
		
	</body>
</html>

main.js

$(document).ready(function() {

	$('button').on('click', getImg);
	
	async function getImg(){
  		
  		const image = await faceapi.fetchImage('https://sun9-58.userapi.com/c638524/v638524146/57f04/76YNYJz82jY.jpg')
		console.log(image instanceof HTMLImageElement) // true
		// displaying the fetched image content
		const myImg = document.getElementById('myImg')
		myImg.src = image.src
		const detections = await faceapi.detectAllFaces(image, await new faceapi.SsdMobilenetv1Options({ minConfidence: 0.6 }));
		//console.log(detections)
		console.log(detections)

	}

});

Error:
face-api.js:4675 Uncaught (in promise) Error: SsdMobilenetv1 - load model before inference
    at SsdMobilenetv1.forwardInput (face-api.js:4675)
    at SsdMobilenetv1.<anonymous> (face-api.js:4709)
    at step (face-api.js:78)
    at Object.next (face-api.js:59)
    at fulfilled (face-api.js:49)

**Comment by idelburgo** [comment]
You should call the method to load the models as stated [https://github.com/justadudewhohacks/face-api.js#loading-the-models](here) in the doc before using the 'detectAllFaces' method in your case

**Comment by swapanil** [comment]
Hi can you give me a code snippet how to do in react js I have tried but giving me same error?

**Comment by ghost** [comment]
Hi. Even I get the same error on react js. 
 I have included it.

Promise.all([
            faceapi.nets.tinyFaceDetector.loadFromUri(MODELURL),
            faceapi.nets.faceLandmark68Net.loadFromUri(MODELURL),
            faceapi.nets.ssdMobilenetv1.loadFromUri(MODELURL)
            ]).then(console.log("Loaded models")).catch(e=>console.log(e))

It outputs "Loaded models', but it still shows the above error

**Comment by RuthvikRaviKumar** [comment]
> Hi can you give me a code snippet how to do in react js I have tried but giving me same error?


> Hi. Even I get the same error on react js.
> I have included it.
> 
> Promise.all([
> faceapi.nets.tinyFaceDetector.loadFromUri(MODELURL),
> faceapi.nets.faceLandmark68Net.loadFromUri(MODELURL),
> faceapi.nets.ssdMobilenetv1.loadFromUri(MODELURL)
> ]).then(console.log("Loaded models")).catch(e=>console.log(e))
> 
> It outputs "Loaded models', but it still shows the above error

It works if you give a URL. I forked the face-api to my repos and I loaded models using github URLs.

example: faceapi.nets.faceRecognitionNet.loadFromUri("https://raw.githubusercontent.com/RuthvikRaviKumar/face-api.js/master/weights/")

**Comment by tanmay-joshi** [comment]
Hello, for anyone looking for the solution to React js, you need to download the "models" folder from https://github.com/justadudewhohacks/face-api.js/tree/master/weights and add the folder to your "public" folder.
After that, you can simply load it via 

Promise.all([
faceapi.nets.tinyFaceDetector.loadFromUri("/models"),
faceapi.nets.faceLandmark68Net.loadFromUri("/models"),
faceapi.nets.ssdMobilenetv1.loadFromUri("/models")
])

**Comment by xahram** [comment]
Hi, I'm getting the same error despite loading the models, I also have the models in my public folder and provided the paths correctly but still getting the same error.

Script File:

const MODEL_URL = "/weights";
const net = new faceapi.SsdMobilenetv1()
Promise.all([
    net.loadFromUri(MODEL_URL),
    faceapi.nets.faceRecognitionNet.loadFromUri(MODEL_URL),
    faceapi.nets.faceLandmark68Net.loadFromUri(MODEL_URL),
]).then((val) => {
    console.log(val)
}).catch((err) => {
    console.log(err)
})


Express Server :

const express = require("express")
const path = require('path')
const app = express()
const hbs = require("hbs")


const publicFolder = path.join(__dirname, '../public')
const viewsPath = path.join(__dirname, "../views")

app.use(express.static(publicFolder));


app.set("view engine", "hbs");
app.set("views", viewsPath);

app.get('/', (req, res) => {
    res.render('index')
})

app.listen(7000, () => {
    console.log("Listening On port 7000")
})

**Comment by xranby** [comment]
you need to be 100% sure your models are loaded.
one solution is to execute the face detection logic inside the callback when the promise complete
example working code: https://stackoverflow.com/a/63568335
