### ISSUE TITLE
How to train a model that can recognize my face?

### ISSUE THREAD

**Issue by UCASHurui** [justadudewhohacks/face-api.js#422]
Hi, I am trying to utlize face recognition model in a project and I want to recognize my own face. However I am still very new to tensorflow and this great project, I need some help to guide me. I really appreciate any help! Thanks.

**Comment by justadudewhohacks** [comment]
You do not train a new model, with the existing model you are able to recognize any peoples face. If you are unsure how to do so, take a look at the tutorials and examples first.
