### ISSUE TITLE
How to detect all faces from local file node js

### ISSUE THREAD

**Issue by agnoam** [justadudewhohacks/face-api.js#424]
Hey, 
I'm using node js. I want to detect all the faces available from file buffer or a link to it. 
(like `./uploads/images/${filename}`)

this is possible at this library ?

**Comment by fadiabdeen** [comment]
I'm actually looking to do the same thing , so we do not have to process the file multiple times. we want to store the face data in the database. I was able to convert the data in the array coming from detectAllFaces to a JSON data (this is probably what you are looking for Noam).. this worked fine . but my struggle now is to revert it back and use it .. if there is any tip about doing that, would be great. Thanks

**Comment by agnoam** [comment]
Can you show me an example for `detectAllFaces()` that runs on an image file

**Comment by fadiabdeen** [comment]
check this out : https://github.com/justadudewhohacks/face-api.js/issues/231

**Comment by justadudewhohacks** [comment]
You have to create the image data from your link / data buffer. face-api.js accepts input images as Tensors, HTML image, canvas or video elements.

For nodejs you can use the node-canvas package to read images from disk, furthermore tfjs-node has utility to create Tensors from png/jpeg image buffers read via fs.readFile.

**Comment by punisher97** [comment]
Hi, in NodeJS with new version of tensorflow if more easy and decode buffer directly with new API tf.node.decodeImage:
I hope help to any

```

function getPhotoTensor(pathPhto) {
  return fs.readFile(pathPhto).then(buffer => {
    return tf.node.decodeImage(new Uint8Array(buffer));
  });
}
// then use function 
const input = await getPhotoTensor("image/person.jpg");
const results = await faceapi
      .detectAllFaces(input)
      .withFaceLandmarks()
      .withFaceDescriptors();
```
