### ISSUE TITLE
node js examples not working

### ISSUE THREAD

**Issue by ankurpowar** [justadudewhohacks/face-api.js#425]
when I run the node js example I am getting errors when compiling and running.

using cmd: ""npx ts-node faceDetection.ts" 

cpu backend was already registered. Reusing existing backend factory.
Platform node has already been set. Overwriting the platform with [object Object].
node-pre-gyp info This Node instance does not support builds for N-API version 4
node-pre-gyp info This Node instance does not support builds for N-API version 4
Cannot find module '[*localpath]\face-api.js\examples\examples-nodejs\node_modules\@tensorflow\tfjs-node\lib\napi-v3\tfjs_binding.node'

*****************************************************************************************
using cmd: "npx tsc faceDetection.ts"

node_modules/@types/webgl2/index.d.ts:582:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'WebGL2RenderingContext' must be of type '{ new (): WebGL2RenderingContext; prototype: WebGL2RenderingContext; readonly ACTIVE_ATTRIBUTES: number; readonly ACTIVE_TEXTURE: number; readonly ACTIVE_UNIFORMS: number; readonly ALIASED_LINE_WIDTH_RANGE: number; ... 554 more ...; readonly WAIT_FAILED: number; }', but here has type '{ new (): WebGL2RenderingContext; prototype: WebGL2RenderingContext; readonly ACTIVE_ATTRIBUTES: number; readonly ACTIVE_TEXTURE: number; readonly ACTIVE_UNIFORMS: number; readonly ALIASED_LINE_WIDTH_RANGE: number; ... 555 more ...; readonly MAX_CLIENT_WAIT_TIMEOUT_WEBGL: number; }'.

582 declare var WebGL2RenderingContext: {
                ~~~~~~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:16450:13
    16450 declare var WebGL2RenderingContext: {
                      ~~~~~~~~~~~~~~~~~~~~~~
    'WebGL2RenderingContext' was also declared here.

Found 1 error.

**************************************************************************************
I actually want to use faceapi in an angular app but I am getting some errors regarding 'faceapi.env.monkeyPatch({ Canvas, Image, ImageData })' so I tried to take  reference from this example but got this error. please help.
**************************************************************************************

**Comment by justadudewhohacks** [comment]
Why are you running nodejs examples with npx? You should be using the browser environment of face-api.js.
