### ISSUE TITLE
Maybe somebody did a api from this? I try to do emotion detection.

### ISSUE THREAD

**Issue by MacMillan13** [justadudewhohacks/face-api.js#442]
I send a get request from my php to browser example and don't get a result of detection, becouse js scripts don't  work. Have a error that file didn't find. I'm php developer, to me it's so amazing error, becouse if we send request on php api, that api use his php code, but this error said that they tried to find error on my server.
Plse help me. Best result to me to make some api, may be you finded something like this.
Thanks.

**Comment by Mactacs** [comment]
What error did you get when using the api? Can you paste it here for clarification

**Comment by MacMillan13** [comment]
I just try to do a api by example-browser.
TypeError: Cannot set property 'width' of undefined
    at Object.matchDimensions (matchDimensions.js:7)
but i wrote

var myImg = document.createElement("img");
myImg.id = "inputImg";
myImg.style.cssText = "max-width: 800px; width: 800px;";
myImg.src = newImg;

Iit's a little part of my changes, if you want to help, we can connect in
skype
чт, 17 окт. 2019 г. в 05:31, Mark Adrian Estaca <notifications@github.com>:
