### ISSUE TITLE
DOMException (anonymous)

### ISSUE THREAD

**Issue by soyrandom** [justadudewhohacks/face-api.js#446]
i'm having this error with Google chrome, in opera it runs alright 
![image](https://user-images.githubusercontent.com/56101442/67244154-83008380-f42f-11e9-92ec-e217f672796e.png)
![image](https://user-images.githubusercontent.com/56101442/67244194-94499000-f42f-11e9-8f0b-a62c027460a6.png)

**Comment by justadudewhohacks** [comment]
Probably some issue with opening your webcam in opera. However this is not related to face-api.js.
