### ISSUE TITLE
How do i train the models for my own images

### ISSUE THREAD

**Issue by kumar88kanishk** [justadudewhohacks/face-api.js#447]
Hi THE Dude who hacks,

I see in the documentation mentioning this "The model is not limited to the set of faces used for training, meaning you can use it for face recognition of any person, for example yourself. You can determine the similarity of two arbitrary faces by comparing their face descriptors, for example by computing the euclidean distance or using any other classifier of your choice."

but no placeholder or caveat to be found with respect to training the models on my own images,
Please suggest/guide the path to be taken.

**Comment by justadudewhohacks** [comment]
> but no placeholder or caveat to be found with respect to training the models on my own images,

You do not train your own model. Check out the examples and tutorials first, these should answer your question.
