### ISSUE TITLE
Can I use face-api.js with ReactJS? 

### ISSUE THREAD

**Issue by thqueiroz** [justadudewhohacks/face-api.js#449]
I would like to run a web application using face-api as backend and ReactJS as frontend. It is possible?
Can someone help me?

**Comment by justadudewhohacks** [comment]
Yes, just google face-api.js react and some projects will pop up. There is even a tutorial on medium: https://towardsdatascience.com/facial-recognition-spa-for-bnk48-idol-group-using-react-and-face-api-js-ad62b43ec5b6
