### ISSUE TITLE
Issue loading: TypeError: Nt.makeTensor is not a function

### ISSUE THREAD

**Issue by luucv** [justadudewhohacks/face-api.js#455]
I just started and in the latest version I am getting the following error in the browser:

```
tf-core.esm.js:17 Uncaught (in promise) TypeError: Nt.makeTensor is not a function
    at Sn (tf-core.esm.js:17)
    at kn (tf-core.esm.js:17)
    at o (tf-core.esm.js:17)
    at Fh (tf-core.esm.js:17)
    at tf-core.esm.js:17
    at Array.forEach (<anonymous>)
    at tf-core.esm.js:17
    at Array.forEach (<anonymous>)
    at tf-core.esm.js:17
    at tf-core.esm.js:17
```

I installed `face-api.js` with `npm install face-api.js`. Now using it as follows:

```
import * as faceapi from 'face-api.js';

await faceapi.nets.tinyFaceDetector.loadFromUri('/models');
```

As soon as I try to load the model, I get the type error above. Any idea's where it is going wrong? I saw this https://github.com/tensorflow/tfjs/issues/2194#issuecomment-546187719 but couldn't see a solution to that. Thanks!

**Comment by hsparrow** [comment]
Hi, I just got the same error(tfjs-core@1.3.1) and I downgraded to tfjs-core@1.3.0, and this error disappeared, however, a new error rendered. Anyway, you could have a try.

**Comment by Spodeopieter** [comment]
When downgrading tfjs-core to 1.2.9 I get this error when trying to use the library

SsdMobilenetv1.js:26 Uncaught (in promise) Error: SsdMobilenetv1 - load model before inference
    at SsdMobilenetv1.forwardInput (SsdMobilenetv1.js:26)
    at SsdMobilenetv1.<anonymous> (SsdMobilenetv1.js:81)
    at step (tslib.es6.js:196)
    at Object.next (tslib.es6.js:127)
    at fulfilled (tslib.es6.js:80)

here is the lock file of a project where this library still works.

[yarnlockfile.txt](https://github.com/justadudewhohacks/face-api.js/files/3787177/yarnlockfile.txt)

**Comment by luucv** [comment]
@Spodeopieter, I think your last error has to do with not asynchronously loading in your model. Are you sure it is being loaded in correctly before you try to use it?

**Comment by Spodeopieter** [comment]
@luucv  this is how I am loading the models : 

`  loadModels = async () => {`
    `const MODEL_URL = "/models";`
   ` await faceapi.loadSsdMobilenetv1Model(MODEL_URL);`
   ` await faceapi.loadFaceLandmarkModel(MODEL_URL);`
   ` await faceapi.loadFaceRecognitionModel(MODEL_URL);`
 ` };`

**Comment by JackFy** [comment]
@luucv have the same error right now. I installed face-api.js via yarn. I retried it with npm install face-api.js adn it worked without any problem.
I'm using webpack-encore with Symfony.

**Comment by justlp** [comment]
Have the same problem.

Try to delete package-lock.json, node_modules. Then install the latest version (currently 0.21.0)

**Comment by justadudewhohacks** [comment]
The issue is most certainly due to your package managers installing a tfjs core version other than 1.2.9 (which is the one the latest face-api.js version uses). May be an issue with yarn?

Try deleting your yarn locks / package locks and do a clean installation. If for some reason the issue still remains, try explicitly installing `npm i @tensorflow/tfjs-core@1.2.9`.

**Comment by JackFy** [comment]
@justadudewhohacks Thanks for the Tip!
I've solved my problem :D

You do not just have to say `"@tensorflow/tfjs-core": "1.2.9"` in the dependencies-section of the package.json, you also have to prevent _tfjs-image-recognition-base_ from getting a newer version:

```
"resolutions": {
    "tfjs-image-recognition-base/@tensorflow/tfjs-core": "<=1.2.9"
}
```

**Comment by giuseppedev** [comment]
I've solved by taking these steps:

1.  delete tensorflow node module
2. `npm i @tensorflow/tfjs-node@1.2.9`
3. `npm i @tensorflow/tfjs-code@1.2.9`

The 1.2.9 is the last one supported by latest face-api.js version as @justadudewhohacks said.

**Comment by sudokzt** [comment]
I have same problem.

```
"@tensorflow/tfjs-core": "1.2.9",
"@tensorflow/tfjs-node": "1.2.9",
"face-api.js": "^0.21.0",
```

5 days ago, It was operating normally.

**Comment by Sxela** [comment]
> @justadudewhohacks Thanks for the Tip!
> I've solved my problem :D
> 
> You do not just have to say `"@tensorflow/tfjs-core": "1.2.9"` in the dependencies-section of the package.json, you also have to prevent _tfjs-image-recognition-base_ from getting a newer version:
> 
> ```
> "resolutions": {
>     "tfjs-image-recognition-base/@tensorflow/tfjs-core": "<=1.2.9"
> }
> ```

This helped. looks like `tfjs-image-recognition-base` was secretly installing the latest tfjs behind our backs.

**Comment by paulvales** [comment]
have same problem, resolutions no helped

**Comment by Spodeopieter** [comment]
installing face-api with npm instead of yarn seems to solve the problem for me.

**Comment by cmaycumber** [comment]
> installing face-api with npm instead of yarn seems to solve the problem for me.

I'm running into the same issue with yarn.

**Comment by SteveShaffer** [comment]
> looks like `tfjs-image-recognition-base` was secretly installing the latest tfjs behind our backs.

I added the `resolutions` section as suggested above and by [this help doc](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) but it was apparently ignored by yarn cuz it resolved to 1.3.1 anyway per yarn.lock.  I've got a yarn monorepo so I'm sure there's either some logical reason or some bug as to why that was the case.

I was able to get around it by **manually editing** the `yarn.lock` to change the section for `"@tensorflow/tfjs-core@^1.2.9":` to be identical to the section for `"@tensorflow/tfjs-core@1.2.9":` (no caret).  But that seems super hacky and tenuous.  If this is working in npm but not yarn that seems like a yarn bug to me.

**Comment by naveensky** [comment]
> I've solved by taking these steps:
> 
> 1. delete tensorflow node module
> 2. `npm i @tensorflow/tfjs-node@1.2.9`
> 3. `npm i @tensorflow/tfjs-code@1.2.9`
> 
> The 1.2.9 is the last one supported by latest face-api.js version as @justadudewhohacks said.

This solved the same issue I was having. Hope this helps somebody.

**Comment by JaeDukSeo** [comment]
So for me nothing worked what did work was this

**FOR YARN USERS**

1. add 
"resolutions": {
    "tfjs-image-recognition-base/@tensorflow/tfjs-core": "<=1.2.9"
}

2. in the package add these lines

  "dependencies": {
    "@tensorflow/tfjs-core": "1.2.9",
    "face-api.js": "^0.21.0",
    "next": "9.1.4",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-stickynode": "^2.1.1",
    "styled-components": "^4.4.1",
    "tfjs-image-recognition-base": "^0.6.2"
  }

actually installing tfjs-image-recognition-base worked!

**Comment by blazinaj** [comment]
I have this same issue. I get the error: 
![image](https://user-images.githubusercontent.com/39976117/69595561-c44afc80-0fb4-11ea-8a2a-4819275fe322.png)
when I try to load any model. 

I have the models in `public/models` and am trying to access them with 
```
 await faceapi.nets.ssdMobilenetv1.loadFromUri('/models') 
```
I've tried all the fixes mentioned above and I don't think it's an issue with versioning, or npm. 

Is there another way to load the models? Thanks!

**Comment by Foxyf76** [comment]
Also having the same issue, though my error message reads:

`engine_1.ENGINE.makeTensor is not a function`

**Comment by jjs-stripe** [comment]
We need to upgrade to TFJS 1.3.x for other reasons.  Any idea what's causing this problem with newer TFJS packages?  I don't see `makeTensor` anywhere in the code here or in `tfjs-image-recognition-base`

**Comment by hua1995116** [comment]
> I've solved by taking these steps:
> 
> 1. delete tensorflow node module
> 2. `npm i @tensorflow/tfjs-node@1.2.9`
> 3. `npm i @tensorflow/tfjs-code@1.2.9`
> 
> The 1.2.9 is the last one supported by latest face-api.js version as @justadudewhohacks said.

It solved my problem.

**Comment by justadudewhohacks** [comment]
I upgraded the tfjs-core version the latest release. Also I decided to move tfjs-image-recognition-base to face-api.js, so yarn should not have any reason to install different versions of tfjs-core anymore unless you or one if your dependencies is explicitly installing another version.

**Comment by MadalenaSousa** [comment]
I'm getting a "Kt.makeTensor is not a function", more specifically: 
Uncaught (in promise) TypeError: Kt.makeTensor is not a function
    at Rn (face-api.min.js:2426)
    at In (face-api.min.js:2407)
    at e (face-api.min.js:11444)
    at Vh (face-api.min.js:11445)
    at face-api.min.js:12054
    at Array.forEach (<anonymous>)
    at face-api.min.js:12053
    at Array.forEach (<anonymous>)
    at face-api.min.js:12047
    at face-api.min.js:103

I've tried all these resolutions and none of them worked. Could anyone help please?

**Comment by sj056** [comment]
> I'm getting a "Kt.makeTensor is not a function", more specifically:
> Uncaught (in promise) TypeError: Kt.makeTensor is not a function
> at Rn (face-api.min.js:2426)
> at In (face-api.min.js:2407)
> at e (face-api.min.js:11444)
> at Vh (face-api.min.js:11445)
> at face-api.min.js:12054
> at Array.forEach ()
> at face-api.min.js:12053
> at Array.forEach ()
> at face-api.min.js:12047
> at face-api.min.js:103
> 
> I've tried all these resolutions and none of them worked. Could anyone help please?

I'm facing the same problem. Is there any fix available for it?

**Comment by codmitu** [comment]
for me worked just to import tenserflow aswel, i had Lt.makeTensor is not a function
import * as faceapi from "face-api.js"
import '@tensorflow/tfjs-node';

**Comment by mohammednur1997** [comment]
@codmitu i face same problem as like you, do you have any solution for me ? 
i am also try add import '@tensorflow/tfjs-node';  
but still now workng

**Comment by codmitu** [comment]
@mohammednur1997 probably different version 
{
  "name": "....",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/core": "^7.18.10",
    "@babel/preset-env": "^7.18.10",
    "@date-io/date-fns": "^2.14.0",
    "@dipaktelangre/age-calculator": "^1.0.7",
    "@emotion/react": "^11.5.0",
    "@emotion/styled": "^11.3.0",
    "@mui/base": "^5.0.0-alpha.70",
    "@mui/core": "^5.0.0-alpha.54",
    "@mui/icons-material": "^5.4.2",
    "@mui/lab": "^5.0.0-alpha.92",
    "@mui/material": "^5.0.6",
    "@mui/styled-engine-sc": "^5.0.4",
    "@mui/styles": "^5.8.6",
    "@mui/system": "^5.8.6",
    "@mui/x-date-pickers": "^5.0.0-beta.3",
    "@reduxjs/toolkit": "^1.8.2",
    "@stripe/react-stripe-js": "^1.7.1",
    "@stripe/stripe-js": "^1.27.0",
    "@styled-icons/styled-icon": "^10.6.3",
    "@tensorflow/tfjs": "^3.19.0",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^17.0.45",
    "@types/react-qr-reader": "^2.1.4",
    "@types/styled-components": "^5.1.15",
    "assert": "^2.0.0",
    "axios": "^0.25.0",
    "console-browserify": "^1.2.0",
    "crypto-browserify": "^3.12.0",
    "date-fns": "^2.27.0",
    "face-api.js": "^0.22.2",
    "firebase": "^9.6.10",
    "framer-motion": "^4.1.17",
    "qrcode": "^1.5.0",
    "raw-loader": "^4.0.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-dropzone": "^12.1.0",
    "react-easy-crop": "^4.2.0",
    "react-firebase-hooks": "^5.0.3",
    "react-flip-move": "^3.0.4",
    "react-google-recaptcha": "^2.1.0",
    "react-intersection-observer": "^8.32.3",
    "react-qr-reader": "^3.0.0-beta-1",
    "react-redux": "^8.0.2",
    "react-router-dom": "^6.0.2",
    "react-scripts": "^5.0.1",
    "react-scroll": "^1.8.7",
    "react-swipeable-views": "^0.14.0",
    "react-swipeable-views-utils": "^0.14.0",
    "redux": "^4.2.0",
    "redux-thunk": "^2.4.1",
    "styled-components": "^5.3.3",
    "styled-icons": "^10.45.0",
    "typescript": "^4.7.4",
    "workbox-background-sync": "^6.5.3",
    "workbox-broadcast-update": "^6.5.3",
    "workbox-cacheable-response": "^6.5.3",
    "workbox-core": "^6.5.3",
    "workbox-expiration": "^6.5.3",
    "workbox-google-analytics": "^6.5.3",
    "workbox-navigation-preload": "^6.5.3",
    "workbox-precaching": "^6.5.3",
    "workbox-range-requests": "^6.5.3",
    "workbox-routing": "^6.5.3",
    "workbox-strategies": "^6.5.3",
    "workbox-streams": "^6.5.3"
  },
  "scripts": {
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build",
    "start": "react-scripts start",
    "build": "react-scripts build && react-compress",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/qrcode": "^1.4.2",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.5",
    "@types/react-google-recaptcha": "^2.1.5",
    "@types/react-redux": "^7.1.24",
    "@types/react-router": "^5.1.18",
    "@types/react-router-dom": "^5.3.3",
    "@types/react-scroll": "^1.8.3",
    "@types/react-swipeable-views": "^0.13.1",
    "@types/react-swipeable-views-utils": "^0.13.3",
    "@types/webpack-dev-server": "^4.7.2",
    "babel-loader": "^8.2.5",
    "css-loader": "^6.7.1",
    "envify": "^4.1.0",
    "html-loader": "^4.1.0",
    "react-compress": "^2.5.4",
    "style-loader": "^3.3.1",
    "terser": "^5.14.0",
    "terser-brunch": "^4.1.0",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.9.1",
    "uglifyify": "^5.0.0",
    "user-agent-data-types": "^0.2.0",
    "web-vitals": "^2.1.4",
    "webpack-cli": "^4.10.0",
    "webpack-dev-server": "^4.9.3"
  }
}
