### ISSUE TITLE
TypeError: st().registerTensor is not a function 

### ISSUE THREAD

**Issue by seta-duchuy** [justadudewhohacks/face-api.js#466]
![Screenshot from 2019-11-05 18-19-47](https://user-images.githubusercontent.com/53167951/68373125-cf102f80-0174-11ea-96ad-f9a59ba241c8.png)

I get this error while using `withFaceLandmarks()` . Many other functions like `detectSingleFace()` `detectAllFaces()` cause the same error if I use other models that are not `tinyFaceDetector`.
Can anyone help me ? Many thanks.

Here is my code:
```
    await faceapi.nets.tinyFaceDetector.loadFromUri(modelsUri);
    await faceapi.nets.faceLandmark68TinyNet.loadFromUri(modelsUri);
    const camera = new Camera({
      fps,
      onSnapshot: processImage,
    });
    const cameraSettings = await camera.start();

    async function processImage(image) {
      const face = await faceapi
                          .detectSingleFace(image, new faceapi.TinyFaceDetectorOptions({ inputSize, scoreThreshold }))
                          .withFaceLandmarks(true);
   }
```

**Comment by jtweaver** [comment]
I'm also seeing this issue. My setup is essentially the faceRecognition example to a T. I haven't been able to figure out what the problem is as of yet. Some help would be appreciated.

**Comment by billychasen** [comment]
Downgrading tfjs-core appears to fix it (via [this other issue](https://github.com/justadudewhohacks/face-api.js/issues/455#issuecomment-548987538) )

**Comment by justadudewhohacks** [comment]
Same issue as #455.
