### ISSUE TITLE
detecting emotions kill my  process.

### ISSUE THREAD

**Issue by Glunky** [justadudewhohacks/face-api.js#467]
Hi!
I have some troubles with face detecting. i`have written about issue [here](https://stackoverflow.com/questions/58738178/need-recomendation-about-code-because-it-kill-my-programm). I know that it is not your trouble(because i tested it without webrtc and all was great) but, please, may you can help me with that issue? If i dont detect face 
```
/*
detectEmotion().then(function(res) {
        emotion = res;
      });
*/
```
i dont have an error. So problem somewhere in my function, could you help please?

**Comment by punisher97** [comment]
I answer in stackoverflow, you r code have memory leak, please tell me if it working, i hope help you :)

**Comment by Glunky** [comment]
> I answer in stackoverflow, your code have memory leak, please tell me if it working, i hope help you :)

Yes, it works)) Thanks you a lot, you saved me)) It is funny that everything is solved in one line))
