### ISSUE TITLE
Wont load the shards just the manifest

### ISSUE THREAD

**Issue by joshatoutthink** [justadudewhohacks/face-api.js#468]
I'm trying to load the tinyFaceDetector and faceLandmark68TinyModel.  The manifests load just fine but I don't see the shards coming in.  In the console I'm getting an "Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0".

here is my code
```
import "./main.scss";
import * as FaceApi from "face-api.js";

window.addEventListener("load", function() {
  async function loadModels() {
    await Promise.all([
      FaceApi.nets.tinyFaceDetector.loadFromUri("/models/"),
      FaceApi.nets.faceLandmark68TinyNet.loadFromUri("/models/"),
    ]);
    const image = document.querySelector(".img");
    const detection = await FaceApi.detectSingleFace(
      image,
      new FaceApi.TinyFaceDetectorOptions()
    ).withFaceLandmarks;
    console.log(detection);
  }
  try {
    loadModels();
  } catch (e) {
    console.log(e);
  }
});
```

any help would be greatly appreciated
thanks!!

**Comment by idelburgo** [comment]
I would check:
1. the network tab at web inspector,  it should be doing two "fetch"
2. the JSON downloaded is complete and correct

I had a similar problem in which my framework was not loading non-extension files (as the shards)

**Comment by joshatoutthink** [comment]
Yeah Thanks,
That is what it ended up being, my bundler was not bundling the shards.

**Comment by sharonzhou** [comment]
How did you resolve the bundling issue and/or the non-extension issue (did you add .weights to the ext? That did not work for me..) Thanks!
