### ISSUE TITLE
how to train a image in faceapi.fetchImage with base64?

### ISSUE THREAD

**Issue by arifpermadi999** [justadudewhohacks/face-api.js#476]
i want to train a base64 image in faceapi.fetchImage but i get error from it , do you have a reference to solve it?
thank you

**Comment by anchitanc** [comment]
do you have solution for it ? i am also looking for same

**Comment by arifpermadi999** [comment]
> do you have solution for it ? i am also looking for same

actually  faceapi.fetchImage() will be generate a base64 source , so you can dirrectly put base64 in faceapi.fetchImage()
ex : 
let img = await faceapi.fetchImage(base64_image);
let detections = await faceapi.detectSingleFace(img).withFaceLandmarks().withFaceDescriptor();

you can check it through console.log

**Comment by arkumish** [comment]
Try this
for using base64 image in face-api.js

1. convert base64 to blob
2. convert blob to acceptable face api image format

```javascript
    const base64Response = await fetch(bas64ImageData);
    const blob = await base64Response.blob();
    const img = await faceapi.bufferToImage(blob);

    const detections = await faceapi.detectSingleFace(img, new faceapi.TinyFaceDetectorOptions());`
```

**Comment by ArchivistDevelopers** [comment]
> > do you have solution for it ? i am also looking for same
> 
> actually faceapi.fetchImage() will be generate a base64 source , so you can dirrectly put base64 in faceapi.fetchImage() ex : let img = await faceapi.fetchImage(base64_image); let detections = await faceapi.detectSingleFace(img).withFaceLandmarks().withFaceDescriptor();
> 
> you can check it through console.log

I got this error : 
ReferenceError: FileReader is not defined
    at \node_modules\face-api.js\build\commonjs\dom\bufferToImage.js:9:22
    at new Promise (<anonymous>)
    at Object.bufferToImage \node_modules\face-api.js\build\commonjs\dom\bufferToImage.js:5:12)
    at Module.<anonymous> (\node_modules\face-api.js\build\commonjs\dom\fetchImage.js:20:59)
    at step (\node_modules\tslib\tslib.js:141:27)
    at Object.next (\node_modules\tslib\tslib.js:122:57)
    at fulfilled (\node_modules\tslib\tslib.js:112:62)
sale
