### ISSUE TITLE
TensorFlow Synchronous processing on Node.js

### ISSUE THREAD

**Issue by noambonnie** [justadudewhohacks/face-api.js#499]
Per Tensorflow's documentation, the node.js implementation is synchronous and takes (https://www.tensorflow.org/js/guide/nodejs - Production considerations).

From looking at the code, it appears to me that no special action was taken in face-api to address this, meaning that the main thread will be blocking when running a face detection on Node JS. Am I correct in my understanding?

(We're using face-api on a web server to detect faces in uploaded images).

**Comment by justadudewhohacks** [comment]
> From looking at the code, it appears to me that no special action was taken in face-api to address this, meaning that the main thread will be blocking when running a face detection on Node JS. Am I correct in my understanding?

Correct, face-api.js doesn't touch any of the backend logic, it's only build on top of it.
