### ISSUE TITLE
SSD to tensorflowjs convertor

### ISSUE THREAD

**Issue by startupgurukul** [justadudewhohacks/face-api.js#50]
Hey Vincent, 

Can you enlighten me on how you converted the weights provided in https://github.com/yeephycho/tensorflow-face-detection to tfjs. I tried this but hit unsupported ops issue.                            

tensorflowjs_converter --input_format=tf_frozen_model  --output_node_names='concat,concat_1' frozen_inference_graph_face.pb output

Unsupported Ops in the model
Where, TopKV2, Assert, NonMaxSuppression

**Comment by justadudewhohacks** [comment]
Hi,

I didn't use the tensorflow.js converter, because at that time way more ops where not supported than the ones you mentioned. I extracted them with some own scripts.

**Comment by startupgurukul** [comment]
You are a rock star. Being able to get SSD to work when there are certain ops that aren't supported. It would be great if you can share them with the bigger community.  I am not sure how comfortable you would be to share the scripts. Can totally understand if you couldn't

**Comment by justadudewhohacks** [comment]
Thanks, but it might actually be easier than you think. You could simply load your graphdef with tf + python and then save the weight values to binary files with numpy and get their names and shape from the graph, to construct the manifest.json file.

I already commented on the [tfjs ssd_mobilenet issue](https://github.com/tensorflow/tfjs/issues/188), with how you could approach converting an ssd model to tfjs.

**Comment by startupgurukul** [comment]
Thank you for your response

**Comment by Sunwc0** [comment]
Can you share your scripts? I have the same questions that tfjs ops not supported,very thanks
