### ISSUE TITLE
face-api is incompatible with TFJS 1.3

### ISSUE THREAD

**Issue by jjs-stripe** [justadudewhohacks/face-api.js#500]
Using face-api with recent TensorflowJS builds results in an error when loading models.
See: https://github.com/justadudewhohacks/face-api.js/issues/455

We suspect this is because the saved models using by face-api are too old and need to be re-trained or re-exported to be compatible with new TFJS releases

**Comment by justadudewhohacks** [comment]
They dont need to be retrained, I upgraded tfjs-core to 1.4.0.
