### ISSUE TITLE
One face id for one face

### ISSUE THREAD

**Issue by mnatsakanyan** [justadudewhohacks/face-api.js#508]
Different ids are generated every time for one face id, is there a range for each face id, so that if it is in that range we can understand it is that face.

**Comment by lucasavila00** [comment]
I assume an embedding is being generated. (a multidimensional vector)
Then it's up to you to determine a distance ([euclidean](https://en.wikipedia.org/wiki/Euclidean_distance#n_dimensions), for example) in this space that would define being the same person or not (maybe if distance > 5 then it's not the same person) It's up to you to determine a good distance value based on the model being used and the distance function being used.

**Comment by mnatsakanyan** [comment]
thanks, I check and will write you

**Comment by mnatsakanyan** [comment]
> I assume an embedding is being generated. (a multidimensional vector)
> Then it's up to you to determine a distance ([euclidean](https://en.wikipedia.org/wiki/Euclidean_distance#n_dimensions), for example) in this space that would define being the same person or not (maybe if distance > 5 then it's not the same person) It's up to you to determine a good distance value based on the model being used and the distance function being used.

**Comment by mnatsakanyan** [comment]
I get this data  http://prntscr.com/qcduhu
What data or digits do I need to use to do that calculation

**Comment by lucasavila00** [comment]
The descriptor, I imagine.

**Comment by mnatsakanyan** [comment]
Hi ) how can we detect faces from afar?

**Comment by ldenoue** [comment]
Blaze face for tfjs works well for small faces in a video https://www.npmjs.com/package/@tensorflow-models/blazeface?linkId=80168838

**Comment by mnatsakanyan** [comment]
thanks.

**Comment by mnatsakanyan** [comment]
when I use this module I get this error, can you help me? 
tfjs-core:17 Uncaught (in promise) TypeError: Ot.makeTensor is not a function
