### ISSUE TITLE
mtcnn is deprecated and will be removed soon

### ISSUE THREAD

**Issue by rpolonsky** [justadudewhohacks/face-api.js#511]
Hey there!
Just interested why MTCNN is deprecated and what should we use instead?
Is there any topic to read or discussion about it?

MTCNN is described as fast and lightweight alternative to SSD Mobilenet v1 in your [great article](https://itnext.io/realtime-javascript-face-tracking-and-face-recognition-using-face-api-js-mtcnn-face-detector-d924dd8b5740) and that deprecation surprised me quite a lot :)

Thanks!

**Comment by justadudewhohacks** [comment]
The TinyFaceDetector should perform way better than MTCNN, the article is a bit out of date, sorry for that, I might update the article soon. MTCNN is more or less an artifact, which I do not want to maintain anymore. 

Furthermore I am working on bringing state of the art face detection to this project, which will still take some time however. Until then I would recommend to use the TinyFaceDetector.
