### ISSUE TITLE
Error: euclideanDistance: arr1.length !== arr2.length

### ISSUE THREAD

**Issue by adumbz** [justadudewhohacks/face-api.js#518]
While running video face recognition locally, I stored face vectors in browser localstorage by using JSON.stringify(), and when webcam starts, I convert all the JSON strings back into LabeledFaceDescriptors using the following code:

`var FINALVECTORS = []
    for (let i=0; i < localStorage.length ; i++) {
        var reVector = JSON.parse(window.localStorage.getItem(localStorage.key(i)))
        var LFD = new faceapi.LabeledFaceDescriptors(reVector['label'], [new Float32Array(reVector['descriptors'][0])])
        FINALVECTORS.push(LFD)`

following that, I pass the array FINALVECTORS into faceapi.FaceMatcher and start comparing:

`const faceMatcher = new faceapi.FaceMatcher(FINALVECTORS,0.5)
    var idVar = setInterval(async () => {
        console.log('start interval')
        const detections2 = await faceapi.detectSingleFace(video).withFaceLandmarks().withFaceDescriptor()
        if (detections2) {
            const results = faceMatcher.findBestMatch(detections2.descriptor) // error here
        }
`

Can't seem to find anything wrong, I am pretty sure the LabeledFaceDescriptor was instantiated correctly. Any help would be appreciated!

**Comment by fakob** [comment]
Maybe you have figured it out by now. For what its worth.
I remember an issue I had once which might be related. The size of localStorage is limited and varies from browser to browser. When I was storying too much data I experienced data loss. 
You could look into using the browsers indexedDB instead of localStorage. This might give you more space.

**Comment by Infinitay** [comment]
Double check the format of your `LabeledFacialDescriptors`. I had this error recently, and it turns out I was accidentally saving my facial descriptors as `{label: String, descriptors: [Object]}`, where `descriptors` was an array of objects, where the objects were results from
 ```js
await faceapi.detectAllFaces(image, faceapiOptions).withFaceLandmarks().withFaceDescriptors()[0].descriptor // note here, detecting all faces, pulling first
```
Instead of saving the descriptors as an array, or rather Float32Array.

How I solved the issue was instead of saving the descriptors as:
```js
{
    label: <label>,
    descriptors: <result-from-the-above-snippet>
}
```
I saved them properly as:
```js
new faceapi.LabeledFaceDescriptors(<label>, <result-from-the-above-snippet>).toJSON()
```

**Comment by adumbz** [comment]
I solved it after awhile but completely forgot how I did it, but anyway I am no longer working on this so I will close this issue, thanks for your replies though! Appreciate it @Infinitay @fakob

**Comment by prkhrv** [comment]
@adumbz  I am having the same issue can you please help me with it?

**Comment by adamozh** [comment]
@prkhrv Hi there, it's been too long since I last used this, I can't remember what I did to solve it! But I would think it was something like @Infinitay said above, maybe the format of the descriptor is wrong.

**Comment by alanine** [comment]
It may be because I use an old version, but I experienced this error when trying to use FaceMatcher.
I solved the problem by using something more straightforward. Here is a quick example for anyone else:

```
var first= faceapi.computeFaceDescriptor(input_1).then(data => { 
    var second = faceapi.computeFaceDescriptor(input_2).then(data => { 
         console.log(faceapi.euclideanDistance(first.descriptors[0], second.descriptors[0]));
  });
});

```

**Comment by nakataken** [comment]
> It may be because I use an old version, but I experienced this error when trying to use FaceMatcher. I solved the problem by using something more straightforward. Here is a quick example for anyone else:
> 
> ```
> var first= faceapi.computeFaceDescriptor(input_1).then(data => { 
>     var second = faceapi.computeFaceDescriptor(input_2).then(data => { 
>          console.log(faceapi.euclideanDistance(first.descriptors[0], second.descriptors[0]));
>   });
> });
> ```

I'm currently experiencing this error while using faceMatcher.findBestMatch(). Is your code also applicable to the findBestMatch() ?

**Comment by Harshit13777** [comment]
so reson is when you convert descriptor object which is in float 32 type in json and then parse it, the object which is in float32 will change to plain object which is creating erorr ;
here is answer:
when need to covert descriptor into json first
convert  descriptor(flaot32Array object ) into array(number[]) 
`let des=Array.from(img_descriptor)//convert float32Array into number[]`
then in json
`let jsondata=JSON.stringfy(des)`

when need parse it 
`let img_arr=JSON.parse(jsondata);`
`let descriptor =new float32Array(img_arr)
//convert it into float32 object from number[]`
`let facematcher =new faceapi.facemather('laber',[descriptor])`
