### ISSUE TITLE
How can I increase brightness and contrast in the webcam video stream before passing it to face api?

### ISSUE THREAD

**Issue by ShvedAction** [justadudewhohacks/face-api.js#528]
Hello, thank you for the convenient tool. 
Is it possible to do preprocessing like change brightness and contrast for video stream before doing detections? Will it help to improve the quality of detections? Can you give advice about how can I do this, and debug it?

Thank you for your help.

**Comment by justadudewhohacks** [comment]
> Will it help to improve the quality of detections?

Since I am training most of the models with data augmentation I think you will not get any significant benefit. But it's definitely possible to implement such preprocessing operations with tfjs in case you want to see whether it makes any difference.

**Comment by ShvedAction** [comment]
Thank you very much. I found the solution. It can be done using the TensorFlow function `tf.browser.fromPixels`. 

```
const gamma = 0.5
const tensor = tf.browser.fromPixels(video)
const sourceImg = tf.mul(tensor, tf.scalar(1/255))
const norm = tf.pow(sourceImg,  tf.scalar(gamma))
tf.browser.toPixels(norm, canvas)
```

Here is a full example https://jsfiddle.net/shvedaction/wcue6xmf/44/
