### ISSUE TITLE
Library Collision between face-api and posenet?

### ISSUE THREAD

**Issue by msj121** [justadudewhohacks/face-api.js#543]
My posenet code works, but when I add `import * as faceapi from 'face-api.js';` I start to get errors like:

> Error: Argument 'x' passed to 'pad' must be a Tensor or TensorLike, but got 'Tensor'
> convertToTensor — modules.js:108247
> pad_ — modules.js:95597
> f2 — modules.js:96538
> f2 — modules.js:96538
> (anonymous function) — modules.js:75986
> (anonymous function) — modules.js:10545
> scopedRun — modules.js:10555
> padAndResizeTo — modules.js:75984
> (anonymous function) — modules.js:75561
> step — modules.js:75414
> (anonymous function) — modules.js:75389
> initializePromise
> Promise
> (anonymous function) — modules.js:75385

Is there a way to have both of these libraries?

Thanks for any thoughts or help! I am using Meteor and this is running on my iphone. In a regular laptop browser it works fine. Very confused! Any advice to track this down?

**Comment by justadudewhohacks** [comment]
You have to make sure that you are using a posenet version, that utilizes the same tfjs-core version as face-api.js, or atleast make sure, that you are not ending up with 2 different versions of tfjs-core in your bundle.

**Comment by msj121** [comment]
Ok. Thanks!
