### ISSUE TITLE
How to speed it up after porting to node.js

### ISSUE THREAD

**Issue by land007** [justadudewhohacks/face-api.js#55]
I ported it to node.js to compare faces, but the operation was slow when extracting 128-dimensional feature vectors. I replaced the latest @ tensorflow/ tfjs and used require('@tensorflow/tfjs-node'), but it is not accelerated, it is still very slow, each method call below will wait 5-20 seconds, but in the browser can be faster, what can I do to speed it up?

            return tidy(function() {
                var batchTensor = input.toBatchTensor(150, true);
                var normalized = normalize(batchTensor);
                var out = convDown(normalized, params.conv32_down);
                out = maxPool(out, 3, 2, 'valid');
                out = residual(out, params.conv32_1);
                out = residual(out, params.conv32_2);
                out = residual(out, params.conv32_3);
                out = residualDown(out, params.conv64_down);
                out = residual(out, params.conv64_1);
                out = residual(out, params.conv64_2);
                out = residual(out, params.conv64_3);
                out = residualDown(out, params.conv128_down);
                out = residual(out, params.conv128_1);
                out = residual(out, params.conv128_2);
                out = residualDown(out, params.conv256_down);
                out = residual(out, params.conv256_1);
                out = residual(out, params.conv256_2);
                out = residualDown(out, params.conv256_down_out);
                var globalAvg = out.mean([1, 2]);
                var fullyConnected = matMul(globalAvg, params.fc);
                return fullyConnected;
            });

**Comment by justadudewhohacks** [comment]
Unfortunately, I have not played around with tfjs-node yet. But as I said in another issue already, unless you can get tfjs-node to run on your native gpu (I am not sure what the current state of tfjs-node is in that regards), I would suspect it to be very slow.

**Comment by land007** [comment]
I used the @tensorflow/tfjs-node to perform the multi-person detection of the posenet from the browser to the node.js, and the time to draw one frame was raised from about 2 seconds to 170-180 milliseconds.

**Comment by justadudewhohacks** [comment]
So running posenet in nodejs was faster or slower compared to browser?

**Comment by land007** [comment]
The posenet test speed node.js is 9-10 times higher than the browser. Just now, the faceapi euclideanDistance is speeded up by Node.js. The test results are as follows:

    	var begin = new Date().getTime();
    	const descriptor1 = await faceapi.computeFaceDescriptor(face1)//225px*225px
    	const descriptor2 = await faceapi.computeFaceDescriptor(face2)//252px*252px
    	const distance = faceapi.euclideanDistance(descriptor1, descriptor2)
    	console.log('distance='+distance);
    	if (distance < 0.6)
    	  console.log('match')
    	else
    	  console.log('no match')
    	var end = new Date().getTime();
    	console.log(end - begin);



browser：
distance=0.46667880224688196
match
2628

node.js:
distance=0.4666788574536108
match
1136

Although there is no speed improvement of posenet 9-10 times, but there is also a 2x improvement, only @tensorflow/tfjs-node is used for CPU acceleration.
Also I modified your embedded @tensorflow/tfjs because I tried to upgrade the embedded @tensorflow/tfjs multiple times and the result could not be accelerated by @tensorflow/tfjs-node.

**Comment by justadudewhohacks** [comment]
Interesting, did you set your backend in the browser to CPU or WebGL? 2628 ms for 2 forward passed through the recognition net is very slow.

**Comment by land007** [comment]
Thanks for your reminder, it is true that my browser does not have Open WebGL. What I want to say is that if you don't turn on acceleration in node.js, the result will be like this:

node.js:
distance=0.4666789108041152
match
432349

I haven't used your face-recognition.js yet, test it tomorrow, thank you for sharing such a good project on github.

**Comment by justadudewhohacks** [comment]
I see, thanks for the hint. Maybe I will also try to tinker around with tfjs-node a bit soon.

**Comment by zobis2** [comment]
heya , trying to port it aswell , land007 can you please help me a little bit?

**Comment by justadudewhohacks** [comment]
I played around with face-api.js + node.js a bit now and actually it seems that you don't need to port anything. You simply have to declare HTMLImageElement, HTMLCanvasElement and HTMLVideoElement in your node environment, for example `global.HTMLImageElement = class {}`.

I will look more into this and try to get better nodejs support into face-api.js soon, but right now you should already be able to use the package with nodejs.

**Comment by land007** [comment]
@zobis2 If you prefer, you can use "docker run -it --privileged --name tfjs-html land007/tfjs-html:latest bash" to pull the tensorflow.js image of node.js, which provides tfjs, canvas for node.js , ws, xmlhttprequest, node-fetch, mjpeg-server and other support, as justadudewhohacks said to simulate these objects in node.js, you can quickly port face-api.js to the node.js environment.

**Comment by land007** [comment]
Ok, I will test your new program and hope it will satisfy the video processing.

**Comment by masterulisses** [comment]
I'm also experiencing slowness problem when using faceRecognition on api-faces. I use windows and my tests are taking around three seconds to identify the face.
I already installed openblas on windows, but it looks like faces-api.js does not recognize it.
Sorry, you are requested to use face-recognition.js and this repository is saying This package is pretty much obsolete. I recommend you to switch to face-api.js.

Please help me, I'm loving this api.

**Comment by land007** [comment]
https://github.com/land007/face-kit
