### ISSUE TITLE
Improving the face alignment

### ISSUE THREAD

**Issue by seranus** [justadudewhohacks/face-api.js#57]
Currently I get some faces misaligned, the issue seems to be more with the ROI of the detector. Not completely sure in the end if its a detection or alignment model issue

![image](https://user-images.githubusercontent.com/590231/42971559-17537c32-8bad-11e8-92fd-6b7a0d1e2a44.png)

With changing the detection ROI we can get good results

![image](https://user-images.githubusercontent.com/590231/42971618-481461ce-8bad-11e8-84c0-a0fd1d77bfb2.png)

I'm looking how to get overall improvement up, maybe running mtcnn and SSD side by side. I'd rather do a bit slower detection then having users fix the ROI manualy

**Comment by justadudewhohacks** [comment]
The boxes drawn, are the bounding boxes returned from SSD? 

The 68 point landmark model we are using currently is not that accurate and could be improved, either by training an own model or looking for a pretrained model that grants better accuracy. At the moment the accuracy is sufficient to get a roughly aligned bounding box for the net computing the face descriptors.

**Comment by seranus** [comment]
First one is the SSD one the other is manual resizing to get good results

So I ended up messing around with bounding boxes. The alignment model can get good results but its very dependent on a good bounding box. 

I had much worse results with faces that are angled more than 75 degree, none of them had proper alignment set. It seems that alignment model likes the bounding box to start above eyes and a squared face. I'm currently testing making wider squared bounding boxes since ones generated by SSD are narrow.

Going to test 1adrianb and mtcnn later

**Comment by justadudewhohacks** [comment]
Anyways, I would rather have a model, that is agnostic to the face detector and which can predict the 68 face landmarks more precisely, independent of the bounding box.

I played around with retraining the landmark model a while ago actually and have some intermediate models, which seem to perform better already, but I didn't investigate further yet or validated them on a larger data set.

Does deep fakes require 68 face landmark points or simply a aligned bounding box by the way?

**Comment by seranus** [comment]
Current deep fake projects use a 68 face landmark to determine the face cutout, you need your input face to be the closest as possible to the one you used in training to get the best quality output. Here is an example, training input, faces are determined by a function based on landmarks
![image](https://user-images.githubusercontent.com/590231/43036700-9e051c68-8d06-11e8-8738-ea2890808dd4.png)

Also in post processing  you do a landmark cutout of the new outer part of the face to remove the background. That's something I'm missing from my site until I can get an openCVjs compilation with drawing.

Even the slight misalignment can be seen as flickers or jitters in a video, here's an example without manual fixing http://www.machine.tube/v/87 and this one doesn't even have hard align faces

**Comment by seranus** [comment]
I managed to figure it out. Since a face rotated to 90 or more won't get aligned anyways the box orientations doesn't matter. Lowering the bounding box to 15%-12% of the height and making it a box shape improved the aligner accuracy by a lot

Going to close the issue since it seems this is the best as it gets
