### ISSUE TITLE
how to create face matching on webcam

### ISSUE THREAD

**Issue by fuadkhalis** [justadudewhohacks/face-api.js#574]
I see on YouTube face matching can be done on a webcam https://www.youtube.com/watch?v=kcBi6AY96Dw, 

does anyone have the code
I need web verification using face
 please

**Comment by fuadkhalis** [comment]
i just made it

**Comment by idkidk-idk** [comment]
Hi, could you post your code? I am trying to makes face recognition system too and facing a lot of issues. It would be a great help! Thank you

**Comment by siddas27** [comment]
@idkidk-idk @fuadkhalis Can you share the link?

**Comment by baronrustamov** [comment]
@fuadkhalis please share your code thank you in advance
