### ISSUE TITLE
@tensorflow/tfjs-node: "This repository has been archived"

### ISSUE THREAD

**Issue by rubengt01** [justadudewhohacks/face-api.js#623]
Hi,
The instructions are recommending to install `@tensorflow/tfjs-node` but that repository is archived ([link](https://github.com/tensorflow/tfjs-node)) since Aug 2019. Should I use [tensorflow/tfjs](https://github.com/tensorflow/tfjs) instead?

Thanks

**Comment by morozovsk** [comment]
It seems you are confused.
Npm package [@tensorflow/tfjs-node](https://www.npmjs.com/package/@tensorflow/tfjs-node) already uses https://github.com/tensorflow/tfjs instead of https://github.com/tensorflow/tfjs-node

**Comment by rubengt01** [comment]
Ohh. It is confusing, thanks for pointing it out.
