### ISSUE TITLE
 Compute and compare the descriptors of two face images 

### ISSUE THREAD

**Issue by Hilina12** [justadudewhohacks/face-api.js#64]
Hi thank you a lot for your efforts, but i need some helps in the face recognition : my goal is to compare two face  images for that i compute the descriptor o each image and the euclidean Distance the same thing in the examples when i enter the same person and the same image it gives me 'match' but when  i enter for example different photographs of the same person the result is 'no match'  i really need to compare different photographs of the same person

**Comment by justadudewhohacks** [comment]
Can you append some screenshots for your example, that is not working? Also some code snippets would be helpful. Are you performing face detection and alignment?

**Comment by Hilina12** [comment]
yes of course !
first i detect the faces in the images than i compute their descriptors . this an example :
![capture1](https://user-images.githubusercontent.com/38425517/43686560-e7c25fae-98bf-11e8-93c3-ef4e63bb3bfd.PNG) and for the code i use this :

**Comment by justadudewhohacks** [comment]
Hmm it says match, or am I missing something. Also are you computing the face bounding box for the second image as well? `descriptor1 = await faceapi.computeFaceDescriptor(inputImgEl)` looks like you are passing the entire image and not the extracted face image.

You can also use `faceapi.allFaceMtcnn` to get the bounding boxes + descriptors, so you don't have to do everything on your own.

**Comment by Hilina12** [comment]
Hi again , you are right it's my fault you are right when i use `computeFaceDescriptor`  i pass the entire image that why it's give me error in matching !!!! thanks a lot :+1:

**Comment by Vishi234** [comment]
I have two base64 image and both image has a single face i want to compare both faces. can any one help men

**Comment by neerajrajput05** [comment]
Hi, 
 I am new in tensorflow js. I am working detect and recognized images between realtime web cam and stored in db.
Can any one Please suggest me from where i can start in react js.

I intgreated this **@tensorflow-models/blazeface** module
i am able to detect the faces in real time web cam.
i do not under stand how to convert image in tensor. 
now i am not able to understand what i do after that. 
I am very thankfull if any one help me.
