### ISSUE TITLE
Using landmark model and don't have the expected behavior

### ISSUE THREAD

**Issue by luiguild** [justadudewhohacks/face-api.js#65]
![image](https://user-images.githubusercontent.com/16566338/43789700-f7142d74-9a46-11e8-836e-0d0f9eacca7b.png)

What I'm doing wrong? I just change the example to landmark model and it´s apparently not working correctly. I'm running it on Windows/Firefox and Windows/Chrome.

**Comment by justadudewhohacks** [comment]
You have to feed the landmark model an image of a face, e.g. just the extracted image from the bounding box, not the entire image.
