### ISSUE TITLE
faceapi.nets is undefined

### ISSUE THREAD

**Issue by jzauderer** [justadudewhohacks/face-api.js#665]
I'm trying to start a new project using face-api.js, and I've run into an issue while awaiting faceapi.nets.tinyFaceDetector.

```javascript
import * as faceapi from '../node_modules/face-api.js/dist/face-api.js';

const video = document.getElementById('video');

async function run(){
    console.log(faceapi);
    console.log(faceapi.nets);
    await Promise.all([
        faceapi.nets.tinyFaceDetector.loadFromUri('/models'),
        faceapi.nets.faceLandmark68Net.loadFromUri('/models'),
        faceapi.nets.faceRecognitionNet.loadFromUri('/models'),
        faceapi.nets.faceExpressionNet.loadFromUri('/models')
    ]);
}

run();;
```

The HTML is as follows:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Webcam Test</title>
    <script defer src="./node_modules/face-api.js/dist/face-api.min.js"></script>
    <script defer type="module" src="scripts/script.js"></script>
    <link rel="stylesheet" href="index.css">
    <link rel="shortcut icon" href="#" />
</head>
<body>
    <video id="video" width="720" height="560" autoplay muted></video>
</body>
</html>
```

The error I'm getting
![image](https://user-images.githubusercontent.com/28771760/87985923-6a9ac380-caaa-11ea-933d-a372a7cbf2f8.png)

I'm not sure why nets isn't getting defined until after the page has loaded and the error has happened. I've also manually called faceapi and faceapi.nets afterwards to make sure it loaded properly. Does anyone know why this might be happening?

**Comment by jzauderer** [comment]
Figured it out, I had the server set up improperly

**Comment by Marsisgod** [comment]
How are you solve ,I run this in Nginx server and it show me that"Uncaught ReferenceError: faceapi is not defined
    <anonymous> http://121.43.119.154:81/js/script.js:7"

**Comment by Marsisgod** [comment]
How are you solve ,I run this in Nginx server and it show me that"Uncaught ReferenceError: faceapi is not defined
    <anonymous> http://121.43.119.154:81/js/script.js:7"
