### ISSUE TITLE
Error installing example

### ISSUE THREAD

**Issue by hmartiins** [justadudewhohacks/face-api.js#666]
#### I followed the README.md step by step, even with the node and the updated npm, I was returned with the following error:

![image](https://user-images.githubusercontent.com/51277667/88124396-63a3ac00-cba3-11ea-9850-73fb5254970c.png)
![image](https://user-images.githubusercontent.com/51277667/88124409-69998d00-cba3-11ea-8e23-f04fd4207c9c.png)
![image](https://user-images.githubusercontent.com/51277667/88124416-73bb8b80-cba3-11ea-93ac-444759eab3ce.png)

**Comment by karthik-Gopalan** [comment]
From what I can see, you seem to be in the wrong directory when you are running the scripts. Are you trying to run the examples? In which case you need to traverse to the right dir 
face-api.js->examples-> 
examples browser folder for browser based examples. Example-node for node js examples. And then you do an npm install. 
Hope this helps.

**Comment by hmartiins** [comment]
OMG that was it, thank you, and forgiveness for the lack of attention on my part
