### ISSUE TITLE
 Uncaught (in promise) Error: failed to fetch: (404) Not Found, from url: http://localhost:8601/face-api.js/models/ssd_mobilenetv1_model-weights_manifest.json

### ISSUE THREAD

**Issue by naveen-robotixedu** [justadudewhohacks/face-api.js#673]
Tried using Face-api.js in a web based application, For now we have the models folder in nodemodules/face-api.js/models. but we get the above error. May i know which is the right place to have the models folder?
This is the code used.
const { Canvas, Image, ImageData } = canvas
	faceapi.env.monkeyPatch({ Canvas, Image, ImageData })
	
	console.log(faceapi.nets);
 (async () => {
	await faceapi.nets.ssdMobilenetv1.loadFromUri('face-api.js/models');
	
	const detections = await faceapi.detectAllFaces(this.video);
	console.log("face found ");
	console.log(detections);
	
})();
    let media = navigator.mediaDevices.getUserMedia({
      video: true,
      audio: false
    });

    media.then((stream) => {
      this.video.srcObject = stream;
    });

**Comment by sharonzhou** [comment]
What did you figure out here @naveen-robotixedu? Dealing with a similar issue... Thanks! (I'm not using express backend)

**Comment by naveen-robotixedu** [comment]
> What did you figure out here @naveen-robotixedu? Dealing with a similar issue... Thanks! (I'm not using express backend)

Created a build folder for the website and just placed the models folder in the build folder

**Comment by reynaldoayala062** [comment]
wow you just saved my life. I was stressing the fu&^ out
