### ISSUE TITLE
Support Loading models from external sources

### ISSUE THREAD

**Issue by bmaguireibm** [justadudewhohacks/face-api.js#68]
The Current Implementation does not support loading of models from sources other than the current domain. 
This could be a useful feature as it could allow for loading of models from cdns or directly from a cloud object storage instance. 

I have implemented the required change [here](https://github.com/bmaguireibm/face-api.js), let me know if this is desired feature and I can create a PR.

P.S.
Thanks for the excellent library.

**Comment by justadudewhohacks** [comment]
Hi,

Sure that would be awesome, if you could create a PR for that. Thank you!

**Comment by bmaguireibm** [comment]
Great. I've created the PR [here](https://github.com/justadudewhohacks/face-api.js/pull/69).

**Comment by justadudewhohacks** [comment]
Your changes are published in version 0.10.1.
