### ISSUE TITLE
Question: Are the face descriptors generated compatible with dlib-generated face descriptors?

### ISSUE THREAD

**Issue by ndtreviv** [justadudewhohacks/face-api.js#706]
Here's what I want to achieve:

I have a corpus of dlib face descriptors. 

I want to:
1. take an image that was previously processed by dlib
2. extract a face using face-api.js
3. still get true positive results when querying the dlib-generated data with the face-api.js descriptors.

Is that possible?

**Comment by josiahbryan** [comment]
Have you tried it? 

The face descriptors here are 128-item float arrays - don't know what dlib does. Guessing the chances of them being from the same underlying network model are slim, sorry. But ymmv...

**Comment by ndtreviv** [comment]
Yes, I think it depends largely on the model. I ended up going with a fork of this repo that resolves a ton of problems I was having. I think because the colour models used between node and java are different, then the floats produced are potentially slightly different as well? Not to mention different platforms and their float precision differences and endianness.
In the end, though, I don't think the differences weren't enough to prevent a match.

**Comment by josiahbryan** [comment]
What fork did you use? I might want to check it out myself

**Comment by ndtreviv** [comment]
> What fork did you use? I might want to check it out myself

https://github.com/vladmandic/face-api
