### ISSUE TITLE
Loading models in Angular

### ISSUE THREAD

**Issue by guilhermeaugustog** [justadudewhohacks/face-api.js#722]
I'm trying to load the "models" downloaded in my project, it compiles but showing this following error in console: 
![image](https://user-images.githubusercontent.com/43259638/98045958-183aa400-1e08-11eb-80c8-c34a6ee607d5.png)

All examples I have found are in Vanilla or Node.js, so I have  doubts if I'm loading the models in right place of Angular class, the current code of class is: 

`  
@ViewChild('videoPlayer') videoplayer : HTMLVideoElement;  
async ngOnInit() {
    Promise.all([
      await faceapi.nets.tinyFaceDetector.loadFromUri('./models'),
      await faceapi.nets.faceLandmark68Net.loadFromUri('./models'),
      await faceapi.nets.faceRecognitionNet.loadFromUri('./models'),
      await faceapi.nets.faceExpressionNet.loadFromUri('./models')
    ]).then(() => {
      this.startVideo();
    })
  }

  async startCanvas(){
    // const canvas = faceapi.createCanvasFromMedia(this.videoplayer);
    
    setInterval(async () => {
      const detections = await faceapi.detectAllFaces(this.videoplayer, 
        new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceExpressions();
        console.log(detections);
    }, 100)
  }

  startVideo(){
    navigator.getUserMedia(
      { video: {} },
      stream => {
        this.videoplayer.srcObject = stream;
      },
      err => console.error(err)
    );

  }`

Current path of "models" folder:

![image](https://user-images.githubusercontent.com/43259638/98046459-04437200-1e09-11eb-9f6c-be2e0b98e6eb.png)

Am I putting the models in a wrong place or I should to change where my code load the "models" in page?

**Comment by AneudysOrtiz** [comment]
Hello, try moving the models folder to **assets**.

![image](https://user-images.githubusercontent.com/25928891/98683328-473aa380-233b-11eb-9a33-58c79479df99.png)

**Comment by thelionleo** [comment]
I have no idea how to implement this in angular. can you please share github of working code in angular?

**Comment by guilhermeaugustog** [comment]
@thelionleo take a look in a project named "projeto-tcc" in my profile, I did the implementation for Angular, just configure and access localhost:800/tests to see the results

**Comment by guilhermeaugustog** [comment]
> Hello, try moving the models folder to **assets**.
> 
> ![image](https://user-images.githubusercontent.com/25928891/98683328-473aa380-233b-11eb-9a33-58c79479df99.png)

I did the changes as you sugested, I had to make other changes to models loading correctly, for example, instead of calling the model loaders on init and inside a Promise.all(), I have to load them inside a async function and call it in ngAfterViewInit().
If someone have difficult to load the plugin in project, see "projeto-tcc" in my profile, it's not finished yet but is possible to see this plugin working in tests page.

**Comment by thelionleo** [comment]
> @thelionleo take a look in a project named "projeto-tcc" in my profile, I did the implementation for Angular, just configure and access localhost:800/tests to see the results

there's too much happening there.  is it an implementation of face-api? would it be too much to ask if you can create a new github for me for angular? just the basics to get me started.

**Comment by imrushi** [comment]
@thelionleo Here is my [repo](https://github.com/imrushi/face-api-js-angular) I have implemented the Face-api.js in angular. I hope this will help you.
