### ISSUE TITLE
Unhandled Rejection (Error): 'multiply' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen

### ISSUE THREAD

**Issue by shailjaa** [justadudewhohacks/face-api.js#723]
I keep getting this error while using TinyFaceDetector for face detection. 
I am using another tfjs model as well so it is conflicting.

![Screenshot (6)](https://user-images.githubusercontent.com/62165403/98072218-8a080180-1e8b-11eb-9491-5cb358075390.png)

**Comment by archeelp** [comment]
> I keep getting this error while using TinyFaceDetector for face detection.
> I am using another tfjs model as well so it is conflicting.
> 
> ![Screenshot (6)](https://user-images.githubusercontent.com/62165403/98072218-8a080180-1e8b-11eb-9491-5cb358075390.png)

This issue is alredy raised here [https://github.com/justadudewhohacks/face-api.js/issues/719#issue-733674343](url)
@shailjaa please raise your concerns there and mark this as duplicate.
