### ISSUE TITLE
Uncaught TypeError: Cannot read property 'loadFromUri' of undefined

### ISSUE THREAD

**Issue by Tros-t** [justadudewhohacks/face-api.js#735]
So I was just doing this youtube tutorial about face detection but in my scripts file I get an error.

`const video = document.getElementById('video')

Promise.all([
    faceapi.nets.tnyFaceDetector.loadFromUri('/model'),
    faceapi.nets.faceLandmark68Net.loadFromUri('/model'),
    faceapi.nets.faceRecognitionNet.loadFromUri('/model'),
    faceapi.nets.faceExpressionNet.loadFromUri('/model')

])

function startVideo() {
    navigator.getUserMedia(
        { video: {} },

        stream => video.srcObject = stream,
        err => console.error(err)
    )
}

startVideo()`

the Error:

`Uncaught TypeError: Cannot read property 'loadFromUri' of undefined
    at script.js:5`

Kindly help me, I am stuck

**Comment by treedbox** [comment]
You have a typo: replace **tnyFaceDetector** with **tinyFaceDetector**

**Comment by Tros-t** [comment]
Thanks I fixed that but now I get another error after typing the full code.

The error on the console:

`face-api.min.js:1 Fetch API cannot load file:///C:/models/tiny_face_detector_model-weights_manifest.json. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
lp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
hp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
vp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
t.loadFromUri @ face-api.min.js:1
(anonymous) @ script.js:4
face-api.min.js:1 Fetch API cannot load file:///C:/models/face_landmark_68_model-weights_manifest.json. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
lp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
hp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
vp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
t.loadFromUri @ face-api.min.js:1
(anonymous) @ script.js:5
face-api.min.js:1 Fetch API cannot load file:///C:/models/face_recognition_model-weights_manifest.json. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
lp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
hp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
vp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
t.loadFromUri @ face-api.min.js:1
(anonymous) @ script.js:6
face-api.min.js:1 Fetch API cannot load file:///C:/models/face_expression_model-weights_manifest.json. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
lp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
hp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
vp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
t.loadFromUri @ face-api.min.js:1
(anonymous) @ script.js:7
face-api.min.js:1 Uncaught (in promise) TypeError: Failed to fetch
    at face-api.min.js:1
    at face-api.min.js:1
    at Object.next (face-api.min.js:1)
    at face-api.min.js:1
    at new Promise (<anonymous>)
    at p (face-api.min.js:1)
    at lp (face-api.min.js:1)
    at face-api.min.js:1
    at face-api.min.js:1
    at Object.next (face-api.min.js:1)
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
lp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
hp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
vp @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
(anonymous) @ face-api.min.js:1
p @ face-api.min.js:1
t.loadFromUri @ face-api.min.js:1
(anonymous) @ script.js:4
Promise.then (async)
(anonymous) @ script.js:8`

The code in my JS file:

`const video = document.getElementById('video')

Promise.all([
  faceapi.nets.tinyFaceDetector.loadFromUri('/models'),
  faceapi.nets.faceLandmark68Net.loadFromUri('/models'),
  faceapi.nets.faceRecognitionNet.loadFromUri('/models'),
  faceapi.nets.faceExpressionNet.loadFromUri('/models')
]).then(startVideo)

function startVideo() {
  navigator.getUserMedia(
    { video: {} },
    stream => video.srcObject = stream,
    err => console.error(err)
  )
}

video.addEventListener('play', () => {
  const canvas = faceapi.createCanvasFromMedia(video)
  document.body.append(canvas)
  const displaySize = { width: video.width, height: video.height }
  faceapi.matchDimensions(canvas, displaySize)
  setInterval(async () => {
    const detections = await faceapi.detectAllFaces(video, new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceExpressions()
    const resizedDetections = faceapi.resizeResults(detections, displaySize)
    canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height)
    faceapi.draw.drawDetections(canvas, resizedDetections)
    faceapi.draw.drawFaceLandmarks(canvas, resizedDetections)
    faceapi.draw.drawFaceExpressions(canvas, resizedDetections)
  }, 100)
})`

And thanks again @treedbox

**Comment by Tros-t** [comment]
Oh solved it,

I was using some other extension to open my .html file in browser and know I used the live server extension and it solved for me.

Thanks @treedbox

**Comment by varuas-1** [comment]
Hey there 
I was also using the code 

const video = document.getElementById("video");

Promise.all([
  faceapi.nets.tinyFaceDectector.loadFromUri("/models"),
  faceapi.nets.faceLandmark68Net.loadFromUri("/models"),
  faceapi.nets.faceRecognitionNet.loadFromUri("/models"),
  faceapi.nets.faceExpressionNet.loadFromUri("/models"),
]).then(startVideo);

function startVideo() {
  navigator.getUserMedia(
    { video: {} },
    (stream) => (video.srcObject = stream),
    (err) => console.error(err)
  );
}

video.addEventListener("play", () => {
  //   console.log("dfdf");
  setInterval(async () => {
    const detections = await faceapi
      .detectAllFaces(video, new faceapi.TinyFaceDectectorOptions())
      .withFaceLandmarks()
      .withFaceExpressions();
    console.log(detections);
  }, 100);
});


and here the =>
(loadFromUri )   is not working 
compiler is giving the below mentioned error
Cannot read properties of undefined (reading 'loadFromUri')


HOW COULD I FIX THIS

**Comment by neha93995** [comment]
hello, I
 have errors on this line 
script.js:6 Uncaught TypeError: Cannot read properties of undefined (reading 'loadFromUri')

const video = document.getElementById('vid');


faceapi.nets.ssdMobilenetv1.loadFromUri('/weights'); //error
faceapi.nets.faceLandmark68Net.loadFromUri('/weights');//error
faceapi.nets.facerecognitionNet.loadFromUri('/weights');//error


console.log(video);
function startWebcam(){
    navigator.mediaDevices.getUserMedia(
        {
            video:true,
            audio:false
        }).then((stream)=>{
            video.srcObject = stream;
        }).catch((err)=>{
            console.error(err)
        })
}

startWebcam();

**Comment by Sivanesanbalu** [comment]
script.js:26 Uncaught TypeError: Cannot read properties of undefined (reading 'loadFromUri')
what kind of problem there some help for me .

**Comment by Ayush022005** [comment]
I am getting error here please help
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
  Promise.all([
    faceapi.nets.tinyFaceDetector.loadFromUri('./models'),
    faceapi.nets.faceLandmark68Net.loadFromUri('./models'),
    faceapi.nets.faceRecognitionNet.loadFromUri('./models'),
    faceapi.nets.ssdMobilenetv1.loadFromUri('./models')
  ]).then(() => {
  // Your code to run after models are loaded
  console.log('Models loaded successfully!');
});
  </script>
</body>
</html>
