### ISSUE TITLE
Use face expression model on hidden video feed

### ISSUE THREAD

**Issue by hamza-bentahar** [justadudewhohacks/face-api.js#750]
Hello,

Just found out about this awesome repo, and I'm having a great time using the face expressions API. Maybe because I was smiling too much (for the testing). 

Anyway, In my app, I want to check if the user is smiling but without displaying the camera video on the screen.
For now, I can check if the user is smiling or not with a pretty good accuracy, but the video has to be on my screen.

How can I remove the video from the screen?

Here is the js code:
```
<video id="video" width="500" height="500" autoplay muted ></video>

async startVideo() {
      let stream = null;
      try {
        stream = await navigator.mediaDevices.getUserMedia({
          audio: false,
          video: { width: 1280, height: 720 },
        });
        this.video.srcObject = stream;
      } catch (e) {
        console.log(e);
      }
    },

this.video = document.getElementById('video');
    Promise.all([
      faceapi.nets.tinyFaceDetector.loadFromUri('/models'),
      faceapi.nets.faceExpressionNet.loadFromUri('/models'),
    ]).then(this.startVideo);
    this.video.addEventListener('play', () => {
      console.log('video started');
      setInterval(async () => {
        const detections = await faceapi.detectAllFaces(
          this.video,
          new faceapi.TinyFaceDetectorOptions(),
        ).withFaceExpressions();
        detections.forEach((detection) => {
          if (detection.expressions.happy >= 0.7) {
            this.isHappy = true;
          } else {
            this.isHappy = false;
          }
        });
      }, 100);
    });
```
The app is in vue.js, so I only took the parts that matter.

Your help is greatly appreciated.
Cheers,

**Comment by vladmandic** [comment]
video element does not have to rendered to work, just add style="display: none" to the video tag.

**Comment by sudarshan-parvatikar** [comment]
You can hide the video by setting the `style="display: none;"`  of the video. The video tag then becomes: 
```
<video id="video" width="500" height="500" style="display: none;" autoplay muted ></video>
```
or using JS:
```
var vid = document.createElement("video"); 
vid.setAttribute('id', 'video');
vid.setAttribute('autoplay', 'muted');
document.body.appendChild(vid);
document.getElementById("video").style.display = "none";
```

**Comment by hamza-bentahar** [comment]
Thank you so much @vladmandic  and @sudarshan-parvatikar ! 
I had of course tried to use "display: none;" but it doesn't work somehow. Could it be due to vue.js and its virtual dom?

Anyway, I created the element in javascript as suggested by @sudarshan-parvatikar, and it works! I still don't know why it works this way and not the other, but I'm glad it does. Thanks again guys, you are awesome!

**Comment by vladmandic** [comment]
Most likely it is Vue that is avoiding placing element with display:none, but can't do that when it's added programmatically via JS.

Best way to determine what is Vue doing is to open inspector in browser and see which elements are present on the page.

**Comment by sudarshan-parvatikar** [comment]
@hamza-bentahar glad it worked out. I suggest trying out @vladmandic 's recommendation as I don't know Vue and I use that snippet in Vanilla JS . Also, if your issue is solved, I'd suggest closing this issue.
