### ISSUE TITLE
How to use quantized as Float32Arrays

### ISSUE THREAD

**Issue by dmastag** [justadudewhohacks/face-api.js#76]
I noticed that the weight files are missing since the model weights have been quantized,
Does this mean that we now should use the shards if we want to load the weights as a Float32Arrays?

How would the following code then work?

```
// using fetch
const res = await fetch('/models/face_detection_model.weights')
const weights = new Float32Array(await res.arrayBuffer())
net.load(weights)

// using axios
const res = await axios.get('/models/face_detection_model.weights', { responseType: 'arraybuffer' })
const weights = new Float32Array(res.data)
net.load(weights)
```

**Comment by justadudewhohacks** [comment]
You cannot pass quantized as Float32Arrays to net.load, because dequantization requires meta data, such as `scale `and `min` for each tensor. Why do you want to load quantized weights as Float32Array in the first place?

**Comment by dmastag** [comment]
Because the uncompressed weights have been removed in this repo, so I though that if I want to use http/axios then that would be the way to go.

How would I then use this like that?

**Comment by justadudewhohacks** [comment]
If you want to load quantized weights simply use net.load('uri'). This downloads the weights using fetch and then dequantizes the weights (this step is just a call to tfjs-core actually).

May I ask, why you want to use axios for that?

By the way, if for some reason you still want to use the weights without quantization, you can still download them from [face-api.js-models](https://github.com/justadudewhohacks/face-api.js-models/tree/master/uncompressed).

**Comment by justadudewhohacks** [comment]
Closing here now, since question should be answered.
