### ISSUE TITLE
Where are the models?

### ISSUE THREAD

**Issue by geuis** [justadudewhohacks/face-api.js#760]
Installed via npm, `npm install face-api.js`. In the resulting `/node_modules/face-api.js` directory there's no models or weights directory. The instructions in the readme don't indicate what the proper way to get the models is.

**Comment by imrushi** [comment]
Hi @geuis, you can clone the Face-api.js repo and copy the weights directory in this you will get all the weights (models). if you got it then close the issue.

**Comment by vladmandic** [comment]
...or use the newer fork, `npm install @vladmandic/face-api`
