### ISSUE TITLE
How to get detected frame when input is <video> tag

### ISSUE THREAD

**Issue by SuperSuperNero** [justadudewhohacks/face-api.js#763]
Hello,

I'm working on a project that detects human face in some specific angles in real-time and when everything are correct, it captures that frame.
I'm able to get media stream from camera of the device and fetch in HTML video tag. I have tried two options below:
1. Capturing frames continuously from video tag (by using opencv.js) and process that frames by face-api.js. The processing time of each frame is very slow on low performance devices.
2. Using video tag as input of face-api.js directly. The processing time of each frame is acceptable. 
I decided to choose the second option. However, I don't know how to get exactly the frame of input video tag that had been processed by face-api.js to return detection results.
If I capture frame from video before face-api.js processes that video. The frame will be lagging when comparing with detection results.

Thanks.

**Comment by vladmandic** [comment]
blindly capturing video frame takes ~2ms, so it's not really a slow operation - and you definitely don't need opencv.js for that.  
now, actually reading `imagedata` from a frame easily takes ~20ms - i guess that's what opencv.js does and thats why its slow.  

do this once:
```js
const video = document.getElementById('your-video-id');
const canvas = document.createElement('canvas');
canvas.width = video.videoWidth;
canvas.height = video.videoHeight;
const ctx = canvas.getContext('2d');
```

and then redraw each frame and pass canvas object to face-api instead of passing HTMLVideoElement:
```js
ctx.drawImage(video, 0, 0, video.videoWidth, video.videoHeight, 0, 0, canvas.width, canvas.height);
faceapi.detectAllFaces(canvas, ...);
```

it's even faster with `gl` context, but quite a lot more complex.

**Comment by SuperSuperNero** [comment]
Thank you very much for your comment.
I need to do some pre/post-processing by using opencv.js. That why I need opencv.js for capturing frames.
I don't know that face-api.js accepts HTML canvas tag as input (My bad for don't read the document carefully). So I do a redundant conversion image data from canvas to img tag (to pass img tag to face-api :D). This conversion is heavy part.
Now, I can capture frame by using opencv.js, do some pre-processing, drawing frame to canvas and pass the canvas to face-api. It works without any problems.
On the other hand, do you think that face-api should return processing frame along detection results when passing video as input?
Because I think that, in almost cases, in the end, frame is what we need, detection results just helps us decide which is correct frame to take.

**Comment by vladmandic** [comment]
> On the other hand, do you think that face-api should return processing frame along detection results when passing video as input?
> Because I think that, in almost cases, in the end, frame is what we need, detection results just helps us decide which is correct frame to take.

What you're asking for, I do in my own library. But `face-api.js` doesn't process input - it passes it as-is to `tfjs` which converts it to tensor. No reason why `face-api.js` wouldn't include that tensor in the output structure.

Btw, not exactly what you want, but there is a helper function that can be used to convert processed tensors back to canvas, either for full image or for regions - `extractFaces`.

**Comment by SuperSuperNero** [comment]
Haha, sorry. Please don't mind. I just want to share my thought to improve this project.
Thank you very much for your help.
I will close this issue.

**Comment by vladmandic** [comment]
you can create a feature request in my updated port <https://github.com/vladmandic/face-api>
