### ISSUE TITLE
Can we use the trained weights with python?

### ISSUE THREAD

**Issue by Picocu** [justadudewhohacks/face-api.js#777]

**Comment by vladmandic** [comment]
face-api does not use prebuild models, they are implemented in tfjs inside face-api itself.  
so weights are only that - weights. you'd need to recreate models manually in python.

or use alternative prebuilt models that have same functionality, for example take a look at <https://github.com/vladmandic/human/wiki/Models>

of course, you'd need to implement output parsing yourself - for some models it's trivial and for some not so much.

**Comment by Picocu** [comment]
Thanks @vladmandic
