### ISSUE TITLE
Webp support on node

### ISSUE THREAD

**Issue by Xetera** [justadudewhohacks/face-api.js#779]
Currently based on node-canvas's arbitrary restrictions, it's not possible to use an optimized image format like webp when doing face recognition. There are some workarounds I've looked at that claim they work with webp like https://github.com/node-gfx/image but because face-api has checks on things like the `Image` constructor with `image instanceof Image` this separate library isn't usable.

My best guess for this then would be converting webp to a tensor instead of a canvas. I looked around and found https://www.tensorflow.org/io/api_docs/python/tfio/image/decode_webp but of course that's available in the python api and not node. Whats the correct way to deal with this? I don't want to deoptimize my images if possible but right now it's looking like that's the only reasonable way to do things.

**Comment by vladmandic** [comment]
seems that `@canvas/image` package supports `webp` via `@cwasm/webp`  
and it does have a `getImageData` method  

so load the image and convert it to tensor in a correct format

```js
const imageData = canvas.getImageData(0, 0, canvas.width, canvas.height);
const tensor = tf.tidy(() => {
  const data = tf.tensor(Array.from(imageData.data), [canvas.height, canvas.width, 4], 'int32'); // create rgba image tensor from flat array
  const channels = tf.split(data, 4, 2); // split rgba to channels
  const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
  const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
  return reshape;
});
```

**Comment by Xetera** [comment]
I'm confused where I would use this, it seems like this is for serializing a canvas with an image into a webp output but I'm looking for the opposite to get a webp buffer into a canvas I can use for face recognition.
```ts
const image = await imageFromBuffer(webpBuffer);

const detections = await faceapi
  .detectAllFaces(image)
  .withFaceDescriptors();
```
I figured that what I was originally not passing in the custom `Image` into 
```ts
import { Image } from "@canvas/image"
import { Canvas, ImageData } from "canvas"
faceapi.env.monkeyPatch({ Image, Canvas, ImageData })
```
But canvas still doesn't recognize it as a correct `Image` format (`TypeError: Image or Canvas expected`) which could be an issue with `node-canvas` and not faceapi https://github.com/Automattic/node-canvas/issues/1258

Sorry if my question wasn't clear.

**Comment by vladmandic** [comment]
what i wrote is `webp` (assuming it's already loaded) to `tensor` - and you can just pass that tensor to `face-api`

```js
const detections = await faceapi.detectAllFaces(tensor).withFaceDescriptors();
```

and to load `webp` image, it's `canvas.src = 'some-path.webp'` and then execute everything else in `canvas.onload` event  
(`canvas` here is instance of `@canvas/image`, not `canvas`)

pretty sure `monkeyPatch` is not even necessary in that case at all, could be just to make `face-api` happy with a defined object, but it's pretty much completely unused

**Comment by vladmandic** [comment]
end-to-end, just a prototype from the head, didn't test
```js
const fs = require('fs');
const tf = require('@tensorflow/tfjs-node');
const image = require('@canvas/image');
const faceapi = require('@vladmandic/face-api');

const data = fs.readFileSync('image.png');
const canvas = await image.imageFromBuffer(data);
const imageData = canvas.getImageData(0, 0, canvas.width, canvas.height);
const tensor = tf.tidy(() => {
  const data = tf.tensor(Array.from(imageData.data), [canvas.height, canvas.width, 4], 'int32'); // create rgba image tensor from flat array
  const channels = tf.split(data, 4, 2); // split rgba to channels
  const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
  const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
  return reshape;
});
const detections = await faceapi
  .detectAllFaces(tensor)
  .withFaceDescriptors();
```

**Comment by vladmandic** [comment]
end-to-end, just tried and works fine without the need for `canvas` or `monkeyPatch`  

```js
const fs = require('fs');
const tf = require('@tensorflow/tfjs-node');
const image = require('@canvas/image');
const faceapi = require('@vladmandic/faceapi');

const modelPath = 'model/';
const imageFile = 'demo/sample1.webp';
const ssdOptions = { minConfidence: 0.1, maxResults: 10 };

async function main() {
  await faceapi.nets.ssdMobilenetv1.loadFromDisk(modelPath);
  const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions);

  const buffer = fs.readFileSync(imageFile);
  const canvas = await image.imageFromBuffer(buffer);
  const imageData = image.getImageData(canvas);
  console.log('image:', imageFile, canvas.width, canvas.height);

  const tensor = tf.tidy(() => {
    const data = tf.tensor(Array.from(imageData.data), [canvas.height, canvas.width, 4], 'int32'); // create rgba image tensor from flat array
    const channels = tf.split(data, 4, 2); // split rgba to channels
    const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
    const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
    return reshape;
  });
  console.log('tensor:', tensor.shape, tensor.size);

  const result = await faceapi.detectAllFaces(tensor, optionsSSDMobileNet)
  console.log('results:', result);
}

main();
```

**Comment by Xetera** [comment]
I wasn't using your fork of face-api but I decided to give it a shot because I had `@tensorflow/tfjs-node` pinned to `1.7.4` because of face-api compatibility issues. I tried this using the following code
```ts
import * as tf from "@tensorflow/tfjs-node";
import { getImageData, imageFromBuffer } from "@canvas/image";
import * as faceapi from "@vladmandic/face-api";
import {
  WithFaceDescriptor,
  WithFaceLandmarks,
  FaceDetection,
} from "@vladmandic/face-api";

export async function detectFaces(buf: Buffer): Promise<Detection> {
  const canvas = await imageFromBuffer(buf);
  const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options({
    minConfidence: 0.1,
    maxResults: 10,
  });

  const imageData = getImageData(canvas);
  if (!imageData) {
    throw Error("No image data found");
  }

  const tensor = tf.tidy(() => {
    const data = tf.tensor(
      Array.from(imageData.data),
      [canvas.height, canvas.width, 4],
      "int32"
    ); // create rgba image tensor from flat array
    const channels = tf.split(data, 4, 2); // split rgba to channels
    const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
    const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
    return reshape;
  });
  console.log("tensor:", tensor.shape, tensor.size);

  const detections = await faceapi
    .detectAllFaces(tensor, optionsSSDMobileNet)
    .withFaceLandmarks()
    .withFaceDescriptors();
  return detections;
}
```
But I'm running into `TypeError: forwardFunc is not a function`. I tried clearing `node_modules` and making sure `tfjs` and `tfjs-node` versions are matching
```
    "@canvas/image": "^1.0.1",
    "@tensorflow/tfjs": "3.3.0",
    "@tensorflow/tfjs-node": "3.3.0",
    "@vladmandic/face-api": "1.1.12",
    "canvas": "2.7.0",
```
I tried to also set `tf.setBackend('cpu')` explicitly as per https://github.com/tensorflow/tfjs/issues/3883 but that didn't seem to change the error either.

Starting to wonder if wastefully converting the image back to jpeg is a better approach at this point haha

**Comment by vladmandic** [comment]
i tried your code (mostly) as-is and it works:

just had to add actual model loading:
```js
  const modelPath = 'node_modules/@vladmandic/face-api/model/';
  await faceapi.nets.ssdMobilenetv1.loadFromDisk(modelPath);
  await faceapi.nets.faceLandmark68Net.loadFromDisk(modelPath);
  await faceapi.nets.faceRecognitionNet.loadFromDisk(modelPath);
```

and then just invoked it at the end with
```js
const buf = fs.readFileSync('test.webp');
detectFaces(buf);
```

so question is how are you compiling/bundling this (as it's a ts syntax)?
i've tried with
```shell
tsc src/test.ts --outDir dist/
```
and 
```shell
esbuild --bundle --format=cjs --platform=node --external:@tensorflow --target=es2018 src/test.ts >dist/test.js
```
and both work fine

also, check if you get a sane output from
```js
  console.log(faceapi.version, tf.version.tfjs, faceapi.tf.version.tfjs, faceapi.tf.getBackend());
```

**Comment by Xetera** [comment]
Ahh, I didn't realize I was running the `monkeyPatch` method which broke tensorflow somehow, seems like it's working now! Thank you so much for taking the time to look into this 🙏 much appreciated.

**Comment by vladmandic** [comment]
You're welcome 😁
