### ISSUE TITLE
faceapi is not defined 

### ISSUE THREAD

**Issue by vishaldhull09** [justadudewhohacks/face-api.js#797]
const pkg = require("../package.json")
const BASE_URL = process.env.BLUR_SRC || `https://unpkg.com/${pkg.name}/src`;
let loadModel = false;
let faceapi: any

const loadScript = (src: string) => {
  return new Promise(function (resolve, reject) {
    const s = document.createElement('script');
    s.src = src;
    s.onload = resolve;
    s.onerror = reject;
    document.head.appendChild(s);
  });
};

const loadfile = async () => {
  console.log("load script");
  console.log(`${BASE_URL}/models/face-api.min.js`)
  await loadScript(`${BASE_URL}/models/face-api.min.js`);
  console.log("check");
  loadModels();
}

const loadModels = async () => {
  console.log(faceapi);
  console.log(faceapi.nets);
  await faceapi.nets.tinyFaceDetector.loadFromUri('/models');
  console.log("check2");   
}

**Uncaught (in promise) TypeError: Cannot read property 'nets' of undefined**

**Comment by vladmandic** [comment]
first, what is this code? require is not a browser function.  
and post more complete output, not just promise rejection.  

anyhow, at the very least, you need `script.async=false` or `onload` may trigger too early.  
but even then, *loaded* is not the same as *complete* (for *iife* scripts that means executed and registered in global namespace), you should also check for `readyState`. it's close, but not exact. dynamically loading iife scripts is not a great thing to do in general.
