### ISSUE TITLE
Version of NodeJS for face-api?

### ISSUE THREAD

**Issue by amit0shakya** [justadudewhohacks/face-api.js#798]
Hi I have installed Node version 16 it throws some method depreciated issue of tensorflow but It works well in Node 8.12.0, Is someone know what is the max version of Node I can use for this..?

**Comment by vladmandic** [comment]
this original version of `face-api` has not been updated in over a year, so no wonder there are issues with latest node.
try newer port of `face-api` which works with both new versions of tfjs, typescript and nodejs (yes, nodejs 16 is tested):
<https://github.com/vladmandic/face-api>
