### ISSUE TITLE
Same code, different results (0.11.0/0.12.0)

### ISSUE THREAD

**Issue by jrdev128** [justadudewhohacks/face-api.js#81]
Hi,

I was locating faces with SSD Mobile Net (faceapi.locateFaces) because with other nets (MTCNN, Tiny Yolo v2) the result was unstable. Now I updated the library from 0.11.0 to 0.12.0 version and same code produces different results. At 0.11.0 version faceapi.locateFaces was stable but with 0.12.0 version is unstable (like MTCNN, Tiny Yolo v2 at 0.11.0).

Greetings and thanks for the repository.

**Comment by justadudewhohacks** [comment]
Hmm, I couldn't notice any difference regarding ssd mobilenet . Can you upload a picture to show me what kind of differences you are seeing?

The only real difference between 0.11.0 and 0.12.0 is, that I upgraded tfjs-core from 0.11.9 to 0.12.14.

**Comment by justadudewhohacks** [comment]
If this is still an issue with the recent versions feel free to reopen, giving atleast one example showing the issue.
