### ISSUE TITLE
findBestMatch algoritym

### ISSUE THREAD

**Issue by danies8** [justadudewhohacks/face-api.js#818]
Hi,
`const bestMatchPerson = faceMatcher.findBestMatch(singleResult.descriptor)`
I would like to understand how `findBestMatch  `is working behind the screen ?
Thanks,

**Comment by vladmandic** [comment]
its simply a loop that runs calculates euclidean distance for all descriptors and returns entry with the lowest distance

**Comment by danies8** [comment]
Thanks-:)

**Comment by danies8** [comment]
If I compare face with face in DB that are not same, when will I get results of unknown , and when exist label with the lowest
distance?

**Comment by vladmandic** [comment]
I think that would be obvious by now. If not, how about you check? Sorry.

**Comment by danies8** [comment]
Now is ok :)
