### ISSUE TITLE
Bug - TypeError: Cannot read property 'descriptor' of undefined

### ISSUE THREAD

**Issue by danies8** [justadudewhohacks/face-api.js#822]
Hi,
I `register `this picture to DB:
![amy5](https://user-images.githubusercontent.com/1079689/134693120-a0d29ebe-f5be-46c0-a0a5-69a0ad2794b5.png)
when I `compare `with this picture and  with itself  it done successfully.
![amy4](https://user-images.githubusercontent.com/1079689/134693230-c5fb342e-b015-4d38-8f11-17e7c77ab914.png)
But when I `compare `to these pictures I got `TypeError: Cannot read property 'descriptor' of undefined`
![amy1](https://user-images.githubusercontent.com/1079689/134693501-29adf716-18d1-4bc2-9e97-96ad7f77ab44.jpeg)
![amy3](https://user-images.githubusercontent.com/1079689/134693525-b3291c9f-b6ae-4167-bb82-a7ba4d39455f.png)

Why ? the same faces

**Comment by vladmandic** [comment]
error says it all `TypeError: Cannot read property 'descriptor' of undefined`  

meaning that face was never detected to start with, so descriptor for it doesn't exist. you cannot just assume that face detection will find face on every input image and that descriptor is valid. do some checks before blindly passing parameters.

**Comment by danies8** [comment]
Fixed, Thanks a lot:)
