### ISSUE TITLE
Bug-UnhandledPromiseRejectionWarning - OOM when allocating tensor with shape[1,256,256,64]

### ISSUE THREAD

**Issue by danies8** [justadudewhohacks/face-api.js#824]
Hi,
I tried to insert 10000 record to DB in loop using this link and got this error after 300 records.
https://github.com/vladmandic/face-api/blob/master/demo/node-image.js
```
2021-09-24 23:59:17.493963: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at cwise_ops_common.h:128 : Resource exhausted: OOM when allocating tensor with shape[1,256,256,64] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
(node:21876) UnhandledPromiseRejectionWarning: Error: Invalid TF_Status: 8
Message: OOM when allocating tensor with shape[1,256,256,64] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
    at Object.<anonymous> (<anonymous>)
```

**Comment by danies8** [comment]
In production I will have same problem ? What can I do ?
This the relevant code:
```
 const tensor = tf.tidy(() => { // create tensor from image data
    const data = tf.tensor(Array.from(imageData?.data || []), [canvas.height, canvas.width, 4], 'int32'); // create rgba image tensor from flat array and flip to height x width
    const channels = tf.split(data, 4, 2); // split rgba to channels
    const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
    const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
    return reshape;
  });
```

**Comment by vladmandic** [comment]
you're using explicit functionality from <https://github.com/vladmandic/face-api>  
so create issues there.

tensor should never have shape `[1,256,256,64]` (and that is massive, thus OOM), it should be `[1,width,height,4]`. which means that your input `imageData` is somehow corrupt before it reaches this part. cant know for sure if i don't know how it was created up to that point.

**Comment by danies8** [comment]
This my code, what wrong with it ?
//https://github.com/vladmandic/face-api/blob/master/demo/node-image.js
  ```
register = async (id, imageStrEncodedBase64) => {

    try {

      utils.logger.log({
        level: 'info',
        message: `register: Start register id:${id}`,
        label: 'faceRecognition.ts'
      });

      // 1.Save image  to disk
      let filename = id + ".jpeg";
      const currentDate = dateTime.getCurrentDate();
      const baseDir = path.resolve("D:\\images\\", currentDate);
      if (!fs.existsSync(baseDir)) {
        fs.mkdirSync(baseDir)
      }
      let imagePath = path.join(baseDir, filename);
      let base64Data = imageStrEncodedBase64.replace(/^data:image\/\w+;base64,/, '');
      fs.writeFile(imagePath, base64Data, 'base64',
        function (err, data) {
          if (err) {
            utils.logger.log({
              level: 'error',
              message: `register: ${err}`,
              label: 'faceRecognition.ts'
            });
          }
          utils.logger.log({
            level: 'info',
            message: `register: ${"Success to saved image " + filename + " to " + imagePath}`,
            label: 'faceRecognition.ts'
          });
        });


      // 2.Load models
      faceapi.env.monkeyPatch({ Canvas: canvas.Canvas, Image: canvas.Image, ImageData: canvas.ImageData });
      const faceDetectionNet = new faceapi.FaceDetectionNet();
      const modelPath = '../../node_modules/@vladmandic/face-api/model';
      await faceDetectionNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.ssdMobilenetv1.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.ageGenderNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceLandmark68Net.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceRecognitionNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceExpressionNet.loadFromDisk(path.join(__dirname, modelPath));

      utils.logger.log({
        level: 'info',
        message: `register: Load models done successfully"`,
        label: 'faceRecognition.ts'
      });


      // 3. Create image data
      const buffer = fs.readFileSync(imagePath); // read image from disk
      const canvasObj = await image.imageFromBuffer(buffer); // decode to canvas
      const imageData = image.getImageData(canvasObj); // read decoded image data from canvas
      utils.logger.log({
        level: 'info',
        message: `register: Create image data done successfully(image path:${imagePath}, width:${canvasObj.width}, height:${canvasObj.height}`,
        label: 'faceRecognition.ts'
      });

      // 4. Create tensor and detect all faces
      const tensor = tf.tidy(() => { // create tensor from image data
        const data = tf.tensor(Array.from(imageData.data || []), [canvasObj.height, canvasObj.width, 4], 'int32'); // create rgba image tensor from flat array and flip to height x width
        const channels = tf.split(data, 4, 2); // split rgba to channels
        const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
        const reshape = tf.reshape(rgb, [1, canvasObj.height, canvasObj.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
        return reshape;
      });
      utils.logger.log({
        level: 'info',
        message: `register: Create tensor done successfully(tensor shape:${tensor.shape}, tensor size:${tensor.size}`,
        label: 'faceRecognition.ts'
      });

      // 5. Detect all faces
      const ssdOptions = { minConfidence: 0.1, maxResults: 10 };
      const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions);
      const faces = await faceapi
        .detectAllFaces(tensor, optionsSSDMobileNet)
        .withFaceLandmarks()
        .withFaceExpressions()
        .withFaceDescriptors()
        .withAgeAndGender();
      utils.logger.log({
        level: 'info',
        message: `register: Detect all faces done successfully`,
        label: 'faceRecognition.ts'
      });

```

**Comment by vladmandic** [comment]
At least two major things
- you're writing to file and not waiting for write to complete before later reading it. Use writeFileSync
- you're recreating faceapi class and reloading weights on each image. Not only extremely costly, but likely will cause issues sooner or later. 

On a major note, for diagnostics learn to check your interim results before posting issue. E.g., what is your canvasObj.width and height? Is it even valid. What about imageData? Etc. 

And for production, *always* check if any interim output is valid before passing it on to next function. You're basically running blind and when error happens, you don't know where it all started.

**Comment by vladmandic** [comment]
And a major suggestion - since you don't need canvas to draw anything, so how about avoid using it completely. Take a look at another demo that does native JPG decoding to tensor directly and without external library.

**Comment by vladmandic** [comment]
And why are you writing to file and then reading it back when you already have buffer in memory.

There is sooo much wrong with this.

**Comment by danies8** [comment]
> And why are you writing to file and then reading it back when you already have buffer in memory.
> 
> There is sooo much wrong with this.

I need to keep this file for other system to show this file.

**Comment by danies8** [comment]
> * you're recreating faceapi class and reloading weights on each image. Not only extremely costly, but likely will cause issues sooner or later.

How I can avoid it ?

**Comment by vladmandic** [comment]
A) you can keep it, but you don't have to re-read it immediately.
B) how can you avoid recreating and reloading weights? By doing that during app startup and keeping it. That's as basic as it gets. Entire section 2 should be once per app, not once per image.

**Comment by danies8** [comment]
> On a major note, for diagnostics learn to check your interim results before posting issue. E.g., what is your canvasObj.width and height? Is it even valid. What about imageData? Etc.
> 
> And for production, _always_ check if any interim output is valid before passing it on to next function. You're basically running blind and when error happens, you don't know where it all started.

Fixed:)

**Comment by danies8** [comment]
> A) you can keep it, but you don't have to re-read it immediately.
> B) how can you avoid recreating and reloading weights? By doing that during app startup and keeping it. That's as basic as it gets. Entire section 2 should be once per app, not once per image.

Only pass Entire section 2  to startup, where i keep it ? can you show me how?

**Comment by danies8** [comment]
Called like that that all or I need to keep it somewhere ? 

```
app.listen(config.serverPort, async () => {
            logger.log({
                level: 'info',
                message: `Server start listening at port:${config.serverPort}`,
                label: 'app.js'
            });
              // 2.Load models
      faceapi.env.monkeyPatch({ Canvas: canvas.Canvas, Image: canvas.Image, ImageData: canvas.ImageData });
      const faceDetectionNet = new faceapi.FaceDetectionNet();
      const modelPath = '../../node_modules/@vladmandic/face-api/model';
      await faceDetectionNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.ssdMobilenetv1.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.ageGenderNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceLandmark68Net.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceRecognitionNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceExpressionNet.loadFromDisk(path.join(__dirname, modelPath));
        })
 
```

**Comment by vladmandic** [comment]
No, NOT like this.
And I can't show you how. That is basic app state management for JavaScript. I don't want to write the app for you, learn basics. From now on, I'll only reply to specific questions regarding Faceapi and only if diagnostics info has been provided, not just code copy&paste.

**Comment by danies8** [comment]
Sorry I understood you now.To create  this file and to called it from startup and from each register or compare? is it
```
const tf = require('@tensorflow/tfjs-node');
const path = require('path');
const canvas = require('canvas');
const faceapi = require('@vladmandic/face-api');

async function loadModals() {
      faceapi.env.monkeyPatch({ Canvas: canvas.Canvas, Image: canvas.Image, ImageData: canvas.ImageData });
      const faceDetectionNet = new faceapi.FaceDetectionNet();
      const modelPath = '../../node_modules/@vladmandic/face-api/model';
      await faceDetectionNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.ssdMobilenetv1.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.ageGenderNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceLandmark68Net.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceRecognitionNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceExpressionNet.loadFromDisk(path.join(__dirname, modelPath));
}
module.exports = { loadModals}
```

and called it from start up:
app.listen(config.serverPort, async () => {
          //.Load models
  await  loadModals();
}
and same from register and compare .

**Comment by danies8** [comment]
> And a major suggestion - since you don't need canvas to draw anything, so how about avoid using it completely. Take a look at another demo that does native JPG decoding to tensor directly and without external library.

Which demo ? I looked on your demo and didn't see- please provide a link:)

**Comment by vladmandic** [comment]
A) No. Take a step back and think. Look what is CONSTANT vs what is CHANGING and should be inside `register`. In your case, `optionsSSDMobileNet` that gets created in step 5 should really be part of step 2 and entire step 2 should be be placed somewhere where its executed ONCE on app startup. Only thing that matters is that `optionsSSDMobileNet` is visible from within `register` method so it can be used from there. DO NOT RECREATE IT FOR EVERY IMAGE.

B) You did not look. Function is even marked with comments:
> // read image from a file and create tensor to be used by faceapi
> // this way we don't need any monkey patches

Next time when you have  a question, step back  
Think about it and research it a bit  
Search for solutions before posting issues on GitHub  
Post issues in a correct repository  
GitHub Issues is for issues, not for learning how to code - Only if its an issue, then post  
Youre close of being blocked

**Comment by danies8** [comment]
Hi,
Thank a lot for your answers.
It is very appreciated here :)
I fixed all your remarks, and run again the app from vs code with 1000 and after 827 inserts it crash better than before 300 inserts. I insert **same** image every time.
You said:
tensor should never have shape [1,32,32,512] (and that is massive, thus OOM), it should be [1,width,height,4]. which means that your input imageData is somehow corrupt before it reaches this part. cant know for sure if i don't know how it was created up to that point.
> 
> > 26/09/2021 07:51:15:647 faceRecognition.ts - info : register: Create tensor done successfully(tensor shape:1,403,716,3, tensor size:865644
> > 2021-09-26 07:51:15.809551: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at cwise_ops_common.h:128 : Resource exhausted: OOM when allocating tensor with shape[1,32,32,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
> > (node:12320) UnhandledPromiseRejectionWarning: Error: Invalid TF_Status: 8
> > Message: OOM when allocating tensor with shape[1,32,32,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
> >     at Object.<anonymous> (<anonymous>)

![image](https://user-images.githubusercontent.com/1079689/134794241-8d080f92-a3b2-48e2-adde-f327859555fa.png)

**Comment by vladmandic** [comment]
no actual information provided.

**Comment by danies8** [comment]
I used this code to register new faces into DB:https://github.com/vladmandic/face-api/blob/master/demo/node-image.js
My installed ram is 16,GB , window 10 ,
Processor: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz   2.71 GHz.
I used `node-cashe` to keep the descriptors.

**Comment by vladmandic** [comment]
a) you DON'T USE my code - don't just provide link to it!!! you have your own code based on my code. so provide that.
b) there is no diagnostic info provided that i mentioned several times before! what are interim states of variables. LOG!!!

**Comment by danies8** [comment]
Thanks for answer.
Error:
40
```
26/09/2021 19:37:18:635 faceRecognition.ts - info : register: Create tensor done successfully(tensor shape:1,240,135,3, tensor size:97200
2021-09-26 19:37:18.796932: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at cwise_ops_common.h:128 : Resource exhausted: OOM when allocating tensor with shape[1,32,32,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
(node:21292) UnhandledPromiseRejectionWarning: Error: Invalid TF_Status: 8
Message: OOM when allocating tensor with shape[1,32,32,512] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
    at Object.<anonymous> (<anonymous>)
```

 ```
// 3. Create image data
      const buffer = fs.readFileSync(imagePath); // read image from disk
      if(!buffer){
        let bufferMessage = "register: Read image from disk failed";
        utils.logger.log({
          level: 'error',
          message: bufferMessage,
          label: 'faceRecognition.ts'
        });
        return { success: false, error:bufferMessage }
      }
      const canvasObj = await image.imageFromBuffer(buffer); // decode to canvas
      if(!buffer){
        let  decodedtoCanvasMessage = "register:Decode to canvas failed";
        utils.logger.log({
          level: 'error',
          message: decodedtoCanvasMessage,
          label: 'faceRecognition.ts'
        });
        return { success: false, error:decodedtoCanvasMessage }
      }
      const imageData = image.getImageData(canvasObj); // read decoded image data from canvas
      if(!imageData){
        let createImageDataMessage = "register: Create image data failed";
        utils.logger.log({
          level: 'error',
          message: createImageDataMessage,
          label: 'faceRecognition.ts'
        });
        return { success: false, error:createImageDataMessage }
      }

      utils.logger.log({
        level: 'info',
        message: `register: Create image data done successfully(image path:${imagePath}, width:${canvasObj.width}, height:${canvasObj.height}`,
        label: 'faceRecognition.ts'
      });

      // 4. Create tensor 
      const tensor = tf.tidy(() => { // create tensor from image data
        const data = tf.tensor(Array.from(imageData.data || []), [canvasObj.height, canvasObj.width, 4], 'int32'); // create rgba image tensor from flat array and flip to height x width
        const channels = tf.split(data, 4, 2); // split rgba to channels
        const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
        const reshape = tf.reshape(rgb, [1, canvasObj.height, canvasObj.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
        return reshape;
      });
      if(!tensor){
        let createTensorMessage = "register: Create tensor image failed";
        utils.logger.log({
          level: 'error',
          message: createTensorMessage,
          label: 'faceRecognition.ts'
        });
        return { success: false, error:createTensorMessage }
      }
      utils.logger.log({
        level: 'info',
        message: `register: Create tensor done successfully(tensor shape:${tensor.shape}, tensor size:${tensor.size}`,
        label: 'faceRecognition.ts'
      });

      // 5. Detect all faces
      // minConfidence determines if face is face at all during detection. 
      // If detected face is below that level, it will not be analyzed at all
      // and you don't get things like descriptor as a result.
      const ssdOptions = { minConfidence: 0.1, maxResults: 10 };
      const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions);
      const faces = await faceapi
        .detectAllFaces(tensor, optionsSSDMobileNet)
        .withFaceLandmarks()
        .withFaceExpressions()
        .withFaceDescriptors()
        .withAgeAndGender(); // failed here
      utils.logger.log({
        level: 'info',
        message: `register: Detect all faces done successfully`,
        label: 'faceRecognition.ts'
      });
      if(faces.length === 0){
        let detectAllFacesMessage = "register: detect all faces didn't generate a face";
        utils.logger.log({
          level: 'error',
          message: detectAllFacesMessage,
          label: 'faceRecognition.ts'
        });
        return { success: false, error:detectAllFacesMessage }
      }
```

**Comment by vladmandic** [comment]
STILL NO DIAG OUTPUT - LOG YOUR OPERATIONS. sorry for yelling, but i've said this how many times so far?
What are the values of `tensor` or `imageData`
And what is method `image.getImageData`? It's not here. 
Post full code on **GIST** not inline in issue as it's impossible to track after a while.
And post LOG there as well.

And when reporting error, execute as simply as possible. You're noting that `VSCode` runs out of memory. 
Don't - it impacts how NodeJS performs garbage collection. Make sure this error is reproducible from NodeJS directly.

**Comment by danies8** [comment]
1.Logs:
26/09/2021 19:37:18:616 faceRecognition.ts - info : register: Load models done successfully
26/09/2021 19:37:18:620 faceRecognition.ts - info : register: Create image data done successfully(image path:D:\images\2021.09.26\12838.jpeg, width:135, height:240
26/09/2021 19:37:18:635 faceRecognition.ts - info : register: Create tensor done successfully(tensor shape:1,240,135,3, tensor size:97200

2.imageData`
const imageData = image.getImageData(canvasObj); // read decoded image data from canvas
     if(!imageData){
       let createImageDataMessage = "register: Create image data failed";
       utils.logger.log({
         level: 'error',
         message: createImageDataMessage,
         label: 'faceRecognition.ts'
       });
       return { success: false, error:createImageDataMessage }
     }
3. I will test this code NodeJS directly.

**Comment by vladmandic** [comment]
Step back. Do something else. Come back tomorrow. Re-read the thread and POST RELEVANT INFORMATION.

What are the values of `tensor` or `imageData` ? Log them during execution and POST LOG!
And still no idea what is `image.getImageData(canvasObj)` Where is code for that?
Use GIST.

**Comment by danies8** [comment]
OK - thanks a lot.
