### ISSUE TITLE
Analysing images hosted on other domains

### ISSUE THREAD

**Issue by brendon** [justadudewhohacks/face-api.js#827]
I'm getting `SecurityError: The operation is insecure.` because I'm trying to analyse an image that's on my asset server (another domain). Is this the browser throwing the error or a limitation of `face-api.js`? :)

**Comment by vladmandic** [comment]
when you load an image from an external domain, browser marks canvas as tainted and doesnt allow any user app to read canvas data  

workaround is to setup a proxy to load such images or find a browser plugin that overrides browser setting (it cannot be done in user-mode apps, but plugins have near-root access so it can be done)

**Comment by brendon** [comment]
Thanks @vladmandic, very helpful. I've decided to go down the route of a small node express app on my server that can process images locally and store the metadata for use later. I've switched over to your `Human` library. Very nice work there :)
