### ISSUE TITLE
[ Electron ] Cannot import faceApi   Uncaught TypeError: this.util.TextEncoder is not a constructor

### ISSUE THREAD

**Issue by rodevasia** [justadudewhohacks/face-api.js#829]
I am trying to integrate it with electron+angluar application, it is working as expected in browser , but not working in electron ,I'm getting this error 
```
tf-core.esm.js:17 Uncaught TypeError: this.util.TextEncoder is not a constructor
    at new t (tf-core.esm.js:17)
    at Module.6636 (tf-core.esm.js:17)
    at __webpack_require__ (bootstrap:19)
    at Module.4687 (main.js:153594)
    at __webpack_require__ (bootstrap:19)
    at Module.1858 (detail.module.ts:13)
    at __webpack_require__ (bootstrap:19)
    at Module.7882 (shared.module.ts:15)
    at __webpack_require__ (bootstrap:19)
    at Module.158 (main.js:174358)

````

I know it is something related to tenserflow but I dont know solve it.

**Comment by Omnia6975** [comment]
@DOCSPLOIT  I am facing the same issue, did you find a solution ?

**Comment by rodevasia** [comment]
Yes I found it, you can either use node version and use ipc events from electron to angular or by puting the faceapi source as asset and include in `angular.json` and use it directly in angular, best of luck :crossed_fingers: :

**Comment by Omnia6975** [comment]
Thanks for the feedbacks, appreciate it.

**Comment by Omnia6975** [comment]
> 
> 
> Yes I found it, you can either use node version and use ipc events from electron to angular or by puting the faceapi source as asset and include in `angular.json` and use it directly in angular, best of luck 🤞 :

Thanks for the feedbacks, appreciate it.
