### ISSUE TITLE
Best option for detecting faces

### ISSUE THREAD

**Issue by Alireza17224** [justadudewhohacks/face-api.js#833]
Hi, I want to know which option is best for detecting faces? 
Mtccn?
Yolyo?
tiny Face Detector?

**Comment by vladmandic** [comment]
`mtcnn` is obsolete and not really working. `tiny` is well, tiny - good for extremely low powered devices. best is `SsdMobilenet`

**Comment by Alireza17224** [comment]
Thank you!
