### ISSUE TITLE
Not working on Cloudflare?

### ISSUE THREAD

**Issue by hotgeart** [justadudewhohacks/face-api.js#839]
Hi,

I'm playing with face api. My script works on local but not on prod. The only difference with my prod it's that my prod uses Cloudflare.

Cloudflare : https://hotgeart.com/face-api/ 👎 
Random hosting : http://hotgeart.000webhostapp.com/ 👍 

The code is really simple:

```html
<body>
    <h1>Upload</h1>
    <img id="inputImg" src="" style="max-height: 300px" />
    <div>
        <input
            id="queryImgUploadInput"
            type="file"
            class="waves-effect btn bold"
            onchange="loadImageFromUpload()"
            accept=".jpg, .jpeg, .png"
            />
    </div>
    <script>
        Promise.all([faceapi.nets.ssdMobilenetv1.loadFromUri("/face-api/models")]);
        
        async function loadImageFromUpload() {
          const imgFile = $("#queryImgUploadInput").get(0).files[0];
          const img = await faceapi.bufferToImage(imgFile);
          $("#inputImg").get(0).src = img.src;
        
          const detection = await faceapi.detectSingleFace(img);
        
          if (detection) {
            alert("FACE");
          } else {
            alert("NO FACE");
          }
        }
    </script>
</body>
```

The files are not corrupted, I have uploaded them several times via FTP.

Does anyone know what's going on?

Thanks

**Comment by vladmandic** [comment]
not corrupted, but served in a wrong way by **cloudflare**  
just download them manually - they do not match (and this is nothing to do with `face-api` specifically):

    # wget https://hotgeart.com/fhttps://hotgeart.com/face-api/models/ssd_mobilenetv1_model-shard1
    Saving to: ‘ssd_mobilenetv1_model-shard1’
    
    # wget http://hotgeart.000webhostapp.com/models/ssd_mobilenetv1_model-shard1
    Saving to: ‘ssd_mobilenetv1_model-shard1.1’

`ssd_mobilenetv1_model-shard1` size: **4194297** 
`ssd_mobilenetv1_model-shard1.1` size: **4194304** 

## option#1: dont host model weights on **cloudflare**, but download from a cdn  
for example `https://cdn.jsdelivr.net/npm/@vladmandic/face-api/models`

## option#2: configure cloudflare to serve specific records without additional processing  
i don't use it, but it could be related to something like http request header `encodeBody: "manual"`

**Comment by hotgeart** [comment]
I confirm the option#1 is working. I'll put the code below for others users from Google since I'll probably delete my test page.

Here's the working code:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Test Upload</title>
    <script
      type="text/javascript"
      src="https://code.jquery.com/jquery-2.1.1.min.js"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/face-api.js@0.22.2/dist/face-api.min.js"></script>
  </head>
  <body>
    <h1>Upload</h1>

    <img id="inputImg" src="" style="max-height: 300px" />

    <div>
      <input
        id="queryImgUploadInput"
        type="file"
        class="waves-effect btn bold"
        onchange="loadImageFromUpload()"
        accept=".jpg, .jpeg, .png"
      />
    </div>

    <script>
      Promise.all([faceapi.nets.ssdMobilenetv1.loadFromUri("https://cdn.jsdelivr.net/npm/@vladmandic/face-api@1.6.1/model/ssd_mobilenetv1_model-weights_manifest.json")]);

      async function loadImageFromUpload() {
        const imgFile = $("#queryImgUploadInput").get(0).files[0];
        const img = await faceapi.bufferToImage(imgFile);
        $("#inputImg").get(0).src = img.src;

        const detection = await faceapi.detectSingleFace(img);

        if (detection) {
          alert("FACE");
        } else {
          alert("NO FACE");
        }
      }
    </script>
  </body>
</html>
```
