### ISSUE TITLE
Cannot read "loadFromUri" & not able to load image.

### ISSUE THREAD

**Issue by Priyal168** [justadudewhohacks/face-api.js#847]
I am following a youtube tutorial and I am constantly getting this error in my console and I am not able to load image and canvas. 

`import {useRef,useEffect} from 'react'
import * as faceapi from "face-api.js"
import './App.css';

function App() {
  const imgRef = useRef();
  const canvasRef = useRef();
  const handleImage= async () => {
    const detections = await faceapi.detectAllFaces(imgRef.current,
      new faceapi.TinyFaceDetector())
      .withFaceLandmarks()
      .withFaceExpressions();
      console.log(detections);
  }

  useEffect(() => {
      const loadModels= () => {
        Promise.all([
          faceapi.nets.tinyFaceDectector.loadFromUri('/models'),
          faceapi.nets.faceLandmark68Net.loadFromUri('./models'),
          faceapi.nets.faceRecognitionNet.loadFromUri('/model'),
          faceapi.nets.faceExpressionNet.loadFromUri('/model')
        ])
        .then(handleImage)
        .catch((e)=>console.log(e));
      };
      imgRef.current && loadModels();
  } , []);
  
  return (
    <div className="App">
     <img 
     crossOrigin='anonymous'
     ref={imgRef}
     src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK8quAE0go5C6WOaNRrev_MXjiWYNNSDFELCXx2oAekwpqyfyDSCmVLb1AQjbmEjqfJK0&usqp=CAU"
     alt="bacgroundimage"
     width="940"
     height="650"
     /> 
     <canvas 
     ref={canvasRef}
      width="940"
      height="650"
     />
    </div>
  );
}

export default App;`

**Comment by Priyal168** [comment]
in console

> Uncaught TypeError: Cannot read properties of undefined (reading 'loadFromUri')
    at loadModels (bundle.js:43:84)
    at bundle.js:46:23
    at invokePassiveEffectCreate (bundle.js:61252:24)
    at HTMLUnknownElement.callCallback (bundle.js:41868:18)
    at Object.invokeGuardedCallbackDev (bundle.js:41917:20)
    at invokeGuardedCallback (bundle.js:41977:35)
    at flushPassiveEffectsImpl (bundle.js:61334:13)
    at unstable_runWithPriority (bundle.js:69082:16)
    at runWithPriority$1 (bundle.js:49274:14)
    at flushPassiveEffects (bundle.js:61211:18)

**Comment by vladmandic** [comment]
Make sure you load all models before using them - it doesn't seem that you do (check `.with...`statements)

Btw, I'd suggest not to use tiny, it's much worse and not much smaller than ssd.
