### ISSUE TITLE
console in error occured : SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by PrinceKhunt16** [justadudewhohacks/face-api.js#866]
useEffect(() => {
    const loadModels = () => {
      Promise.all([
        faceapi.nets.tinyFaceDetector.loadFromUri("/models"),
        faceapi.nets.faceLandmark68Net.loadFromUri("/models"),
        faceapi.nets.faceRecognitionNet.loadFromUri("/models"),
        faceapi.nets.faceExpressionNet.loadFromUri("/models"),
      ])
        .then(handleImage)
        .catch((e) => console.log(e));
    };
    imgRef.current && loadModels();
  }, []);

**Comment by PrinceKhunt16** [comment]
Please any one know about this error please give me answer.

**Comment by karimmakram** [comment]
add models in public folder

**Comment by PrinceKhunt16** [comment]
Close this issue

**Comment by PrinceKhunt16** [comment]
I tried and I did so I closed this issue.
