### ISSUE TITLE
Fail to provide models as as static assets

### ISSUE THREAD

**Issue by Chuiantw1212** [justadudewhohacks/face-api.js#88]
I've read through the post from https://itnext.io/face-api-js-javascript-api-for-face-recognition-in-the-browser-with-tensorflow-js-bcc2a6c4cf07

It mentioned that "The model files can simply be provided as static assets in your web app". 
So I've done two different approach and failed.

1. Integration with vue.js: In this approach, then i got the following error,
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at eval (loadWeightMap.js?3bcc:12)
    at step (tslib.es6.js?9ab4:97)
    at Object.eval [as next] (tslib.es6.js?9ab4:78)
    at fulfilled (tslib.es6.js?9ab4:68)

2. Native approach:  A different error,
loadWeightMap.js:12 Fetch API cannot load file:///Users/ian.chu/demo-face-api/models/ssd_mobilenetv1_model-weights_manifest.json. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ loadWeightMap.js:12

It seems to me that models can't be provided as static assets, but served by the web host. 
Could anyone correct me or show me how it can be done, I will be very grateful. Thanks.

**Comment by justadudewhohacks** [comment]
Hi,

1: The issue might be due to, how assets are served in vue.js (PS: I am not familar with vue.js), e.g. the uri might simply be wrong. Open the network panel and check verify, that the uri of the fetch request is correct.

2: I think it should be selfexplaining, that a browser can not fetch from your filesystem.

**Comment by manjuk41** [comment]
@Chuiantw1212
Unexpected token < in JSON at position 0 - this issued occurred to me when I was loading all model files at the same time. Use babel-polyfill to implement async and await or use Promise function. Everything loads up, But then I got this error  Error: Constructing tensor of shape (4608) should match the length of values (876). The same code worked when using reactjs but do not know why not on vuejs.

**Comment by justadudewhohacks** [comment]
As I already pointed out the root of the issues with loading the models lies in requesting them from a wrong route. Investigating the outgoing request in the network panel should solve it.

**Comment by greenpdx** [comment]
I am have the same problem using Vue.  I am storing the weights in ./assets.  I am wondering if there needs to be a webpack loader added to load the weights.  How did you fix this problem?

**Comment by shankha117** [comment]
> I've read through the post from https://itnext.io/face-api-js-javascript-api-for-face-recognition-in-the-browser-with-tensorflow-js-bcc2a6c4cf07
> 
> It mentioned that "The model files can simply be provided as static assets in your web app".
> So I've done two different approach and failed.
> 
> 1. Integration with vue.js: In this approach, then i got the following error,
>    Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
>    at eval (loadWeightMap.js?3bcc:12)
>    at step (tslib.es6.js?9ab4:97)
>    at Object.eval [as next] (tslib.es6.js?9ab4:78)
>    at fulfilled (tslib.es6.js?9ab4:68)
> 2. Native approach:  A different error,
>    loadWeightMap.js:12 Fetch API cannot load file:///Users/ian.chu/demo-face-api/models/ssd_mobilenetv1_model-weights_manifest.json. URL scheme must be "http" or "https" for CORS request.
>    (anonymous) @ loadWeightMap.js:12
> 
> It seems to me that models can't be provided as static assets, but served by the web host.
> Could anyone correct me or show me how it can be done, I will be very grateful. Thanks.

Did you find any solution? getting the same errors in both the ways.

**Comment by FinTalomn** [comment]
simply put the models into the ./public and not the ./src/assets directory of your vue project

**Comment by svsintel** [comment]
seams reasonable

**Comment by jeffreykthomas** [comment]
In case anyone else made the same mistake I did... I received a similar error to those above, the 'Unexpected token < in JSON at position 0' error.

The problem was how I downloaded the json file. I think I right clicked and saved... however I did it, I ended up with an html file, not a json file. Once I correctly downloaded the json, the error resolved.
