### ISSUE TITLE
Platform node has already been set. Overwriting the platform with node

### ISSUE THREAD

**Issue by danyhiol** [justadudewhohacks/face-api.js#885]
I'm trying to use this fantastic library on my nodeJS backend. But I get the following when importing TensorFlow node: `import '@tensorflow/tfjs-node'`
`Platform node has already been set. Overwriting the platform with node.`
The above error happens when I import `tfjs-node` in the same file as `face-api`.

When imported at the root of my application, I get the following error:
```js
Platform node has already been set. Overwriting the platform with [object Object].

<PATH>/tfjs-backend-cpu/src/backend_cpu.ts:20
const whereImpl = kernel_impls.whereImpl;
                               ^
TypeError: Cannot read properties of undefined (reading 'whereImpl')
    at Object.<anonymous> (<PATH>/tfjs-backend-cpu/src/backend_cpu.ts:20:32)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.Module._load (<PATH>/packages/js/src/executors/node/node-with-require-overrides.ts:16:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (<PATH>/node_modules/@tensorflow/tfjs/dist/tf.node.js:29:22)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
```

**Comment by vladmandic** [comment]
> Platform node has already been set. Overwriting the platform with [object Object].

this version of `face-api` already imports `@tensorflow/tfjs-node` (very old one), so you're ending up with double-import  

> TypeError: Cannot read properties of undefined (reading 'whereImpl')

subsequent error is because those two different versions are not compatible

**Comment by danyhiol** [comment]
Yeah, I actually found out that they were not compatible.
But I was confused since it's mentioned in the [documentation](https://github.com/justadudewhohacks/face-api.js#face-apijs-for-nodejs). Maybe updating the documentation may help in this regard.
Also, there is a console message about this:
```
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm I @tensorflow/tfjs-node, or npm I @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.
```

**Comment by vladmandic** [comment]
> Maybe updating the documentation may help in this regard

This project has been abandoned since April 2020, so not likely.
If you want, check out port compatible with modern `tfjs`: <https://github.com/vladmandic/face-api>

> Hi there 👋. Looks like you are running TensorFlow.js in Node.js. To speed things up dramatically, install our node backend, which binds to TensorFlow C++, by running npm I @tensorflow/tfjs-node, or npm I @tensorflow/tfjs-node-gpu if you have CUDA. Then call require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start of your program. Visit https://github.com/tensorflow/tfjs-node for more details.

This message is printed by underlying **TFJS** if you're trying to use **CPU** `backend`, it doesn't come from `face-api`

**Comment by danyhiol** [comment]
Thanks a lot @vladmandic 
I could successfully port my project to the provided [repo](https://github.com/vladmandic/face-api).
I guess I would go there for further issues/discussions.
