### ISSUE TITLE
Issue with parcel build

### ISSUE THREAD

**Issue by chuej** [justadudewhohacks/face-api.js#89]
Trying to bundle face-api.js for an SPA, similar setup to this:
https://github.com/tensorflow/tfjs-examples/blob/master/addition-rnn/package.json#L17

We're trying to do this:
```javascript
import * as faceapi from 'face-api.js';
```

Getting this error on the Parcel build:
```
~/workspace/project/node_modules/face-api.js/build/tinyYolov2/TinyYolov2.js:1:25: Cannot resolve dependency 'tslib'
> 1 | import * as tslib_1 from "tslib";
    |                          ^
  2 | import { TinyYolov2 as TinyYolov2Base } from 'tfjs-tiny-yolov2';
  3 | import { FaceDetection } from '../classes';
  4 | import { BOX_ANCHORS, BOX_ANCHORS_SEPARABLE, DEFAULT_MODEL_NAME, DEFAULT_MODEL_NAME_SEPARABLE_CONV, IOU_THRESHOLD, MEAN_RGB_SEPARABLE, } from './const';
```

I looked at the package.json, and it seems like `tslib` should be in `dependencies`, not `devDependencies`. 

We're working around currently by doing this:
```javascript
import * as faceapi from 'face-api.js/dist/face-api'
```
Seems hacky. The other option is setting `main` to the dist file.

**Comment by justadudewhohacks** [comment]
Probably because the build output is still using es6 imports, I think the output should be commonjs again, not sure atm why I changed that.

**Comment by chuej** [comment]
@justadudewhohacks Not sure why ES6 modules would cause this issue... The issue is being able to refer to `node_modules/tslib`. It's in `devDependencies`, which means that it will never be installed when we are consuming face-api.js.

Tensorflow.js uses ES6 modules, and it builds fine:
https://github.com/tensorflow/tfjs/blob/master/src/index.ts

**Comment by justadudewhohacks** [comment]
> @justadudewhohacks Not sure why ES6 modules would cause this issue... The issue is being able to refer to node_modules/tslib. It's in devDependencies, which means that it will never be installed when we are consuming face-api.js.

Yep you are absolutely right. Sorry for the confusion here.

Besides moving tslib fron devDependencies to dependencies, I think the output should still be commonjs instead of es6, but that's another story.
