### ISSUE TITLE
Add a configuration with external tf-js

### ISSUE THREAD

**Issue by seranus** [justadudewhohacks/face-api.js#9]
My issue is i would like to use this code as an external package with my other tfjs models.

Currently you can only have one tensorflowjs script instance any other that gets loaded after the first one breaks.

**Comment by justadudewhohacks** [comment]
Hmm i didnt try that yet, what would be required to make that work? Can you not bundle this package together with you own?

In case it helps, tf core is also exported via facepi.tf

**Comment by seranus** [comment]
I'm going to close it, managed to do it by changing the types to any and removing the tf reference
