### ISSUE TITLE
Using browser only face-api.js and getting console warning Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by ekeric13** [justadudewhohacks/face-api.js#901]
As per the docs I installed it doing:
```
npm i face-api.js
```

In the browser console though I am getting a warning of:
```
./node_modules/face-api.js/build/es6/env/createFileSystem.js
Module not found: Can't resolve 'fs' in '/Users/eric/nextapp/node_modules/face-api.js/build/es6/env'
```

Given I followed the browser installation i am not sure why it is referring to a node stdlib module.

Maybe because it is a next.js app and it is getting server rendered??

edit:
Tried dynamically importing it to avoid the server render and i still see the console warning:

https://nextjs.org/docs/advanced-features/dynamic-import#with-external-libraries

**Comment by ekeric13** [comment]
Just following up on this!

**Comment by ekeric13** [comment]
Okay i got the answer:
https://stackoverflow.com/a/67478653

it is a next.js webpack configuration thing.

**Comment by domus71** [comment]
Go to node_modules/face-api.js/package.js and add:
`
 "browser": {
    "fs": false,
    "path": false,
    "os": false
 }
`
