### ISSUE TITLE
bounding boxs coordinates

### ISSUE THREAD

**Issue by kevinisbest** [justadudewhohacks/face-api.js#92]
Hi does anyone can output the bounding boxes coordinates of the **result**?

https://github.com/justadudewhohacks/face-api.js/blob/fdfedbecf64193b4c92ad680bf0f83a60830479b/examples/views/tinyYolov2FaceDetectionWebcam.html#L106

Thanks!

**Comment by justadudewhohacks** [comment]
Not quite sure what you mean by that. `result` is an array of bounding boxes.

**Comment by kevinisbest** [comment]
Hi I followed the steps of [here](https://github.com/justadudewhohacks/face-api.js#shortcut-functions) and modified the code to below:
```js
const result = await faceapi.tinyYolov2(videoEl, forwardParams)
const result0 = result[0]
console.log(result0.detection)
```
but in browser console:
![image](https://user-images.githubusercontent.com/10130649/45491003-2f872500-b79b-11e8-8c23-c5b1c321cc45.png)
Does any problem here?
Thank you very much!

**Comment by kevinisbest** [comment]
Sorry I solved by my self!
I got the bounding boxes coordinates using `result[0].box` it returns `Rect {x: 238.43092550152085, y: 147.76242547896555, width: 229.86379377029357, height: 278.7513614399462}`

**Comment by kevinisbest** [comment]
Hello, thanks for this api and I'm still learning javascript, I have some questions.
Could you explain how **faceapi.extractFaces()** works? What's its input format and output type?
I want to extract every face in the video, and I wrote these code:
```javascript
const result = await faceapi.tinyYolov2(videoEl, forwardParams)
if (results.length != 0) { 
    result.forEach(function(element) {
        const faceImages = await faceapi.extractFaces(videoEl, element.box)
    });
}
```
Does it seem reasonable?
Thank you very much!

**Comment by justadudewhohacks** [comment]
> /**
>  * Extracts the image regions containing the detected faces.
>  *
>  * @param input The image that face detection has been performed on.
>  * @param detections The face detection results or face bounding boxes for that image.
>  * @returns The Canvases of the corresponding image region for each detected face.
>  */
> export async function extractFaces(
>   input: TNetInput,
>   detections: Array<FaceDetection | Rect>
> ): Promise<HTMLCanvasElement[]>

Implemented [here](https://github.com/justadudewhohacks/face-api.js/blob/master/src/dom/extractFaces.ts).

So yes it looks fine to me.

**Comment by kevinisbest** [comment]
@justadudewhohacks thanks for the reply!
but when I call the **faceapi.extractFaces()** , it shows
![image](https://user-images.githubusercontent.com/10130649/45737874-88364200-bc21-11e8-8018-1db24ad4f3ed.png)
my code : 
```javascript
const result = await faceapi.tinyYolov2(videoEl, forwardParams)
if (result.length != 0) { 
    result.forEach(async function(element) {
        const faceImages = await faceapi.extractFaces(videoEl, element.box)
    });
}
```

**Comment by justadudewhohacks** [comment]
`extractFaces `expects an array of detections not a single element as stated in the signature, thus -> `faceapi.extractFaces(videoEl, [element.box])`
