### ISSUE TITLE
I'm not succeeding in getting the face-api to detect faces.

### ISSUE THREAD

**Issue by davidruizdiaz** [justadudewhohacks/face-api.js#940]
I have a little issue, it's not doing face detections for me. In the console log, it shows me an empty array. And there are no errors, I also checked if the models have been loaded correctly by verifying with faceapi.nets.[model].isLoaded. Any idea what it could be? Could it have lost compatibility since the library is from 2020?

Help please!

![image](https://github.com/justadudewhohacks/face-api.js/assets/6656831/e9e8b102-88df-40f4-b642-e95913a4e792)
![image](https://github.com/justadudewhohacks/face-api.js/assets/6656831/d0ad2bd4-ecaf-47f6-87cd-0386ced1ed66)

**Comment by LeonardoMachado30** [comment]
Hi David, I saw in your code that you are calling the **'document.getElementById('video')**' and passing the ArrayNode of the video, for you to be able to capture the responses from the camera you must access the ArrayNode by simply doing this: **'document.getElementById('video')[0]**', I believe this will solve your problem

**Comment by davidruizdiaz** [comment]
Thank you very much for responding, @LeonardoMachado30. I have just carried out tests following your suggestions, but unfortunately, it also did not solve the problem on my previous laptop. Truthfully, to be able to continue the development of my project, I had to switch to another laptop where faces are detected without any issues.
