### ISSUE TITLE
Don't understand await keyword

### ISSUE THREAD

**Issue by johhnry** [justadudewhohacks/face-api.js#96]
Hey,

I have a question on the `await` keyword. In your examples, you say like : 

```js
const detections = await faceapi.ssdMobilenetv1(myImg, minConfidence, maxResults);
```

But I have this error : 

![synthax_error](https://user-images.githubusercontent.com/35373357/45918509-583ca800-be88-11e8-9044-9ea73ff43ebb.png)

Is it the new syntax of JavaScript or am I missing something?

Thanks

Joseph

**Comment by Panepo** [comment]
Hi @johhnry ,

`await` can not be used in regular functions, put it in a `async` function. `async` and `await` are javascript ES7 features, you can understand how to use it via [this post](https://javascript.info/async-await).

**Comment by johhnry** [comment]
Thank you for answering.

If I understand well, I have to put this line of code : 

```js
const detections = await faceapi.ssdMobilenetv1(myImg, minConfidence, maxResults);
```

In an `async` function like this : 

```js

async function detection(myImg,minConfidence,mmaxResults){
	return faceapi.ssdMobilenetv1(myImg, minConfidence, maxResults);
}

const detect = await detection(myImg,minConfidence,mmaxResults);
```

**Comment by johhnry** [comment]
I understood how it works.

Now I have a problem with loading the model.
Here is my code : 

```js

const net = new faceapi.Mtcnn();

let img;

function preload(){
    img = loadImage("img.jpg");
}

function setup(){
    canvas = createCanvas(1200,630);
    canvas.id('canvas');

    image(img,0,0);
    
    async function detect(){
        console.log("Detecting...");
        const forwardParams = {
            maxNumScales: 10,
            scaleFactor: 0.709,
            scoreThresholds: [0.6, 0.7, 0.7],
            minFaceSize: 20
        }
          
        const results = await faceapi.mtcnn(document.getElementById('canvas'), forwardParams);
        console.log(results);
    }

    async function loadNet(){
        console.log("Loading...");
        await net.load('models/mtcnn_model-weights_manifest.json');
    }

    loadNet().then(() => {
        console.log("Net loaded");
        detect();
    });

    noLoop();
}
```

I am using another library called p5.js but it doesn't matter.
I have this : 

![image](https://user-images.githubusercontent.com/35373357/45927122-8d9bd100-bf2e-11e8-9f99-9b502931875e.png)

I tried all the solutions to load a model (creating an instance with the json file, using faceapi.loadMtcnnModel ) but I can't load the model.

Thanks again

**Comment by justadudewhohacks** [comment]
If you are creating a new instance like this: `const net = new faceapi.Mtcnn();`, then your detection code should be  ` await net.forward(document.getElementById('canvas'), forwardParams)` instead of `await faceapi.mtcnn(document.getElementById('canvas'), forwardParams);`, otherwise you are using the global mtcnn instance. If you want to use `faceapi.mtcnn` you would have to load the mtcnn model like this: `await faceapi.loadMtcnnModel('models/mtcnn_model-weights_manifest.json')` instead of `await net.load('models/mtcnn_model-weights_manifest.json');`.

**Comment by johhnry** [comment]
Thank you so mush for your answer, it works very well ! :+1: 
Open Source is so much appreciated :)

Just a little warning : 

![image](https://user-images.githubusercontent.com/35373357/46111641-0da09000-c1e8-11e8-8c92-9f9e21403748.png)
