### ISSUE TITLE
FR: Custom builds with selected models

### ISSUE THREAD

**Issue by shershen08** [justadudewhohacks/face-api.js#99]
Thanks for creating this lib, it's a best starting point to do image recognition with JS as to me. Extensive README with links; plus working demo examples - priceless!

However, when you're down with experiments and want to have a workable solution 400kb lib size seems a lot. 
I know face-api.js is built on top of tensorflow.js core + various utilities + models. So one answer for users who need optimisation is to start using tfl.js itself. 
But if that solution is too low level maybe it could be a good idea to have a pre-built versions or custom build params (like here: https://lodash.com/custom-builds) covering only selected models. 

With that a user could choose between variety and total bundle size.

**Comment by shershen08** [comment]
Sorry, I was just meaning tensorflow.js.

My point was that if I want to use face API and use only one model I would love to have there size of a library to decrease - yes I'm not using other models and utilities related to them.

**Comment by justadudewhohacks** [comment]
I see what you mean. However, I think you will at most save a few kilobytes with this approach. Again, not sure if it is worth the effort.

**Comment by shershen08** [comment]
Ok thanks for the details. I didn't have time to go through all the code to understand it's modularity. If living out specific model related parts doesn't make the bundle smaller then of course it's not relevant.
